### ISSUE TITLE
Update on MassageController not applies

### ISSUE THREAD

**Issue by makerstorage** [munafio/chatify#10]
I published the Controllers with PHP artisan vendor:publish and make some change on the controller. But the routes still loads the controller in vendor directory. Is there a solution for that Can I also publish the routes?

Regards
Nuri

**Comment by rigonlucas** [comment]
I have a sugestion to fix this:

1. In: vendor/munafio/chatify/src/ChatifyServiceProvider.php
2. private function routesConfigurations change:
**'namespace' => 'Chatify\Http\Controllers',** => **'namespace' =>  config('chatify.namespace', 'Chatify\Http\Controllers'),**. to not break on composer update.
3. In: config/chatify.php
Add to config: **'namespace' => env('CHATIFY_NAMESPACE', 'App\Http\Controllers\vendor\Chatify'),** By default this may bem **Chatify\Http\Controllers** in config and routesConfigurations

so as not to break applications of devs that are already using, it is necessary to leave the vendor standard

Congragulation @munafio for the project, it's a great work

I hope I contributed to the project.

**Comment by munafio** [comment]
@rigonlucas I wrote a notes to your PR .. please check that to merge :)
Thanks for your contribution.

**Comment by rigonlucas** [comment]
@munafio here it is performing correctly. I suggest that you create a new branch for PR outside the master to test the change.
I realized that you have the master branch.
If you want to make this correction feel free to refuse my PR and apply the change.
Hug!

**Comment by munafio** [comment]
@rigonlucas  I've suggested some changes to your PR to be merged and save your contribution.

**Comment by rigonlucas** [comment]
Perfect, however you want. It was a pleasure to contribute! It's a beautiful project.

**Comment by munafio** [comment]
@rigonlucas Still waiting your changes :).
Thanks to you <3

**Comment by rigonlucas** [comment]
@munafio I did the PR, but it is still open.
If you want that i change anything, please, coment here
https://github.com/munafio/chatify/pull/11

**Comment by munafio** [comment]
I wrote a notes on your PR commits and still pending .. please check them and after your change, I'll merge your contribution.

**Comment by munafio** [comment]
@rigonlucas I wrote a notes on your PR commits and still pending .. please check them and after your change, I'll merge your contribution.

**Comment by khyvez** [comment]
> 3\. **'namespace' => env('CHATIFY_NAMESPACE', 'App\Http\Controllers\vendor\Chatify'),**

Hello brother, I tried  your suggestion but I'm having error. 
Target class [App\Http\Controllers\vendor\Chatify\MessagesController] does not exist.

**Comment by rigonlucas** [comment]
Hi guy. Rum composer update and after republish the config command 
You can rum the publish command for controllers

**Comment by rigonlucas** [comment]
Rum**

**Comment by rigonlucas** [comment]
@khyvez it's was been fixed manytimes ago.
Hug, and good work!

**Comment by ahmadazizfauzan** [comment]
> > 3. **'namespace' => env('CHATIFY_NAMESPACE', 'App\Http\Controllers\vendor\Chatify'),**
> 
> Hello brother, I tried your suggestion but I'm having error.
> Target class [App\Http\Controllers\vendor\Chatify\MessagesController] does not exist.

1. in App\Http\Controllers\vendor\Chatify\MessagesController, change namespace to => App\Http\Controllers\vendor\Chatify;
2. composer dump-autoload
3. php artisan config:cache
4. php artisan cache:clear

**Comment by munafio** [comment]
If you are still facing this issue, please update your Chatify to v1.0.1 which released for issues fixes.
