### ISSUE TITLE
laravel 8 support

### ISSUE THREAD

**Issue by Mhmdabbasi** [munafio/chatify#100]
Can I use this package with laravel8? And the things that I have to edit then?!
If not; then can you please tell us when **Chatify v2** going to be release?

**Comment by munafio** [comment]
@Mhmdabbasi Hi
Currently, you can make it work with Laravel 8.x by doing some manual changes as mentioned [here](https://github.com/munafio/chatify#laravel-8-support) 

+ The next release (v1.2.0) will resolve this issue by default .. and it will be released very soon.
