### ISSUE TITLE
it doesnt support above php 7.4

### ISSUE THREAD

**Issue by ayheikal** [munafio/chatify#101]

**Comment by salarzaidi** [comment]
same here 
![image](https://user-images.githubusercontent.com/38673499/119263728-ab4af800-bbf9-11eb-9a04-fddd267b977f.png)

![image](https://user-images.githubusercontent.com/38673499/119263810-f82ece80-bbf9-11eb-9636-aa83e6da357f.png)

**Comment by munafio** [comment]
@salarzaidi Hi,
It seems you required pusher manually in your app! you can not change package's dependencies like that .. pusher v7.x will be supported in the next release (v1.2.0) and it will be releases very soon.
