### ISSUE TITLE
Support for php v^7.4 and release for chatify 2

### ISSUE THREAD

**Issue by davymaish** [munafio/chatify#103]
Hi, thank you for the great package. I have some questions though. How much longer must we wait for the release of chatify 2? why not make your progress known and maybe we can contribute and help you speed up the completion of chatify 2? I think as a team chatify 2 can take less time to completion. That the advantage of open source: developers contribution, right?

**Comment by sofhin** [comment]
Hi, Davymaish. Would like to ask whether you tried to add something the package.
I am currently trying to add the feature of deleting selected message, but I encountered some issue.

**Comment by davymaish** [comment]
Im currently working on a project running on laravel v8 and php v7.4. I can't integrate the package on my project because it is locked to php v7.3. My project dependencies require php v7.4 and above. So the changes I have attempted is to migrate the package to laravel 8 and make it run on php v7.4. About php v7.4, pusher version required in the package is locked to require php v7.3. So if you edit the composer.json file to require a recent version of pusher, the issue of php v7.4 is solved. 

My request is to the owner of the package since he has promised a better, improved and updated version of chatify. That sounds good and it would be nice if we can be allowed to see what he is working on, maybe make some few suggestions and contribution and help in tackling some issues or bugs and maybe make a new feature much better.

Maybe Munafio too is working on adding that feature of deleting selected messages, who knows. I believe together we can make a much better feature than one person working alone.

My suggestion that is.

**Comment by sofhin** [comment]
Understood your request. So you are still waiting for the new version to be released. What's your project is?

**Comment by munafio** [comment]
@davymaish @sofhin Thanks for reaching out,
**First,** the next release is v1.2.0 which will be released in the next few days .. this version will resolve a lot of issues introduced by the developers and will come up with updated dependencies and UI/UX improved.. so, this version will resolve your issues.

**and second**, about v2 .. there will be a major changes so it may take some time to be released after v1.2.0 .. it will come up with new features and new UI/UX and the package will be re-coded.... like so.
So, stay tuned.

**Comment by sofhin** [comment]
@munafio is there any features been added in version 1.2?

**Comment by munafio** [comment]
> @munafio is there any features been added in version 1.2?

@sofhin  No, as I mentioned above, v2 will come up with the new features .. 

so, v1.2 is only coming to resolve community issues, Laravel 8.x support, pusher and other dependencies updates, and improvements..

**Comment by sofhin** [comment]
@munafio  Alright. BTW, I have the issue with receiving the message, there will be shown on left side, but the conversation side will not be updated unless I click on the user.

**Comment by munafio** [comment]
@sofhin 
Please keep things related to this issue only.

I'll check your issue and response to it.

**Comment by davymaish** [comment]
@munafio thanks for your response. As per your assurance that v1.2 is only a few days to be released, I will halt my dev progress of my project as the functionality I'm working on heavily rely on chatify, and thanks for the good work and kindness. I will stay tuned just waiting for the release. Hope it won't take longer than a week.
Thanks again for your response and great package.

**Comment by munafio** [comment]
> @munafio thanks for your response. As per your assurance that v1.2 is only a few days to be released, I will halt my dev progress of my project as the functionality I'm working on heavily rely on chatify, and thanks for the good work and kindness. I will stay tuned just waiting for the release. Hope it won't take longer than a week.
> 
> Thanks again for your response and great package.
> 
> 

I'll do my best to release it within a week.

**Comment by davymaish** [comment]
Thank you
