### ISSUE TITLE
The settings button has no response

### ISSUE THREAD

**Issue by sofhin** [munafio/chatify#104]
The settings button will somehow has no response. 

Any idea on how to fix it.

**Comment by munafio** [comment]
@sofhin since you have opened 2 issues related to the UI, I guess you have issues with the js codes, or jQuery issue.. 

Please check your console and track if any errors occurred

**Comment by sofhin** [comment]
![image](https://user-images.githubusercontent.com/67450858/119321083-d7748080-bcae-11eb-9e52-ba0ffb0be7f8.png)

For this, there is no error shown. From the very first day I install this, it is like this, sometimes it has response but somehow it does not.

Somehow it will show this.
DevTools failed to load SourceMap: Could not load content for http://127.0.0.1:8000/js/popper.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE

**Comment by munafio** [comment]
@sofhin this is just a warning and not related to your issue, 
What you can do, is to remove the assets :
- `public/js/chatify`
- `public/css/chatify`
- `resources/views/vendor/chatify`

and re-publish the `assets` and `views` as mentioned in the docs.

This will restore the default package's UI.

**Comment by sofhin** [comment]
Well, let me try

**Comment by sofhin** [comment]
it still the same, even I republish it

**Comment by munafio** [comment]
> it still the same, even I republish it

I'll check that, and keep you in touch

**Comment by sofhin** [comment]
sure, thanks

**Comment by munafio** [comment]
@sofhin From my side, I have reviewed your issue and all works well ..  
all issues you have opened are related to the UI and I don't know the changes you have done from your side that causing these issues!

You mentioned in another issue that it was working well before your changes,
If so, you have two options:
1- Track your changes that causes these issues.
2- Re-install the package and follow the steps mentioned in the docs (step-by-step).
