### ISSUE TITLE
File extension is not allowed

### ISSUE THREAD

**Issue by sofhin** [munafio/chatify#105]
Just to confirm.

Whenever I upload the image with png extension, it will show the error, the file extension is not allowed.

I can only upload the file with extension txt, jpg, jpeg.

But the allowed images file extension are jpg, jpeg, png and gif.
And for the file are zip, rar and txt.

Am I only the one having this issue or?

**Comment by munafio** [comment]
@sofhin I don't know what changes you have done on the package to open all these issues here! 
You have to uninstall the package and re-install it as mentioned in the docs and then I guarantee that it will work as expected.

**Comment by sofhin** [comment]
I have re-install this package, and the png file extension still the same, that's why I am here for confirmation.

**Comment by sofhin** [comment]
@munafio Sorry for disturbing.
Yes, I made some changes.
But I have reinstall the package, and test it, and I got the same error.
That's why I open the issue just for confirmation.
You may delete this issue.

**Comment by sofhin** [comment]
Sorry for disturbing. As I mentioned in the question, it is for confirmation.
Thanks for your quick reply and you may delete this issue.

**Comment by munafio** [comment]
> Sorry for disturbing. As I mentioned in the question, it is for confirmation.
> 
> Thanks for your quick reply and you may delete this issue.

I'm working on it,to be fixed with the next release v1.2.0 
Thanks to you.
