### ISSUE TITLE
How i can start a chat from another blade (not chatify page)

### ISSUE THREAD

**Issue by sultan-vc** [munafio/chatify#106]
Hey!
Thank you very much for the work done.

I have a large number of other pages on my site, some displaying individual users. How can I start a chat with them outside /chatify?

Thanks a lot in advance
With best wishes!

**Comment by munafio** [comment]
@sultan-vc Thanks for reaching out, 
Currently, Chatify does not support this feature, you can only chat within `/chatify` messenger page .. but you can create an Iframe linked to that page (/chatify) with some stylings..  and in this way you can chat with users while browsing other pages.

and maybe in the next releases will be supported, I'll keep it in mind.
