### ISSUE TITLE
Unable to install on php >= 7.4 

### ISSUE THREAD

**Issue by xenonwellz** [munafio/chatify#107]
I've been unable to install on newer PHP versions ( >= 7.4 ) because it requires version 3.4.0 or 3.4.1 of pusher-php-server which is only supported by PHP versions >=5.6 and < 7.4

Please is there any fix for this, i use PHP 7.4.18. It will also be very nice if it supports pusher-php-server ^5.0 because it is widely compatible.

 Thanks

**Comment by davymaish** [comment]
Just chill out. @munafio gave a word at this issue #103 that within this week he is going to release chatify v1.2 which will have updated dependencies, support for php v7.4 and support for laravel v8. As we approach the end of the week, I believe the awaited day most probably would be today. Lets just stay still and wait till he communicates.

**Comment by munafio** [comment]
@xenonwellz Thanks for reaching out,
As @davymaish said, v1.2 is about to be released and will solve this issue .. stay tuned, I'll keep you updated.

**Comment by xenonwellz** [comment]
@munafio, i want to know I have a package that relies on php-pusher-server v ^5.0, will chatify 1.2 support this ?

**Comment by munafio** [comment]
@davymaish @xenonwellz  SOLVED .. update to v1.2
Check out [CHANGELOG.md](https://github.com/munafio/chatify/blob/master/CHANGELOG.md) for more information about the new release.
