### ISSUE TITLE
Still no support for php-pusher-server v5.x 

### ISSUE THREAD

**Issue by xenonwellz** [munafio/chatify#109]
The current version of Chatify does not support php-pusher-server v5.x, Yes I know it's old, but I use 1 or 2 packages that requires that version of php-pusher-server , I don't know if this is the right way to talk about it... I just started becoming an active Github user. 

Thanks

**Comment by munafio** [comment]
> The current version of Chatify does not support php-pusher-server v5.x, Yes I know it's old, but I use 1 or 2 packages that requires that version of php-pusher-server , I don't know if this is the right way to talk about it... I just started becoming an active Github user. 
> 
> 
> 
> Thanks

Chatify v1.2.x supports pusher v7 from both (front/back end)
Make sure you're using the latest version of Chatify.
