### ISSUE TITLE
Some code coupled tightly with HTML presentation

### ISSUE THREAD

**Issue by zamronypj** [munafio/chatify#112]
Some part of code in controller tightly coupled with HTML presentation for example `src/Http/Controllers/MessagesController.php` line 265. In this line, It would be much better if this is be made neutral from HTML persentation as it returns JSON.

**Comment by munafio** [comment]
@zamronypj Thanks for reaching out,
Yes, with v1.x can't be fixed because it will effect the whole code, but with v2 this issue will be fixed using API routes that returns JSON instead.
