### ISSUE TITLE
Trying to get property 'messenger_color' of non-object 

### ISSUE THREAD

**Issue by sofhin** [munafio/chatify#113]
I updated the package to version 1.2.2, but when I load, it shows this error.

Trying to get property 'messenger_color' of non-object

Illuminate\Foundation\Bootstrap\HandleExceptions::handleError
C:\Users\Blessing\Desktop\new\vendor\munafio\chatify\src\Http\Controllers\MessagesController.php:63

LINE 63: 'messengerColor' => Auth::user()->messenger_color,

**Comment by munafio** [comment]
@sofhin Did you run the migrations? checkout your database users table and see if there is a column called `messenger_color` .. if not, please follow the steps mentioned in the docs and do not forget to run the migrations
