### ISSUE TITLE
No Styless

### ISSUE THREAD

**Issue by basina194** [munafio/chatify#116]
Hi, 
I installed Chatify without problems. but when i  run site. it looks like no Styles - Css. when i cheking i see errors 
![errror](https://user-images.githubusercontent.com/85841485/121815838-a1586a00-cc78-11eb-9840-50aea3dd2d35.png)
what is the problem ? can You hel me ?

**Comment by munafio** [comment]
@basina194 which version you have installed? 
This can be fixed by publishing the assets as mentioned in the docs.

**Comment by basina194** [comment]
> @basina194 which version you have installed?
> This can be fixed by publishing the assets as mentioned in the docs.

Laravel 6.20.26 i install as in https://chatify.munafio.com/installation#3-install-chatify 
i think thats is a Chatify 1.2 
 any instruction how repair this ?

**Comment by munafio** [comment]
@basina194 with Chatify v1.2.x you don't need to publish the assets manually, the artisan command in step 3 will do everything for you.

But, as I can see from your logs that you don't have the assets. What you can do is, go to: 
- `public/css/Chatify`.
- `public/js/Chatify`
- `resources/views/vendor/Chatify`
And check if exists.

or you forgot to run `npm install && npm run dev`

**Comment by Isaac009** [comment]
![error-er](https://user-images.githubusercontent.com/17350980/122397467-f61b1e00-cfb3-11eb-8aea-8d9953e73240.png)

![code-errors](https://user-images.githubusercontent.com/17350980/122398303-b7d22e80-cfb4-11eb-80fc-f0f398bf3c98.png)

I am having these issues; whenever I select the user from the list that I want to chat with, then these errors appear.
Any help, please. I really appreciate any help you can provide.

**Comment by munafio** [comment]
> ![error-er](https://user-images.githubusercontent.com/17350980/122397467-f61b1e00-cfb3-11eb-8aea-8d9953e73240.png)
> 
> 
> 
> ![code-errors](https://user-images.githubusercontent.com/17350980/122398303-b7d22e80-cfb4-11eb-80fc-f0f398bf3c98.png)
> 
> 
> 
> I am having these issues; whenever I select the user from the list that I want to chat with, then these errors appear.
> 
> Any help, please. I really appreciate any help you can provide.

Please open a new issue, 
This issue is differs from yours.
