### ISSUE TITLE
Sent photos are not shown in the info tab

### ISSUE THREAD

**Issue by sofhin** [munafio/chatify#117]
![image](https://user-images.githubusercontent.com/67450858/121826454-3c3d5c80-ccea-11eb-84b8-1110414a9139.png)

I try this in the demo app. The sent images are not shown here.

**Comment by munafio** [comment]
@sofhin you have to refresh the chat, so this part is not real-time .. this will be real-time as ti should in the next releases

**Comment by sofhin** [comment]
I refresh it, but it still the same. I took one example from the live demo app.
![image](https://user-images.githubusercontent.com/67450858/122012798-24e89700-cdf0-11eb-9adc-1c9da056775b.png)
I have refresh it, however, it doesn't appear.

**Comment by munafio** [comment]
@sofhin I'll check it out and keep you in touch about any updates related to this issue.

**Comment by munafio** [comment]
@sofhin FIXED, update Chatify package to the latest version (Now v1.2.3).
