### ISSUE TITLE
Question on V2

### ISSUE THREAD

**Issue by spartyboy** [munafio/chatify#119]
Would version 2 support jquery because not everyone use vue much? and still support bootstrap 4 template? also would it make use of broadcast route?

**Comment by munafio** [comment]
@spartyboy For now, It will be built with Vue.js, but maybe later will add a jQuery & react.js  as a frontend.
Vue.js is a very popular frontend framework with Laravel and very easy to use and to understand. But don't worry, I'll add other frontend options (React.js, jQuery ...) for other developer .. but you have to wait till the next releases after Chatify v2.

**Comment by munafio** [comment]
And your question about (broadcast routes), yes. Chatify v2 will have a broadcast & APIs routes and a clean code & structure.
I'll announce about all the new features and related things of the v2 of this package later.
So, stay tuned ❤️

**Comment by nikultaka** [comment]
How to add contacts in this system ?

**Comment by nikultaka** [comment]
I found 2 issues in this system, when we writing to particular person, it doesn't show writing indicator to the other user

**Comment by munafio** [comment]
> I found 2 issues in this system, when we writing to particular person, it doesn't show writing indicator to the other user

Please don't comment with unrelated issues here, if you have an issue then open a new issue with yours.

**Comment by VSinghhh** [comment]
Is there any time indication of when V2 is being released :) ? We are super super excited!

**Comment by munafio** [comment]
> Is there any time indication of when V2 is being released :) ? We are super super excited!

I want it to be better than the current version from all sides, and this will take some time to introduce you the new Chatify.
I'll notify you with the updates on the official Chatify's discord server:

https://discord.gg/Tfhp88NCqH

**Comment by talhahussaindev** [comment]
Illuminate\Contracts\Container\BindingResolutionException
Target class [MessagesController] does not exist.

**Comment by munafio** [comment]
> Illuminate\Contracts\Container\BindingResolutionException Target class [MessagesController] does not exist.

Please, don't comment in unrelated issues, you can open an issue if you have one!
and about your issue, check out #142

**Comment by munafio** [comment]
> > Is there any time indication of when V2 is being released :) ? We are super super excited!
> 
> I want it to be better than the current version from all sides, and this will take some time to introduce you the new Chatify. I'll notify you with the updates on the official Chatify's discord server:
> 
> https://discord.gg/Tfhp88NCqH

I'm going to close this issue, and all questions and answers about the new Chatify and it's updates, news ...etc can be found at the official Discord server above.
