### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by Isaac009** [munafio/chatify#120]
![error-er](https://user-images.githubusercontent.com/17350980/122397467-f61b1e00-cfb3-11eb-8aea-8d9953e73240.png)

![code-errors](https://user-images.githubusercontent.com/17350980/122398303-b7d22e80-cfb4-11eb-80fc-f0f398bf3c98.png)

I am having these issues; whenever I select the user from the list that I want to chat with, then these errors appear.
Any help, please. I really appreciate any help you can provide.

_Originally posted by @Isaac009 in https://github.com/munafio/chatify/issues/116#issuecomment-863206508_

**Comment by munafio** [comment]
@Isaac009 go to `network` tap in the devtools and check out each request (failed requests) to see what's happening.. 
provide me the error messages you are getting

**Comment by sofhin** [comment]
When I send the image file or the text file, I have this issue as well.
This is for fetching message (image file/attachment).
![image](https://user-images.githubusercontent.com/67450858/122638854-3223bf80-d129-11eb-9b2d-875918212389.png)

This is for sending image/attachment.
![image](https://user-images.githubusercontent.com/67450858/122638886-5ed7d700-d129-11eb-8eda-6f834c3cd832.png)

**Comment by munafio** [comment]
> When I send the image file or the text file, I have this issue as well.
> 
> This is for fetching message (image file/attachment).
> 
> ![image](https://user-images.githubusercontent.com/67450858/122638854-3223bf80-d129-11eb-9b2d-875918212389.png)
> 
> 
> 
> This is for sending image/attachment.
> 
> ![image](https://user-images.githubusercontent.com/67450858/122638886-5ed7d700-d129-11eb-8eda-6f834c3cd832.png)
> 
> 

Your issue you are facing is not related to this issue, so please open a new issue describing yours.

**Comment by sofhin** [comment]
Well, I commented here as it is also the internal error, that's why.

**Comment by munafio** [comment]
@sofhin @Isaac009 Please, first update the package to the latest version and then republish the assets to get the assets updates too.

Check out the UPGRADE.md guide for more.

**Comment by munafio** [comment]
@sofhin as I can see in your issue, that you may have changes on the assets (views -> messageCard.blade.php). There is no `duration` variable by default! so please follow as I mentioned in the comment above.

**Comment by munafio** [comment]
@sofhin @Isaac009 Join the [Discord](https://discord.gg/RaxyKVykYJ) server if you need a help installing this package.

**Comment by munafio** [comment]
@Isaac009 
If you are running Chatify v1.2.x or higher version,
then I think this issue appearing to you is related to the `migrations` table names and `models` names,
because models' names and migrations' table names has been changed (re-named).. check out the [chnage log](https://github.com/munafio/chatify/blob/master/CHANGELOG.md)

to solve this issue, publish/re-publish the assets (migrations) then migrate:
```
php artisan verndor:publish --tag=chatify-migrations --force

php artisan migrate
```

and also publish the models if not published:
```
php artisan verndor:publish --tag=chatify-models
```

and it should work as expected.
