### ISSUE TITLE
Still no Styles

### ISSUE THREAD

**Issue by basina194** [munafio/chatify#123]
Hi,
I installed Chatify without problems. but when i run site. it looks like no Styles 
![docs](https://user-images.githubusercontent.com/85841485/122684813-0d524980-d208-11eb-9a9c-579c3d67eebc.JPG)
when i run npm install && npm run dev many problems
![npm](https://user-images.githubusercontent.com/85841485/122684814-0deae000-d208-11eb-92d3-b633d46d2cbe.JPG)
![error1](https://user-images.githubusercontent.com/85841485/122684815-0e837680-d208-11eb-83ba-a514afb8bef9.JPG)

can someone help me ?

**Comment by munafio** [comment]
@basina194 I think the issue in npm dependencies of your application not the package itself!

Check Chatify's styles if exists at `/public/css/Chatify`. If not, then try publish the assets as mentioned in the docs.
+Try fixing npm errors then re-run `npm install && npm run dev`.

**Comment by basina194** [comment]
> @basina194 I think the issue in npm dependencies of your application not the package itself!
> 
> Check Chatify's styles if exists at `/public/css/Chatify`. If not, then try publish the assets as mentioned in the docs.
> +Try fixing npm errors then re-run `npm install && npm run dev`.

i understand. i knew thats not proplem wrom package. bu i really want to use chatify but i cant. 
I had fresh larvel. npm i'nstall as U see sending  not possible to fix errors. i have css in public

**Comment by munafio** [comment]
@basina194 As I understood, you have an issues with the deployment on a live serve.
You have to follow the instructions mentioned in the official docs to get it working perfectly as expected.
I'll close this issue.
