### ISSUE TITLE
Chatify only show static page

### ISSUE THREAD

**Issue by alghvzali** [munafio/chatify#124]
i installed chatify v1.0 on my already working laravel v5.8 project (unfresh project). but when i tried to access chatify it's only show static page only, i can't even search user or send message on saved message. 

i tried on fresh laravel v5.8 laravel project it's just working fine. 

-- on my working project --
![chatify error](https://user-images.githubusercontent.com/22439534/122889893-68518100-d36d-11eb-9319-5f4771993f09.PNG)

-- on fresh project --
![chatify good](https://user-images.githubusercontent.com/22439534/122890012-81f2c880-d36d-11eb-824f-5c4e9fb481a1.PNG)

**Comment by munafio** [comment]
@alghvzali Check out if any errors in the console or network tab, and also check the assets (css, js ...) if not exists then try to publish them as mentioned in the documentation.

**Comment by alghvzali** [comment]
> 
> 
> @alghvzali Check out if any errors in the console or network tab, and also check the assets (css, js ...) if not exists then try to publish them as mentioned in the documentation.

thank you for replying... 

i add jquery cdn on headLink.blade.php, it show connected status and contact list when searched. 

i follow your suggestion to check the console and network tab then i found this.

-- console tab --
![error1](https://user-images.githubusercontent.com/22439534/123206252-8fcb5980-d4e5-11eb-8864-1a4e31af71d8.PNG)

-- network tab --
![error2](https://user-images.githubusercontent.com/22439534/123206332-b38e9f80-d4e5-11eb-85a1-b723e17b934c.PNG)

**Comment by alghvzali** [comment]
it's already worked.. finally find it on web.php that i just paste the chatify web.php to my route/web.php

thanks a lot @munafio
