### ISSUE TITLE
Responsive design focus on user list

### ISSUE THREAD

**Issue by adityaps13** [munafio/chatify#126]
First of all awesome package. I have a question, when I run this chat on mobile and because of the responsive design it focuses on active conversation message body. While this is good if user I already started conversation however for new user it will just show blank. Instead I want new user focus should be on active user list/search view in mobile responsive design. I tried to look into /vendor/munafio/chatify/src/assets/js/code.js       cssMediaQueries() function but nothing changes. Can you please guide on how to set focus on active users list instead of message card/form view in responsive design especially while viewing in mobile. Thank you very much.

**Comment by munafio** [comment]
@adityaps13 Hi, Thanks for reaching out.
I have already talked about this in the official [discourd](https://discord.gg/RaxyKVykYJ) server of Chatify, I will release a new version soon that includes improvements and fixes (including yours).

Join us and keep updated ❤️
Regards.
