### ISSUE TITLE
Routes files

### ISSUE THREAD

**Issue by sglavach** [munafio/chatify#127]
It looks like you are adding the chatify routes to the web.php routes file... I also use a tenant routes file in a multi-tenancy application.  How can I get your chatify routes ALSO added and working with a tenant.php routes file?

Thanks!

**Comment by munafio** [comment]
@sglavach you have a `chatify.php` config file so you have full control on routes configurations .. and also read about tenancy with laravel and its routes configurations and `Conflicting routes`
 https://tenancyforlaravel.com/docs/v2/tenant-routes/
