### ISSUE TITLE
Chat thread based on user

### ISSUE THREAD

**Issue by sam-94** [munafio/chatify#128]
How to open selected user chat thread directly instead of a white screen. Please reply asap.
Please check: https://prnt.sc/18zvisj

**Comment by munafio** [comment]
@sam-94 Chatify not depends on a url id (url parameters) to fetch a specific user,
but you can do it yourself by modifying the `public/js/Chatify/code.js`, when there is a url param (id) do the fetch messages method.

e.g.  on `document` ready:
```js
let params = new URLSearchParams(window.location.search);
if(params.has('id'))
     const uid = params.get('id');
  // messenger = `user_${uid}`;                      Set messenger.
  // IDinfo(uid, 'user');                            fetch messages method.
```

**Comment by sam-94** [comment]
I just pass the user id in my redirect URL and this working perfectly... Thank you @munafio

**Comment by rafienleo** [comment]
@sam-94 Can you share the code that worked for you to implement this please.

**Comment by sam-94** [comment]
@rafienleo   just pass the user id  in chatify url like this: 
`<a href="{{url('chatify', $user->id)}}" class="edit-profile">Message</a>`

**Comment by sam-94** [comment]
@rafienleo Let me know if you have any other queries............

**Comment by rafienleo** [comment]
@sam-94 Thanks very much. It worked.

**Comment by redx1t** [comment]
Adding this for those who will not fully understand the explanation above. I had the same problem

`chatify?id={{ $user_id }}` for the url that will trigger start chat

in `public/js/Chatify/code.js` make this changes in the document ready section
```
$(document).ready(function () {
    let params = new URLSearchParams(window.location.search);
    if (params.has("id")) {
        var uid = params.get("id");
        setMessengerId(uid);
        setMessengerType("user");
        updateSelectedContact(uid);
        routerPush(document.title, `${url}/${uid}`); //Set messenger.
        IDinfo(uid, "user");
        console.log(`params - ${params.get("id")}`);
    }
}
```
