### ISSUE TITLE
php migration issue even without the migration file (alter table add avatar after email) ("SQLSTATE[42S22]: Column not found: 1054 Unknown column 'email' in 'users'")

### ISSUE THREAD

**Issue by codemoon2019** [munafio/chatify#13]
Hello I just getting error while I migrate the migration files even without the files needed to migrate. I already try the composer update and composer dump autoload but still I getting that error message. Because of that all of the migration file are skipped.

**Comment by pro-cms** [comment]
Hi did you create laravel authentication 
it seems you did not  , or before you install the package, create normal laravel authentication, then run migration first, Then install the package as usual,
if your on laravel 6, Run 
                                  composer require laravel/ui, Then php artisa ui:auth

**Comment by codemoon2019** [comment]
I already have that one actually I changed that column name of email with email_address and I already change it with the migration files of chatify $table->string('avatar')->default(config('chatify.user_avatar.default'))->after('email_address');  but still I getting that error.

**Comment by codemoon2019** [comment]
Thankyou for the help I've change the migration file column name direct into vendor->munafio migration folder files. Thank for the answer really appreciated.

**Comment by munafio** [comment]
Columns that **Chatify package** adds into **Users** table after migrations, is being added after **email** column .. like:
`$table->string('avatar')->after('email');`
To not add columns at the end of **Users** table.


> In the next versions, this **`after('email');`** will be changed .. because developers may not have an email column or they have, but as another column name such as your case.

**Comment by pro-cms** [comment]
hi coders, @munafio cant we use another more responsive theme for the app, it seems like it is not fully mobile-friendly, here is the link to the frontend most responsive design, let me know
https://codepen.io/drehimself/pen/KdXwxR
and this https://codepen.io/elad2412/pen/wvaNyBv

and this one with both night mode and light mode

https://codepen.io/TurkAysenur/pen/ZEbXoRZ

**Comment by munafio** [comment]
Hi,
I'll think about it in the next releases.
best regards,
Munaf.
