### ISSUE TITLE
How to add new file extensions?

### ISSUE THREAD

**Issue by sam-94** [munafio/chatify#130]
Hi @munafio sir, can you please tell me how to add new file extensions while sending attachments in chat? I have already added in 
"sendForm" file. But it's not working... check: https://prnt.sc/1duusq5
Can you please tell me where you define the function in screenshot: https://prnt.sc/1duvlzd

**Comment by labomatik** [comment]
``` https://github.com/munafio/chatify/blob/master/src/config/chatify.php ```
end of the file

```
'attachments' => [
        'folder' => 'attachments',
        'download_route_name' => 'attachments.download',
        'allowed_images' => (array) ['png','jpg','jpeg','gif'],
        'allowed_files' => (array) ['zip','rar','txt'],
    ],
```

**Comment by sam-94** [comment]
I have added the required extension but still not working... check here: https://prnt.sc/1dvoucx

**Comment by munafio** [comment]
> I have added the required extension but still not working... check here: https://prnt.sc/1dvoucx

@sam-94 as @labomatik said but also you have to update the `code.js` a validation method there
