### ISSUE TITLE
White window first sent message to black window but black window  didn't  receive any message from white window unless black refresh window.

### ISSUE THREAD

**Issue by boyamahero** [munafio/chatify#132]
<img width="1436" alt="Screen Shot 2564-07-25 at 20 00 24" src="https://user-images.githubusercontent.com/10239226/126939721-9fa18332-bcd2-49bc-9fe9-db2a1f518736.png">

**Comment by munafio** [comment]
@boyamahero could you please describe the issue you are facing? and provide me if any errors on console/network tab!

**Comment by boyamahero** [comment]
There are no errors in network tab and  in console received event from the white screen but in the contact list of the black screen is still empty.
<img width="1435" alt="Screen Shot 2564-07-29 at 01 15 09" src="https://user-images.githubusercontent.com/10239226/127375545-259470be-566d-4a74-ad83-98a455726432.png">

**Comment by munafio** [comment]
@boyamahero its Pusher's credentials issue, if the subscription failed. check out if the channel successfully subscribed from the logs in the console log tab or not
