### ISSUE TITLE
Attempt to read property "messenger_color" on null

### ISSUE THREAD

**Issue by klexcos** [munafio/chatify#133]
ErrorException
Attempt to read property "messenger_color" on null
.\app\Http\Controllers\vendor\Chatify\MessagesController.php:63
Line 63: 'messengerColor' => Auth::user()->messenger_color,

I've also checked the users table and there is a column called "messenger_color" with value

**Comment by munafio** [comment]
@klexcos is the an auth system? users table? did you migrate the migrations of Chatify?

**Comment by klexcos** [comment]
yes, I've migrated it. then I encountered another problem which is like it doubles App\Http\Controllers\vendor\Chatify\App\Http\Controllers\vendor\Chatify\MessagesController.
but I just reinstalled it and its now working fine. Thanks a lot. Cheers !
