### ISSUE TITLE
Chat Box Not Working

### ISSUE THREAD

**Issue by yasfandyar** [munafio/chatify#134]
Hi Munafio ,
Im Sorry I was busy on some where, thats why not responded at time...
Now I reinstall Chatify at my projct now its
![Screenshot (23)](https://user-images.githubusercontent.com/76943078/128348903-bdaa94c5-9b19-4a51-a4c0-159d0f3577a2.png)
![Screenshot (24)](https://user-images.githubusercontent.com/76943078/128348910-7c474795-7a89-4d19-afee-29d80fa060bb.png)
 give just five different types of errors in consol tab

**Comment by munafio** [comment]
@yasfandyar duplicated #125
