### ISSUE TITLE
Push notifications and reply in messages

### ISSUE THREAD

**Issue by SequelONE** [munafio/chatify#135]
I didn't find these elements in the documentation and demo. Will the next versions add push notifications and responses with a quote to a message on the second mouse click with a drop-down list, as in the Telegram messenger?

![Screenshot (26)](https://user-images.githubusercontent.com/14241611/128870365-52ff57d1-0d97-468a-91fa-0132499f1473.png)

**Comment by munafio** [comment]
Hi @SequelONE ,
Yes, the next Chatify releases will includes a new features as you have mentioned.

If you have a question or an idea about new features, help, or anything related to Chatify .. Join our Discord server and keep updated : https://discord.gg/Tfhp88NCqH
