### ISSUE TITLE
Missing letters

### ISSUE THREAD

**Issue by KGSanchez** [munafio/chatify#136]
I encountered myself with this issue, I don't really know how to fix it no matter what I do. Pusher console does not give any errors nor browser console. 

Any ideas to solve this issue?

![image](https://user-images.githubusercontent.com/36089975/128975646-7083f93c-0b83-4ee5-8b2f-9a75ce920dc2.png)

This is how it looks in the database 
![image](https://user-images.githubusercontent.com/36089975/128975919-1768057e-9182-44ad-abc4-9f0e29c5b4b1.png)

I might think it has something to do with the frontend?

**Comment by munafio** [comment]
@KGSanchez 
Can you inspect the message element to see the text received? is it as showing or not?

**Comment by KGSanchez** [comment]
Well, I tried it today again. And the issue didn't even show up. I'll close this issue, if anything happens in future, I'll let you know!
