### ISSUE TITLE
Security issue on chatify 

### ISSUE THREAD

**Issue by b1nslashsh** [munafio/chatify#139]
I have disclosed a  stored XSS on chatify thru hundr.dev 

https://www.huntr.dev/bounties/1625422364838-munafio/chatify you can visit here 

thank you,
muhaimin

**Comment by munafio** [comment]
@b1nslashsh Hi Abdul Muhaimin,
I have checked out your report at huntr.dev , and I would like to confirm that the upload functionality is vulnerable as in your report! 
According to that, I'm going to release a new version with security patches ASAP. If you would like or have a proper solution for this bug, do not hesitate to create a PR.

Thanks for your report and your contribution to make this project better ❤️,
Munaf

**Comment by munafio** [comment]
I will keep this issue opened, until fixing it and release the new version.
 I'll keep you up-to-date.

**Comment by b1nslashsh** [comment]
@munafio glad to hear that , if you think that was a valid one please Mark it has vaild on huntr , so huntr community will also try to give you nice fixes and you can chose one 🙂

Thanks

**Comment by munafio** [comment]
@munafio A new version has been released v1.2.5, solving this security issue.
Check out the [CHANGELOG.md](https://github.com/munafio/chatify/blob/master/CHANGELOG.md)
