### ISSUE TITLE
Missing contacts/ users

### ISSUE THREAD

**Issue by jgwisdala** [munafio/chatify#140]
First off, thank you for your wonderful contribution on the Laravel / Chat front.  I receive a 'Your contact list is empty'.  4 users in the system and they are able to login.  NPM ran fine.  No errors within browser (console or network). Pusher connecting properly.  Can send messages to myself.  ch_messages table is storing information correctly for both logged in users (msg sent to themselves).  Tried from firefox and edge.  Neither can see users.  Users register active_status = 1.  No problem saving avatars.  At a loss.

![image](https://user-images.githubusercontent.com/46096240/131029028-c2120129-ca05-47ac-a8af-26ce73426e64.png)

**Comment by munafio** [comment]
@jgwisdala In the network tab, click on (getContacts) request and check its response if it returns them or not.

**Comment by jgwisdala** [comment]
@munafio - Apologies on delay in response.  I've been out of town.  getContacts is working correctly.  The issue appears to be with search.  Laravel route list shows 'search' and no conflicts.  Any search using chatify results with Internal Error 500.

![image](https://user-images.githubusercontent.com/46096240/133008547-2a8c4594-0bd4-474d-9ded-53e322ca8131.png)

![image](https://user-images.githubusercontent.com/46096240/133008590-da65eb32-0070-4849-b1fe-b809eb28dc75.png)

Thanks!

**Comment by jgwisdala** [comment]
Located issue after turning debug back on.  Turns out my user table had columns (first and last) instead of name.  Made a few changes to the layout and controller... all is good now.  Thank you!

**Comment by samialtaher** [comment]
Hello, I have the same issue, my user table has first_name and last_name. 
But I have no clue how and where to make the changes. Can you or the author assist.

Thanks

**Comment by munafio** [comment]
@samialtaher If you have published the controllers of the package (mentioned at the docs), then all you have to do is to make your changes there at `MessagesController`.

Also, the views of the package need to be changed as well.

**Comment by samialtaher** [comment]
Actually, I just created an Accessor  and appends to the User controller and this solved this issue 



 protected $appends = ['name']; 

function getNameAttribute() {
  return $this->first_name . ' ' . $this->last_name;
}

**Comment by NEVELYNE** [comment]
![image](https://github.com/munafio/chatify/assets/50985077/bb4bef1b-3c96-424c-9120-3a9516b3a39d)
My Network tab has no error.

When I click on the getContacts method, it doesn't retrieve my users. What could I have missed. Kindly guide me

**Comment by NEVELYNE** [comment]
I don't even have a provision of messaging myself Any assistance please.
