### ISSUE TITLE
No internet access

### ISSUE THREAD

**Issue by ariffmma** [munafio/chatify#141]

**Comment by munafio** [comment]
@ariffmma Hi, 
Check out your pusher connection from the logs in the browser's console tab, also check out Pusher's credentials.

+Please, do not create an issue without providing any information about it.

**Comment by 24Degrees** [comment]
Problem:
In config/chatify.php there is a line: 
`env('PUSHER_APP_USETLS'),`

but that value needs to be true or false because no **PUSHER_APP_USETLS** exists in .env

Solution:
So change that line to:
`env('true'), `

**Comment by munafio** [comment]
> Problem:
> In config/chatify.php there is a line:
> `env('PUSHER_APP_USETLS'),`
> 
> but that value needs to be true or false because no **PUSHER_APP_USETLS** exists in .env
> 
> Solution:
> So change that line to:
> `env('true'), `

You either define a variable inside your `.env` file as `PUSHER_APP_USETLS=true`, 
or define a default value for it, go to `config/chatify.php` then change pushers options `useTLS` to `env('PUSHER_APP_USETLS', true)`

**Comment by 24Degrees** [comment]
Done! Thanks.
