### ISSUE TITLE
Target class [App\Http\Controllers\vendor\Chatify\MessagesController] does not exist after controller tag publish in Laravel 8

### ISSUE THREAD

**Issue by raphyabak** [munafio/chatify#142]

**Comment by hesammoosapour** [comment]
I have the same issue on my server even though my local doesn't have this one.

**Comment by raphyabak** [comment]
> I have the same issue on my server even though my local doesn't have this one.

I don't know why I'm getting this error, all asset has been published including the controller -tag asset

**Comment by munafio** [comment]
@hesammoosapour @raphyabak Hi, As mentioned in the docs, if you have published the controllers then you have to change routes' `namespace` at `config/chatify.php` in your application to `App\Http\Controllers\vendor\Chatify`.

[Check out this](https://chatify.munafio.com/customizations#controllers)

**Comment by raphyabak** [comment]
> @hesammoosapour @raphyabak Hi, As mentioned in the docs, if you have published the controllers then you have to change routes' `namespace` at `config/chatify.php` in your application to `App\Http\Controllers\vendor\Chatify`.
> 
> [Check out this](https://chatify.munafio.com/customizations#controllers)

Done that already, still not working

**Comment by hesammoosapour** [comment]
@munafio once I edited `CHATIFY_ROUTES_NAMESPACE` with small letter v for vendor in  `App\Http\Controllers\vendor\Chatify` , it works like charm .

Thank you , regards.

**Comment by munafio** [comment]
> > @hesammoosapour @raphyabak Hi, As mentioned in the docs, if you have published the controllers then you have to change routes' `namespace` at `config/chatify.php` in your application to `App\Http\Controllers\vendor\Chatify`.
> 
> > 
> 
> > [Check out this](https://chatify.munafio.com/customizations#controllers)
> 
> 
> 
> Done that already, still not working
> 
> 
> 
> 

Do it as @hesammoosapour did

**Comment by raphyabak** [comment]
> > > @hesammoosapour @raphyabak Hi, As mentioned in the docs, if you have published the controllers then you have to change routes' `namespace` at `config/chatify.php` in your application to `App\Http\Controllers\vendor\Chatify`.
> > 
> > 
> > > 
> > 
> > 
> > > [Check out this](https://chatify.munafio.com/customizations#controllers)
> > 
> > 
> > Done that already, still not working
> 
> Do it as @hesammoosapour did

![chatify php - lekelee - Visual Studio Code 9_6_2021 12_18_12 PM](https://user-images.githubusercontent.com/58911706/132209569-36b0bbca-09c1-4bd0-b724-8a07eae94ef3.png)
![🧨 Target class  App_Http_Controllers_vendor_Chatify_MessagesController  does not exist  and 3 more pages - Profile 1 - Microsoft​ Edge 9_6_2021 12_18_27 PM](https://user-images.githubusercontent.com/58911706/132209693-8441779c-b69c-4ae7-8802-2e172b01fa5c.png)

please kindly take a look

**Comment by hesammoosapour** [comment]
@raphyabak check your _RouteServiceProvider.php_ file , and check if your controller namespace of application is like 
`     protected $namespace = 'App\Http\Controllers';
`

**Comment by munafio** [comment]
> > > > @hesammoosapour @raphyabak Hi, As mentioned in the docs, if you have published the controllers then you have to change routes' `namespace` at `config/chatify.php` in your application to `App\Http\Controllers\vendor\Chatify`.
> 
> > > 
> 
> > > 
> 
> > > > 
> 
> > > 
> 
> > > 
> 
> > > > [Check out this](https://chatify.munafio.com/customizations#controllers)
> 
> > > 
> 
> > > 
> 
> > > Done that already, still not working
> 
> > 
> 
> > Do it as @hesammoosapour did
> 
> 
> 
> ![chatify php - lekelee - Visual Studio Code 9_6_2021 12_18_12 PM](https://user-images.githubusercontent.com/58911706/132209569-36b0bbca-09c1-4bd0-b724-8a07eae94ef3.png)
> 
> ![🧨 Target class  App_Http_Controllers_vendor_Chatify_MessagesController  does not exist  and 3 more pages - Profile 1 - Microsoft​ Edge 9_6_2021 12_18_27 PM](https://user-images.githubusercontent.com/58911706/132209693-8441779c-b69c-4ae7-8802-2e172b01fa5c.png)
> 
> 
> 
> please kindly take a look

If you already have the variable inside your .env file, then modify it there. Otherwise directly in the config file as you did and it should work.

**Comment by raphyabak** [comment]
> > > > > @hesammoosapour @raphyabak Hi, As mentioned in the docs, if you have published the controllers then you have to change routes' `namespace` at `config/chatify.php` in your application to `App\Http\Controllers\vendor\Chatify`.
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > [Check out this](https://chatify.munafio.com/customizations#controllers)
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > Done that already, still not working
> > 
> > 
> > > 
> > 
> > 
> > > Do it as @hesammoosapour did
> > 
> > 
> > ![chatify php - lekelee - Visual Studio Code 9_6_2021 12_18_12 PM](https://user-images.githubusercontent.com/58911706/132209569-36b0bbca-09c1-4bd0-b724-8a07eae94ef3.png)
> > ![🧨 Target class  App_Http_Controllers_vendor_Chatify_MessagesController  does not exist  and 3 more pages - Profile 1 - Microsoft​ Edge 9_6_2021 12_18_27 PM](https://user-images.githubusercontent.com/58911706/132209693-8441779c-b69c-4ae7-8802-2e172b01fa5c.png)
> > please kindly take a look
> 
> If you already have the variable inside your .env file, then modify it there. Otherwise directly in the config file as you did and it should work.

Don't know why It's not still working.

**Comment by munafio** [comment]
@raphyabak did you changed the namespace of the MessagesController.php ? It should be same as you've set in `config/chatify.php`

**Comment by hesammoosapour** [comment]
@raphyabak After your modifications Run these 3 commands :
`php artisan view:clear`  , `  php artisan config:clear `  ,  `php artisan route:clear` .

**Comment by munafio** [comment]
@raphyabak Please, follow the official docs. I have mentioned everything you need to know there.
[Chatify](https://chatify.munafio.com)

**Comment by raphyabak** [comment]
> @raphyabak did you changed the namespace of the MessagesController.php ? It should be same as you've set in `config/chatify.php`

This works, thanks
