### ISSUE TITLE
Update profile settings

### ISSUE THREAD

**Issue by hesammoosapour** [munafio/chatify#143]
In update your profile settings :
![image](https://user-images.githubusercontent.com/18083007/132376897-191667c8-54dc-4ae5-a1e9-33d5f84f0913.png)

Buttons for changing colors are not visible , and when I press update it shows 
![image](https://user-images.githubusercontent.com/18083007/132377934-4b227e34-c669-447c-ad91-5543f9a85879.png)

Also I can't switch from light to dark theme and reverse .
What's going on here ?

**Comment by munafio** [comment]
@hesammoosapour can you check your users database whether there is color and darck mode columns or not?

**Comment by hesammoosapour** [comment]
@munafio 
![image](https://user-images.githubusercontent.com/18083007/132951577-8ef2d7dd-b3e4-481e-add2-ccd75037dbce.png)
They do exist.

**Comment by munafio** [comment]
@hesammoosapour It seems you may have a changes that breaks the settings color and dark mode, the response is OK means no errors there but something is missing!

**Comment by hesammoosapour** [comment]
I installed a new separate version of laravel , that issue resolved .

However there is a deformation in favorites part with older version file _public\js\chatify\code.js_  I get this :
![image](https://user-images.githubusercontent.com/18083007/133660721-9546e761-9386-4ac5-9b92-66c0aeca1208.png)
but with new version of file code.js I get this one :
![image](https://user-images.githubusercontent.com/18083007/133660920-f2063a3d-a5dc-418e-a948-eb2b0003328c.png)
Which one I should keep or modify ?

**Comment by hesammoosapour** [comment]
This is what I get from _css_ and _js_ folders in _public_ folder from newer version :
![image](https://user-images.githubusercontent.com/18083007/133661891-618b125a-d1b8-4881-a2a0-93fdf38a16a3.png)
And this is what I get from _css_ and _js_ folders from older version :
![image](https://user-images.githubusercontent.com/18083007/133662022-100ceaea-5db9-4a23-bedd-4f1cdf41e4cf.png)

Apparently I should keep the older ones!

**Comment by munafio** [comment]
@hesammoosapour If you made local changes that effects the UI and updated the package, then you have to republish the `views` assets.

**Comment by hesammoosapour** [comment]
@munafio Yes I did rename my old folder `resources\views\vendor\Chatify` and then I ran the command `php artisan vendor:publish --tag=chatify-views` then I applied my changes to new one & it is working alright , Thank you .
