### ISSUE TITLE
image not showing

### ISSUE THREAD

**Issue by rahihosen** [munafio/chatify#145]
![Screenshot (9)](https://user-images.githubusercontent.com/78076350/135996492-fa2d6587-2ec8-4735-bd20-e76b9896d3b1.png)
in my app image and file saved in the folder but not show in chat.

**Comment by munafio** [comment]
@rahihosen Hi,
make sure that the `storage` has a symlink in `public` folder. if not, the run the following command:
```
php artisan storage:link
```

if the issue still there, please check out the console and inspect the images elements to make sure of the paths, and then provide me with the details.

**Comment by rahihosen** [comment]
yes, it's worked now. my link not properly created. Thanks for your quick response.

**Comment by d-minh** [comment]
I also have the same problem
there is already a symlink in the directory but the image doesn't show
can you make a video on your youtube channel to show how to fix this error
![image](https://user-images.githubusercontent.com/76049792/142713941-d878ad8a-e135-4967-8272-55759436c05f.png)
![image](https://user-images.githubusercontent.com/76049792/142714007-cf3124ec-80dc-40e3-a29a-f563bbe7a170.png)

**Comment by d-minh** [comment]
> yes, it's worked now. my link not properly created. Thanks for your quick response.

can you tell me how you install the link

**Comment by d-minh** [comment]
I got help from munafio  very dedicated you can fix this in the following way:
- Open your public folder from explorer not open on (VS CODE)
- Next, you open the storage folder, if it says an error,
![image](https://user-images.githubusercontent.com/76049792/142723151-55439d26-4481-419a-9508-ff1d6a08ed07.png)
- Delete it and run the command from the root directory of Laravel
`php artisan storage:link`
This command will symlinked storage/app/public to public/storage.

**Comment by SanaRamzan1234** [comment]
im getting the same issue...but image store in public folder .....but have url issue in chatifyMessenger.php

**Comment by SanaRamzan1234** [comment]
`  public function getUserAvatarUrl($user_avatar_name)
    {
        return self::storage()->url(config('chatify.user_avatar.folder') . '/' . $user_avatar_name);
    }

    /**
     * Get attachment's url.
     *
     * @param string $attachment_name
     * @return string
     */
    public function getAttachmentUrl($attachment_name)
    {
        return self::storage()->url(config('chatify.attachments.folder') . '/' . $attachment_name);
    }`

**Comment by SanaRamzan1234** [comment]
here error in url

**Comment by munafio** [comment]
> here error in url
> 
> 

Have you set APP_URL in your `.env` file to your app's url? this may cause a url issue as in your case.

**Comment by Domiynsbelhanda** [comment]
Hey, i'm this error, what's a correct app_url for you?

**Comment by LuqmanKhanZai** [comment]
@munafio 
I am Facing The Same Issue My app Is totally working On local 
then we go to the upload on the server Give Me multiple Issues FIrst issue Is that image Not Showing the Image 
I publish all Documents And Storage Links but do not show images And Not work API.
<img width="953" alt="Chat" src="https://user-images.githubusercontent.com/82702181/177309534-69d66257-fa1c-4c4c-9f28-30029932d172.png">
<img width="434" alt="Chat2" src="https://user-images.githubusercontent.com/82702181/177309543-9f0532df-c54f-41cd-96ad-d7197727e074.png">
@munafio Please tell me the solution to this I am using Ubuntu digital ocean.

**Comment by munafio** [comment]
@LuqmanKhanZai 

This issue is closed, and you can either find a solution from above if helps or open a new issue.

And DO NOT forget describe your issue in details with a descriptive title.

**Comment by pislarustefan** [comment]
Hi,
How to display all users and how to create groups if its possible?
Thanks

**Comment by RogerioAmaral** [comment]
> Hi, How to display all users and how to create groups if its possible? Thanks

The @vinhweb version allows you to create groups
Take a look
https://www.youtube.com/watch?v=7FtinRF-4Bc
https://github.com/munafio/chatify/pull/330

Repository
https://github.com/vinhweb/chatify

**Comment by pislarustefan** [comment]
Hi,
Thanks for your reply!

I installed

 Chatify on my existing project but I do not see the group icon.



[image: chtify.png]

**Comment by rakshasaveasweb** [comment]
![image_error](https://github.com/user-attachments/assets/8a372865-f5e3-4685-85b8-3effce404c5e)

image is not showing only image name is visible on both side of the conversation

**Comment by 10ANT** [comment]
same


> ![image_error](https://private-user-images.githubusercontent.com/163101611/358824144-8a372865-f5e3-4685-85b8-3effce404c5e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQwMDYyMzAsIm5iZiI6MTcyNDAwNTkzMCwicGF0aCI6Ii8xNjMxMDE2MTEvMzU4ODI0MTQ0LThhMzcyODY1LWY1ZTMtNDY4NS04NWI4LTNlZmZjZTQwNGM1ZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxOFQxODMyMTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lZmU5OTI4YWJkZTc4MWRmYmM1M2EzNDZkZWMwZDg5MTYyOTdlZGIxZTBiMzBlYzg4MjNkODEwMzFiZjliNmRlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.WDdA0caxwVYqaEQefK2bDRyR2n-5O0qXQQBGSxXYhN8)
> 
> image is not showing only image name is visible on both side of the conversation

**Comment by munafio** [comment]
@rakshasaveasweb @10ANT Please make sure you run the command above, and your APP_URL in your `.env` is correct, if still the same issue then please inspect element from your browser to see what url is showing for now

**Comment by ankitsingh12341** [comment]
Hello munafio
image are not showing because it show duplicate URL so please give  me solution
http://localhost/befans/public/storage/http://localhost/befans/public/storage/http://localhost/befans/public/storage/7774f296-5fff-49bb-911e-30af04459c34.jpg

![image_2024_09_10T11_34_21_793Z](https://github.com/user-attachments/assets/e7d86beb-1ae1-4e2f-837f-a03ce7e033b3)
