### ISSUE TITLE
Pusher Error - JSON returned from auth endpoint was invalid, yet status code was 200

### ISSUE THREAD

**Issue by designagencygroup** [munafio/chatify#146]
![Untitled](https://user-images.githubusercontent.com/49807537/136959791-f50f570f-f839-4839-8000-e0b2f1cd9eab.png)
![error2 pusher](https://user-images.githubusercontent.com/49807537/136959936-bcd8c2f7-895b-4e4d-8fdc-1a44f482cc30.png)

**Comment by munafio** [comment]
@DesignAgencyAdvertising Hi, 
Can you please check your applications's `<head>`, a meta-tag called `csrf-token`? can you share it with us ?

**Comment by designagencygroup** [comment]
![kkl](https://user-images.githubusercontent.com/49807537/136961302-c410b155-5fec-4482-b147-b2f03d633c12.png)
here my head

**Comment by munafio** [comment]
@DesignAgencyAdvertising The issue as it shows, related to the authentication! can you check the network tab which is next to the console tab in the browser, then select the auth request with the error

**Comment by designagencygroup** [comment]
auth seems ok 200
![auth](https://user-images.githubusercontent.com/49807537/136963054-b4f50b0b-eec0-426d-9d07-f6f2553ca944.png)

**Comment by munafio** [comment]
@DesignAgencyAdvertising what about it's response ?

**Comment by designagencygroup** [comment]
here the response
![auth](https://user-images.githubusercontent.com/49807537/136964480-d41645a6-08f1-45c3-9dfb-1a8eac28565c.png)

**Comment by munafio** [comment]
@DesignAgencyAdvertising Oh!!, sorry I did not notice the Debugger your are using😆. The DebugBar is the reason behind this issue as I can see!
You can solve this issue by following the link below which is a comment on an old issue relevant to yours:
https://github.com/munafio/chatify/issues/17#issuecomment-673906685

**Comment by designagencygroup** [comment]
ok now play well only the typing not working

**Comment by munafio** [comment]
@DesignAgencyAdvertising The `typing...` indicator uses Pusher's `client-events` so make sure you are enabled this option by going to `Pusher's dashboard > Your App > App Settings` then enable it. Also make sure of your credentials your are set.

Lastly, check out the console logs, you should see pusher connection succeeded.

Then every thing should work as expected.

**Comment by designagencygroup** [comment]
great app  thanks a lot

**Comment by AbdullahTheDev** [comment]
> @DesignAgencyAdvertising Oh!!, sorry I did not notice the Debugger your are using😆. The DebugBar is the reason behind this issue as I can see! You can solve this issue by following the link below which is a comment on an old issue relevant to yours: [#17 (comment)](https://github.com/munafio/chatify/issues/17#issuecomment-673906685)

Thank you so much, you saved my day 😊
