### ISSUE TITLE
Error : Failed sending the message! Please, check your server response; Send message status 500

### ISSUE THREAD

**Issue by imo-hub** [munafio/chatify#147]
Hi Munafio, thanks for create the great apps
But i get a little problem here,

the message can not send automatically and i need to click client profile to send or update the message
![image](https://user-images.githubusercontent.com/66655362/137366873-6800ea1d-2b09-4973-ad88-e878984fdae9.png)
![image](https://user-images.githubusercontent.com/66655362/137365678-85818db3-09a8-4bf9-b76f-f4826a7662e7.png)
![image](https://user-images.githubusercontent.com/66655362/137365852-de191d2e-8b54-481c-8091-40048b6159d4.png)
![image](https://user-images.githubusercontent.com/66655362/137365961-689cc1f0-559c-44f7-b99a-b80c7fd25299.png)

i'm using Laravel 8, php 7.4, MySQL Server and valet for windows
![image](https://user-images.githubusercontent.com/66655362/137362350-38e23a65-e4db-4ce9-a91f-a30c29194641.png)
![image](https://user-images.githubusercontent.com/66655362/137362490-05263d59-ad0a-4d4c-869d-b4a587cb9dd6.png)
![image](https://user-images.githubusercontent.com/66655362/137368955-66e3fa8b-499f-44e4-b694-c49d0a6e4968.png)
![image](https://user-images.githubusercontent.com/66655362/137362632-15943836-78b0-4bc5-be1b-06d03e178df9.png)

i follow step-by-step to install chatify
1. create apps
2. install laravel UI auth (FYI : i didn't install Laravel Debugbar)
3. install chatify
![image](https://user-images.githubusercontent.com/66655362/137363125-80a1605a-94d9-49d5-8a39-9906c76d7f13.png)
![image](https://user-images.githubusercontent.com/66655362/137363329-82735ab5-1368-4947-a9a3-42e29774e17e.png)
![image](https://user-images.githubusercontent.com/66655362/137363339-135063b1-53cb-423e-92a8-89233b1f7a99.png)

4. create some user using tinker
![image](https://user-images.githubusercontent.com/66655362/137363455-3a073628-421b-4d5d-8a02-ecb798b1ac1e.png)
![image](https://user-images.githubusercontent.com/66655362/137363719-c84b2340-06ec-4c13-b103-c41ac9928f1e.png)

5. create Pusher Account & Setting
![image](https://user-images.githubusercontent.com/66655362/137364054-9a34ecdb-9382-4ffe-bfb5-d23a9e5a7112.png)
![image](https://user-images.githubusercontent.com/66655362/137364148-939a62fc-c902-46fd-ade3-7e5670544e2b.png)

Setting on my .env file
![image](https://user-images.githubusercontent.com/66655362/137364728-73204cfb-aff7-4910-b23b-b8825308aa9c.png)

FYI : no error log from Pusher Account 
![image](https://user-images.githubusercontent.com/66655362/137364256-28545686-5848-4fa6-896d-758ed38a8208.png)
![image](https://user-images.githubusercontent.com/66655362/137364306-fadcffd3-7be5-465e-913c-803d6648f728.png)
![image](https://user-images.githubusercontent.com/66655362/137364350-8d2d0a68-09db-48fd-91e6-f64a887b64bc.png)

6. Internet speed it's ok
![image](https://user-images.githubusercontent.com/66655362/137364542-3ee36b61-5332-4bfa-8542-006637cc4091.png)

7. And no additional setting or file (just create new fresh project from Laravel)
![image](https://user-images.githubusercontent.com/66655362/137367114-fd180d34-864d-447e-92b7-1c42af913bfc.png)

8. Standard browser and up to date (no additional setting or extention)
![image](https://user-images.githubusercontent.com/66655362/137368101-bd83d1e7-82a0-4c19-ab74-1fe435cc65ca.png)

How to solve this problem?

Thanks

**Comment by munafio** [comment]
@imo-hub You did everything as mentioned in the docs very well, but you have an issue by sending a message! Can you please check out the error occurring by click on the error in the network tab and share it here?

**Comment by imo-hub** [comment]
This is my network tab
![image](https://user-images.githubusercontent.com/66655362/137414142-5eb9d98c-79eb-40f1-864c-05a971e745ea.png)

This is detail error from jquery.js
![image](https://user-images.githubusercontent.com/66655362/137414251-269898e3-8a27-4c52-8ef8-af2873490dd2.png)

Thanks

**Comment by imo-hub** [comment]
Here is the gif

https://user-images.githubusercontent.com/66655362/137417768-db35699d-5214-43d4-9a4a-8212bd540365.mp4

**Comment by munafio** [comment]
@imo-hub Click on the `sendMessage` error, not the js code (jQuery code).. I want to see the response coming from the this request

**Comment by imo-hub** [comment]
@munafio here is the preview tab
![image](https://user-images.githubusercontent.com/66655362/137571582-5794c82d-598a-49d4-bb91-426a2fd0d322.png)
![image](https://user-images.githubusercontent.com/66655362/137571590-a4d95011-2c27-4ab7-8917-fb614f4d1423.png)

- response tab
![image](https://user-images.githubusercontent.com/66655362/137571609-f02f7985-b355-48b0-ba89-4d2c4bbab3d3.png)
![image](https://user-images.githubusercontent.com/66655362/137571636-9d67a1c4-f2ae-4d34-a3be-876861f02fef.png)

- initiator tab
![image](https://user-images.githubusercontent.com/66655362/137571653-bec591a4-0ed3-4bdc-a8e1-e8e9ab042a5f.png)

- header tab
![image](https://user-images.githubusercontent.com/66655362/137571659-b8f4c908-5a12-4cb4-b2af-cd8512f871ca.png)
![image](https://user-images.githubusercontent.com/66655362/137571668-17833d36-57f8-491d-b424-ecf9bac37dbd.png)
![image](https://user-images.githubusercontent.com/66655362/137571679-2965f70f-78f7-46fc-9a56-674416005676.png)

thanks

**Comment by munafio** [comment]
@imo-hub The problem here is with GuzzleHttp client not Chatify! as the error says there is an issue with your ssl certificate, I have searched about this issue and it seems it is a common issue and there is lots of solutions you can check.

**Comment by bakerhassan20** [comment]
Can you solve this problem please

**Comment by bakerhassan20** [comment]
> @imo-hub The problem here is with GuzzleHttp client not Chatify! as the error says there is an issue with your ssl certificate, I have searched about this issue and it seems it is a common issue and there is lots of solutions you can check.

Can you solve this problem please

**Comment by Arooj097** [comment]
was this issue solved ?

**Comment by Arooj097** [comment]
i am getting no network errors but the message is still not send and no issue of SSL certificate.

**Comment by tauseedzaman** [comment]
> i am getting no network errors but the message is still not send and no issue of SSL certificate.

the same here any sulotions plz

**Comment by imo-hub** [comment]
> > i am getting no network errors but the message is still not send and no issue of SSL certificate.
> 
> the same here any sulotions plz

First, you need to check, if you use laravel-debugbar for your project or not,
If you use laravel-debugbar ([LINK](https://github.com/barryvdh/laravel-debugbar)), just disabled or un-install it

But if your problem just like mine (not use laravel-debugbar) but use laravel-valet ([LINK](https://github.com/cretueusebiu/valet-windows)) so you need to add "**_cacert.pem_**" to your php
- download "**_cacert.pem_**" from this ([LINK](https://curl.se/docs/caextract.html))
- then you put it to your php
![image](https://github.com/munafio/chatify/assets/66655362/64463350-a1fa-449e-891c-171fa1c5ac8a)
- then add it to your "**_php.ini_**" at the last line
![image](https://github.com/munafio/chatify/assets/66655362/ad4f1aa9-56b2-4717-8678-5b3fda79ca3d)

> ;;;;;;;;;;;;;;;;;;;
> ; php.ini Options ;
> ;;;;;;;;;;;;;;;;;;;
> 
> curl.cainfo="C:\php\extras\ssl\cacert.pem"

- i think if you didn't use laravel-valet ([LINK](https://github.com/cretueusebiu/valet-windows)), you don't need to add "**_cacert.pem_**" to your **_php_**, but if not working you can try this step too
- and if you use laravel-valet , just simply run "**_valet restart_**" or re-install your laravel-valet after that
- don't forget to check your Pusher Account & Setting ([LINK](https://dashboard.pusher.com/)) is correctly set

Hope it helps

**Comment by jPrado131** [comment]
@imo-hub  i'm encountering the same error but I;m not using laravel-valet and laravel-debugbar

**Comment by imo-hub** [comment]
> @imo-hub  i'm encountering the same error but I;m not using laravel-valet and laravel-debugbar

Just try the step above, put cacert.pem to your php and set php.ini.

Hope it helps

**Comment by jPrado131** [comment]
@imo-hub  Awesome ! that cacert.pem do the job . Thank you very much =)

**Comment by imo-hub** [comment]
> @imo-hub  Awesome ! that cacert.pem do the job . Thank you very much =)

No problem, nice to hear that 😊
