### ISSUE TITLE
How can we use predefined messages to send quickly on one click?

### ISSUE THREAD

**Issue by ateequrrahman97** [munafio/chatify#150]
Hello @munafio 
I hope you are doing well.
Is there any feature you provide related to predefined messages like most asked questions like linked in or Facebook page inbox?
I want to add some questions/answers to the chat box.
Please guide me.
Thanks!

**Comment by munafio** [comment]
> Hello @munafio 
> 
> I hope you are doing well.
> 
> Is there any feature you provide related to predefined messages like most asked questions like linked in or Facebook page inbox?
> 
> I want to add some questions/answers to the chat box.
> 
> Please guide me.
> 
> Thanks!

Hi,
Chatify doesn't provide such a feature but you can implement this yourself.. making a card above the input box containing your predefined messages, on click append to the input box.
