### ISSUE TITLE
User Not Showing

### ISSUE THREAD

**Issue by fiqqirahman** [munafio/chatify#151]
hello @munafio ,
i want to ask, i am using laravel version 8 and php 7.4 . and I'm using CRUDBoster as admin panel. when I install chatify in my project there is no problem.. but when http://127.0.0.1:8000/chatify user does not appear. because when I see the database there are 2 user tables :1. cms_users for CRUDBoster
2. Users for Chatify
what's the solution?
Thank you in advance
<img width="1680" alt="Screen Shot 2021-11-24 at 09 41 35" src="https://user-images.githubusercontent.com/84697641/143161812-22b3c341-a940-4ebf-a70f-c491bcbd2af2.png">

**Comment by munafio** [comment]
@fiqqirahman hi,
Please can you check the console tab to see if any errors there? If so, the go to the network and check the requests too then show us

**Comment by fiqqirahman** [comment]
hi @munafio, here is the console error
<img width="1676" alt="Screen Shot 2021-11-24 at 18 12 09" src="https://user-images.githubusercontent.com/84697641/143228418-e3a13db2-aeca-45eb-a7af-ef1b27a7086a.png">

**Comment by munafio** [comment]
> hi @munafio, here is the console error
> 
> <img width="1676" alt="Screen Shot 2021-11-24 at 18 12 09" src="https://user-images.githubusercontent.com/84697641/143228418-e3a13db2-aeca-45eb-a7af-ef1b27a7086a.png">
> 
> 

Go to the network tab, then refresh. Show us if any errors occurred

**Comment by fiqqirahman** [comment]
@munafio here is the network errors

<img width="1680" alt="Screen Shot 2021-11-25 at 08 20 16" src="https://user-images.githubusercontent.com/84697641/143335872-68b745d9-7aac-4b7b-b414-9c1c28520fa4.png">

**Comment by munafio** [comment]
> @munafio here is the network errors
> 
> 
> 
> <img width="1680" alt="Screen Shot 2021-11-25 at 08 20 16" src="https://user-images.githubusercontent.com/84697641/143335872-68b745d9-7aac-4b7b-b414-9c1c28520fa4.png">
> 
> 
> 
> 
> 
> 

Please, click on the error to see what's going on!

**Comment by fiqqirahman** [comment]
@munafio this is an error

<img width="843" alt="Screen Shot 2021-11-25 at 08 25 08" src="https://user-images.githubusercontent.com/84697641/143341140-1064cfe3-5f72-42a3-abe2-647b866ede1f.png">
<img width="844" alt="Screen Shot 2021-11-25 at 08 26 17" src="https://user-images.githubusercontent.com/84697641/143341458-6b4e7406-ffdf-492d-81e5-4b84faecfa38.png">

**Comment by munafio** [comment]
@fiqqirahman You have to be authenticated to use Chatify, and as mentioned in the docs you have to install an auth system first!

**Comment by fiqqirahman** [comment]
@munafio 
tell me, how to install auth system in chatify ?

**Comment by munafio** [comment]
> @munafio 
> 
> tell me, how to install auth system in chatify ?

Laravel's auth system!

**Comment by fiqqirahman** [comment]
oh sorry, but thanks for answering me, have a nice day @munafio
