### ISSUE TITLE
Auth issue Auth::user() is null

### ISSUE THREAD

**Issue by faisalfaiz64** [munafio/chatify#154]
Hi, I install chatify in my app and I have JWT auth in my app, but now when I run chatify it show me an error, dark_mode is empty means it is not getting my user through Auth::user()
I install in the fresh project and it works fine there, but not working with JWT

**Comment by munafio** [comment]
@faisalfaiz64 Hey, Of course it won't work because it is implemented to work on web .. you have to do something modification to get it working on APIs so you have to send auth token through the requests then you can access Auth::user if authenticated.

**Comment by faisalfaiz64** [comment]
ok, thank you.

**Comment by Gkiokan** [comment]
Just for reference. Create a custom middleware and add this one to the list of middlewares of chatify.  
If you have the token saved as cookie, it will patch your request and the auth will work as it should.  

```
if ($request->cookie('cookie_name')) {
    $request->headers->set('Authorization', 'Bearer ' . $request->cookie('cookie_name'));
}
```
