### ISSUE TITLE
Migration 'down' function has wrong table name

### ISSUE THREAD

**Issue by paulmezza81** [munafio/chatify#156]
Hi,
In the messages and favorites migrations, the 'down' function is missing the 'ch_' off the front of the table names

**Comment by munafio** [comment]
@paulmezza81 

Hi, 
I literally missed this one! .. I'll fix that in the next release as soon as possible.
And you can also make a pull request if you want to contribute.

Thank you ❤️

**Comment by munafio** [comment]
@paulmezza81 Fixed with [v1.3.1](https://github.com/munafio/chatify/releases/tag/v1.3.1).
