### ISSUE TITLE
CSS issue in FF with the contact list

### ISSUE THREAD

**Issue by sscotti** [munafio/chatify#157]
In the release it looks like this:

![image](https://user-images.githubusercontent.com/236933/147184116-2e981cc0-555c-4d75-b48f-0ce15d68f91a.png)

with an overflow, even though there appears to be available space below.

```
.messenger-tab {
	overflow: auto;
	height: calc(100% - 141px);
	display: none;
	position: relative;
}
```
if you change to:

```
.messenger-tab {
	overflow: auto;
	height: calc(100vh - 143px);
	display: none;
	position: relative;
}
```
it takes up the available space with no scroll if there are not any overflow items in the list.

![image](https://user-images.githubusercontent.com/236933/147184321-5e0a0359-fcfe-4e8c-84b8-4b6a1af819f3.png)

**Comment by munafio** [comment]
@sscotti Great job, thank you for your report and I have fixed this issue right now and I have tested it out .. will be there with the next release v1.3.2.

Thanks again
