### ISSUE TITLE
Target class [] does not exist.

### ISSUE THREAD

**Issue by NicolaCarrassi** [munafio/chatify#16]
Hi, i've installed your repository on my existing project and now when i try to log in or register an account i keep getting this error, i am using laravel 7... Do you have any idea of how i can fix this problem?

**Comment by NicolaCarrassi** [comment]
Actually I solved that, I just followed your tutorial once again, now it works perfetctly!

**Comment by diky22rp** [comment]
How to fix this problem?

**Comment by munafio** [comment]
@diky22rp What causes this issue ? where!?
Did you scaffold Laravel's authentication system ??

As @niksBari did, follow the steps mentioned in the tutorial again.

**Comment by diky22rp** [comment]
@

> @diky22rp What causes this issue ? where!?
> Did you scaffold Laravel's authentication system ??
> 
> As @niksBari did, follow the steps mentioned in the tutorial again.

After install your package, getting this error:

Target class [] does not exist , projectname\vendor\laravel\framework\src\Illuminate\Container\Container.php line 811
