### ISSUE TITLE
File extension not allowed! message rephrase.

### ISSUE THREAD

**Issue by MarJose123** [munafio/chatify#160]
Throwing message "File extension not allowed!" instead of File size limit.

https://github.com/munafio/chatify/blob/6117fdd630cbdde043ca21a978c73d98fd29162d/src/Http/Controllers/Api/MessagesController.php#L136

**Comment by munafio** [comment]
@whoami213 Hi👋, I will fix this one in the next release.
Thank you 🙏🏻
