### ISSUE TITLE
The user chat is not showing

### ISSUE THREAD

**Issue by hasanalihaolader** [munafio/chatify#161]
when using `^v1.3` `getContacts()` is call post method but web.php and api.php write get method
as you see
![148654357-ea0da6b1-0384-4541-8f70-9b8d48c07f2f](https://user-images.githubusercontent.com/23256533/149462454-38410775-0212-4d2f-94df-a7d6a21d106c.png)

but `getContacts() `is working fine as well as older version v1.2 because web.php is calling getContacts as post method

**Comment by munafio** [comment]
@RahibHasan I think it is related to the newer update that included APIs, because I have made lots of changes.
I'll check it out and fix this issue in the next coming version, and will let you know of course with the updates.

**Comment by munafio** [comment]
@RahibHasan 
to solve this issue, you have many options:

If you are using v1.3.x newer versions, then you have to 

## Option 1
Go to  `code.js` file in your app at `/public/js/Chatify/code.js`, and then go to line [789](https://github.com/munafio/chatify/blob/7933c08cd2d28217ad22527b0f5e0b58b5da0ce4/src/assets/js/code.js#L789)
and update the method from `POST` to `GET`.

## Option 1
update your code.js of Chatify package too .. also the styles if needed and which I recommend.
- code.js in your app at /public/js/Chatify/code.js (`your copy / old copy`)
- /vendor/munafio/chatify/src/assets/js/code.js


## Option 2
 use the command:
```
php artisan chatify:publish
```
But, it's important to know that this command will override your `views`, `js`, and `css` files to the new files of Chatify .. so if you have made changes, this will override your changes.

**Comment by HuluWZ** [comment]
getContacts() can't respond but it's get method in both

**Comment by munafio** [comment]
> getContacts() can't respond but it's get method in both 

What is the issue? Can you please explain?

**Comment by HuluWZ** [comment]
![image](https://user-images.githubusercontent.com/59336998/172025491-773e012d-d6c4-4314-b8fa-6267fe6603c8.png)

Error in Network tab
 getContacts() error
