### ISSUE TITLE
Installing errors on the migrations step.

### ISSUE THREAD

**Issue by jelleroorda** [munafio/chatify#163]
I'm following the installation instructions here:
https://chatify.munafio.com/installation

After publishing all relevant files with `php artisan chatify:install`, and then running `php artisan migrate` gives me the following error:
![Schermafbeelding 2022-01-20 om 10 40 36](https://user-images.githubusercontent.com/9193686/150313191-a76f92a8-a5e6-4862-ac90-8841e94c4598.png)

Basically the issue is that now there's a conflict since there are duplicate migrations (the package migrations loaded in ChatifyServiceProvider and the ones just published).

Is there a reason why the migrations are being loaded in the service provider? The point of publishing the migrations is that I can still update them or use some of them, right?

**Comment by munafio** [comment]
@jelleroorda Hi,
Yes you are right.. there is no reason to load the migrations in the service provider since we have published them with the `install` command!
That's happened because earlier, the migrations was not published by default.. that's why.
I'll fix this issue with the next release.

Thank you.

**Comment by LyndonMcjohnson** [comment]
How did you fix this issue in the meantime tho? @jelleroorda

**Comment by jelleroorda** [comment]
Since I was testing it for a project, I had just commented the line out in the vendor folder. Obviously this is not the way to go for a real project. Since the fix is really simple I would suggest you make a PR to fix it, or you can temporarily use your own fork (you need to add your fork to the “repositories” key in the composer.json).

**Comment by LyndonMcjohnson** [comment]
Got that. created a PR. thanks for the tip.

**Comment by jelleroorda** [comment]
Since I had to deploy this to a staging environment, I have applied a patch in [this fashion](https://downing.tech/posts/overriding-vendor-classes).
