### ISSUE TITLE
PusherError:Cannot broadcast client event 

### ISSUE THREAD

**Issue by 45h1f** [munafio/chatify#17]
Cannot broadcast client event (connection not subscribed to channel private-chatify)

Please help...

**Comment by ahmadazizfauzan** [comment]
set APP_DEBUG to false in .env file, php artisan config:cache, php artisan config:clear

**Comment by wikichua** [comment]
@ashif007 are u using php debugbar?
if yes, simply export the config/debugbar.php at the except section, add the chatify path. it works for me

**Comment by munafio** [comment]
Check out the suggestion above, and make sure that you're enabled client-event inside you Pusher account's settings as mentioned in the official documentation.

**Comment by diky22rp** [comment]
> if yes, simply export the config/debugbar.php at the except section, add the chatify path. it works for me

can i see your file config/debugbar.php at the except section?

**Comment by Zain541** [comment]
@munafio Are you people talking about this?
https://github.com/barryvdh/laravel-debugbar
