### ISSUE TITLE
Can't send images more than 5MB

### ISSUE THREAD

**Issue by cullobsidian7** [munafio/chatify#170]
I'm unable to send images more than 5mb. The message gets sent but the images attached does not. I've edited php.ini, config.php, code.js and still it doesn't seems to work. below are the attached images.

This is the loaded **php.ini**
![php ini](https://user-images.githubusercontent.com/77494299/158940889-9cbccf00-cea3-4a78-8c43-d91c757dac03.png)

**upload_max** limit
![upload_max](https://user-images.githubusercontent.com/77494299/158940929-5627fc23-104c-4f56-8674-6e8a037c009d.png)

**post_max** limit
![post_max](https://user-images.githubusercontent.com/77494299/158940977-3d660fb3-f226-45b0-aa51-d61db78d39c6.png)

edited **chatify.php**
![chatify php](https://user-images.githubusercontent.com/77494299/158941109-70bdf105-fa23-4c3f-b47d-8c1e64d23f7f.png)

edited **code.js**
![code js](https://user-images.githubusercontent.com/77494299/158941131-eca2d795-b414-4458-8208-5079dd76b78e.png)

This is what the message looks like. **no_preview**
![no_preview](https://user-images.githubusercontent.com/77494299/158941195-1083ec86-469d-4254-b337-394e796360ef.png)

Request 
![request](https://user-images.githubusercontent.com/77494299/158941300-a4f64271-e9bf-47ce-9c60-0e2d46d2d495.png)

Response
![response](https://user-images.githubusercontent.com/77494299/158941324-2734fa85-9aac-4cf7-8613-f9ef0ded0f0a.png)

Laravel version is - 9.5.1
PHP version is - 8.1.3

**Comment by munafio** [comment]
@cullobsidian7 the response/request seems to be fine!!
you can try to publish the controllers as mentioned at the official docs, then track/debug the request to check if the image upload  functionality working as expected or not.

+Check your database for the images, and your files too.

**Comment by cullobsidian7** [comment]
I published the controllers as you said.
Still everything is the same. The database has no entry of the image nor the filename. And attachments folder is also empty.
Just so you know, images less than 5mb get uploaded as usual, lightbox gives preview too and database also registers it.

**Comment by JonathanGrimaldo** [comment]
Hello, I recently installed Chatify, I did the test of uploading a 6Mb image just for testing.
I use Laravel 7 wt Php 7 for this example test:

My image test:

<img width="323" alt="image" src="https://user-images.githubusercontent.com/50802445/159103638-c1f72cd9-6c20-4f96-85ae-6b5cebd32663.png">

Do not modify any PHP configuration, only the following file in the following path:

`public/js/chatify/code.js ` ( My local route is `public_html/js/chatify/code.js` ) In public folder, Not vendor

`change sizeLimit to 2500000 //25Mb`

<img width="968" alt="image" src="https://user-images.githubusercontent.com/50802445/159103778-cbe8abb3-d4ad-4ab0-bce3-2bd66e61fe6b.png">

It works:

<img width="584" alt="image" src="https://user-images.githubusercontent.com/50802445/159103836-531c301f-754d-46f0-af5c-37ac941f360f.png">

**Comment by cullobsidian7** [comment]
> Hello, I recently installed Chatify, I did the test of uploading a 6Mb image just for testing. I use Laravel 7 wt Php 7 for this example test:
> 
> My image test:
> 
> <img alt="image" width="323" src="https://user-images.githubusercontent.com/50802445/159103638-c1f72cd9-6c20-4f96-85ae-6b5cebd32663.png">
> 
> Do not modify any PHP configuration, only the following file in the following path:
> 
> `public/js/chatify/code.js ` ( My local route is `public_html/js/chatify/code.js` ) In public folder, Not vendor
> 
> `change sizeLimit to 2500000 //25Mb`
> 
> <img alt="image" width="968" src="https://user-images.githubusercontent.com/50802445/159103778-cbe8abb3-d4ad-4ab0-bce3-2bd66e61fe6b.png">
> 
> It works:
> 
> <img alt="image" width="584" src="https://user-images.githubusercontent.com/50802445/159103836-531c301f-754d-46f0-af5c-37ac941f360f.png">

Yes, I know it works with laravel 8 and php 7 too. I've tried it's just with the lastest versions idk how to make it work. Alsoare you using the latest version of chatify?

**Comment by JonathanGrimaldo** [comment]
If I use the latest version of chatify, I have not tried with Laravel 9

**Comment by cullobsidian7** [comment]
I'm trying with laravel 8 and php 7 now.

**Comment by cullobsidian7** [comment]
Laravel 8, php 7.4 chatify V1.3 still the same

**Comment by cullobsidian7** [comment]
@JonathanGrimaldo can you share your composer.json please?

**Comment by JonathanGrimaldo** [comment]
@cullobsidian7 Sure, I have more packages installed but you can ignore them and only have chatify related in red.

![image](https://user-images.githubusercontent.com/50802445/159737354-31ffa5af-23b9-4e46-a9b8-91609f31cc08.png)

I uploaded the complete file in a zip file (composer.json):
[composer.zip](https://github.com/munafio/chatify/files/8334381/composer.zip)

**Comment by cullobsidian7** [comment]
> @cullobsidian7 Sure, I have more packages installed but you can ignore them and only have chatify related in red.
> 
> ![image](https://user-images.githubusercontent.com/50802445/159737354-31ffa5af-23b9-4e46-a9b8-91609f31cc08.png)
> 
> I uploaded the complete file in a zip file (composer.json): [composer.zip](https://github.com/munafio/chatify/files/8334381/composer.zip)

Thank you for sharing, actually the problem is with guzzlehttp/guzzle, can you please confirm the guzzle package version used in your chatify instance? Also can you please what are the server specifications of the server you've hosted chatify, especially the OS.

**Comment by XMMR12** [comment]
Open up the terminal or the cmd inside folder of the project and run this command :
`composer require guzzlehttp/guzzle:^7.0`

**Comment by cullobsidian7** [comment]
> Open up the terminal or the cmd inside folder of the project and run this command : `composer require guzzlehttp/guzzle:^7.0`

Didn't worked still the same, guzzle updates to 7.2

**Comment by cullobsidian7** [comment]
@JonathanGrimaldo which php version are you using ?

**Comment by shaikjilani290** [comment]
i am not able to upload the image can you please tell me what the issue

<img width="1280" alt="Screenshot 2022-03-27 at 4 14 42 PM" src="https://user-images.githubusercontent.com/87796590/160277798-baafc499-f280-4833-995a-b52f071ca470.png">

**Comment by cullobsidian7** [comment]
> i am not able to upload the image can you please tell me what the issue
> 
> <img alt="Screenshot 2022-03-27 at 4 14 42 PM" width="1280" src="https://user-images.githubusercontent.com/87796590/160277798-baafc499-f280-4833-995a-b52f071ca470.png">

Do php artisan storage:link

**Comment by munafio** [comment]
@XMMR12 @JonathanGrimaldo @shaikjilani290 @cullobsidian7 
In the `MessagesController.php` file, at [this](https://github.com/munafio/chatify/blob/69621870b71f34c8ab964c2655922d7718114271/src/Http/Controllers/MessagesController.php#L134) line .. there is a condition with `hasFile` method, this method behind the scenes checks php for file size if limited or the file too large, then it will return false .. which in this case if `false` it won't be uploaded as showing in the code of the line mentioned above.

So, it is php issue in your case .. you have to change `upload_max_filesize` and `post_max_size` in your `php.ini`. 

But :
- the `post_max_size` should be greater than `upload_max_filesize`.
- check if you have multiple php versions and you are modifying the right file then after changes restart server/php.

Also, you can [publish the controllers](https://chatify.munafio.com/customizations#controllers) and make changes on this method (send, and/or updateSettings) if you have to!.

**Comment by munafio** [comment]
Another note, with the next coming version of Chatify (v.1.4.0) will be no need to change the file size limitation from the client code and the config file. Only change it from the config file, same thing with the allowed files/images.

**Comment by munafio** [comment]
Version 1.4.0 has been released 🔥 Checkout the change log and the docs for more details.
