### ISSUE TITLE
history not showing

### ISSUE THREAD

**Issue by shaikjilani290** [munafio/chatify#172]
hi sir,
thank you for you package, i am using your charify package in my existing laravel application for chat communication, when i am open the chat url it is not showing the history can you please tell me what the issue and how to resolve that, i am sharing the two users credentials can you please check once

https://webdoc.live/public/login

username : [jilani.asf@gmail.com](mailto:jilani.asf@gmail.com)
password : 123456

username : [jilani.smartcell@gmail.com](mailto:jilani.smartcell@gmail.com)
password : 123456

**Comment by itsrafsanjani** [comment]
@shaikjilani290 try this one
https://stackoverflow.com/a/44984930

**Comment by munafio** [comment]
@itsrafsanjani as Rafsan said above, disable the strict mode and will be solved, this happens because issues related to the `group by` in mysql
