### ISSUE TITLE
Unseen Messages Counter

### ISSUE THREAD

**Issue by iamwebsurgeon** [munafio/chatify#176]
Hi Munafio, 
I appreciate you did great work.  During implementation, I observed there is 1 feature missing, if it exists, maybe chastity will be the best 1 package among all other packages. I am talking about the Unseen Message Counter. 

Moreover, I am trying to do it by myself but I am unable to listen to chatify events in Laravel Echo. Can you guide me? I am doing it in this way.
Echo.private(`chatify`)
    .listen('sent', (e) => {
        console.log(e);
    });

Echo.channel(`chatify`)
    .listen('sent', (e) => {
        consolec.log(e);
    });
Echo.private(`chatify`)
    .listen('messaging', (e) => {
        console.log(e);
    });

Echo.channel(`chatify`)
    .listen('messaging', (e) => {
        consolec.log(e);
    });

No of the above method working.

**Comment by JD456976** [comment]
This is what I'm using:

Model:
`public static function unseenCount()
    {
        return ChMessage::where('to_id', Auth::id())->where('seen', 0)->count();
    }
`

Middleware 
`      //Unseen Message Count
        $unseen = ChMessage::unseenCount();
        View::share(['unseen' => $unseen]);`


View:

` <span class="pro-count blue">{{ $unseen }}</span>`

**Comment by munafio** [comment]
@iamwebsurgeon it is already exists! or you mean something different? 
+the suggestion above will do the trick
