### ISSUE TITLE
idinfo is returning error

### ISSUE THREAD

**Issue by richprince23** [munafio/chatify#178]
I installed Chatify into an existing application but when i open the chat interface, idInfo returns a count() error

![image](https://user-images.githubusercontent.com/19754518/166169573-9113d89a-ae57-48cb-bde7-6888b27cf4d9.png)
![image](https://user-images.githubusercontent.com/19754518/166169595-29195926-09f5-45ba-b7e0-12ea2d155301.png)

error response
![image](https://user-images.githubusercontent.com/19754518/166169740-5ed58522-d7ee-421c-bb0e-ec54dbf63934.png)

**Comment by richprince23** [comment]
I can't start a new convo or send messages because of the error

**Comment by munafio** [comment]
@richprince23 Please provide more details about your issue, and your environment that your are working on.

**Comment by richprince23** [comment]
I didn't make any changes to the controllers except for the avatar path.
I followed every step on the website and the video.
after installation, when i open chatify, it shows a blank chat screen with no input field for me to type message.
And th User Info section shows blank

![image](https://user-images.githubusercontent.com/19754518/166235041-07eb6846-e0df-4738-9670-72636bc2841e.png)

![image](https://user-images.githubusercontent.com/19754518/166235315-84302f60-f280-4fca-b63f-76f77c9627b0.png)
![image](https://user-images.githubusercontent.com/19754518/166235428-8f6eeeb7-9831-48e8-986a-a1bfe190c108.png)
![image](https://user-images.githubusercontent.com/19754518/166235788-3ef7909a-37f4-4a5e-9b7d-63d21e075dd8.png)


Sorry for the plenty images

**Comment by richprince23** [comment]
Hmmm, the issue was from my user table. I have firstname and lastname columns whereas chatify uses name column. I created an accessor in User model to return the firstname and lastname as a signle column; name.

`protected $appends = ['name'];

public function getNameAttribute()
{
   return $this->firstname.' '.$this->lastname;
} `
