### ISSUE TITLE
Can't send message on live server

### ISSUE THREAD

**Issue by richprince23** [munafio/chatify#184]
Implemetation works fine on my localhost. Messages are instant and everything works as expected. But when in production, I get a Server Error as the response when I send a message.
What happens is that, I get and error icon and the message is not pushed instantly, i have to refresh the page to see that it is sent.

Shockingly, I can send a message from my localhost to my live user and it works, but can't seem to send messages from my live server.
Found out the issue is comming from line **187** and **195** below
Apparently, there is some issue with the messageCard view
![image](https://user-images.githubusercontent.com/19754518/169630741-ba0603cf-13ea-4385-86c8-273196ba49c8.png)

please I nned help

**Comment by markosole** [comment]
I am having same issues in localhost, I haven't tried with installing it on live server.

**Comment by munafio** [comment]
@markosole @richprince23 What is the error message you are getting? please provide more details.
+Make sure that you have published the assets (views....etc) as mentioned in the official documentation: https://chatify.munafio.com

**Comment by richprince23** [comment]
I found out that my ssl certificate was causing my sms and emails not to work. Once i fixed that, The errors were gone.
I thing it has something to do with server errors.

@munafio can you please make the server errors a bit verbose than just returning "Server Error"? 
it makes it harder for us to determine where exactly the error is coming from
thanks

**Comment by munafio** [comment]
@richprince23 I will in the next coming versions to improve the error handling issues. Just to mention that the message `Server Error` on production because you are set `debug: false`, it should be false and its related to Laravel itself.
