### ISSUE TITLE
not allow me a message sending

### ISSUE THREAD

**Issue by Taos191** [munafio/chatify#185]
I installed for my laravel 8.8 Framework , the rest of all connectivity is fine but it does not allow me a message sending option. please Help me

**Comment by Taos191** [comment]
![Capture](https://user-images.githubusercontent.com/106091750/169849846-13936846-3223-4f89-a1e3-5471a4b9a151.PNG)

**Comment by Taos191** [comment]
![SSS](https://user-images.githubusercontent.com/106091750/169849988-4dea2e20-c98f-4d77-bbdb-015a1ed8ef4f.PNG)

**Comment by Taos191** [comment]
![image](https://user-images.githubusercontent.com/106091750/169855798-93b8fadf-0ee3-4e23-9700-6b11d062ac4a.png)

**Comment by munafio** [comment]
@Taos191 Expand the `trace` errors and share it with us, it seems you are trying to call a method at `User` model that does not exist!

**Comment by Taos191** [comment]
![image](https://user-images.githubusercontent.com/106091750/169861150-803d3aaf-7f33-4b0f-a278-e53fd058fe70.png)

Model user exist

**Comment by Taos191** [comment]
how fixet it 

![image](https://user-images.githubusercontent.com/106091750/169861612-74ad6a84-19db-4c97-acbc-d2cea0bfa173.png)

**Comment by munafio** [comment]
@Taos191 I meant the method not the model itself

**Comment by Taos191** [comment]
yes i understand you

**Comment by munafio** [comment]
Click on the error, then expand the `trace` errors to see where the errors come from.

**Comment by Taos191** [comment]
![image](https://user-images.githubusercontent.com/106091750/169862732-05d3c559-8de8-4d7b-a246-d42fa8f84b7d.png)
![image](https://user-images.githubusercontent.com/106091750/169862769-4438b173-0def-4907-acf3-a666370ea5d4.png)

**Comment by Taos191** [comment]
![image](https://user-images.githubusercontent.com/106091750/169863601-949a96e9-024e-40b5-8d92-7ea229b623c3.png)

**Comment by munafio** [comment]
@Taos191 on each screenshot you give a different error message!
To solve the error of (group_by) just go to config/database.php then from (mysql) set the strict mode to false.. you can read more about this issue (mysql group_by) at google.

**Comment by Taos191** [comment]
![image](https://user-images.githubusercontent.com/106091750/169867472-f2bf34fb-b252-4aa0-b67f-0c52518e7e5f.png)

**Comment by Taos191** [comment]
can you help me please its very important for me

**Comment by Taos191** [comment]
![image](https://user-images.githubusercontent.com/106091750/169869297-3cd493ae-1068-4b4c-831f-21aa770b3401.png)

**Comment by Taos191** [comment]
there is no problem with web.php as I have not modified this file?

**Comment by munafio** [comment]
> ![image](https://user-images.githubusercontent.com/106091750/169869297-3cd493ae-1068-4b4c-831f-21aa770b3401.png)
> 
> 

Expand line 13

**Comment by Taos191** [comment]
![image](https://user-images.githubusercontent.com/106091750/169869642-a8377dac-bb35-46fc-b341-43f60a937058.png)

**Comment by Taos191** [comment]
![image](https://user-images.githubusercontent.com/106091750/169871316-6919b5aa-f625-4667-8f58-d3bc66c542db.png)

**Comment by munafio** [comment]
@Taos191 Can you share the source code? if you can, then share it on public Github repository and send the link here.

**Comment by Taos191** [comment]
with we transfer have a problem?

**Comment by Taos191** [comment]
https://we.tl/t-FjRhrm73qf

**Comment by munafio** [comment]
> 

Not a download link!! a github repo instead. anyway I'll check the code.

**Comment by munafio** [comment]
@Taos191 After a long search in your code and as I thought, the issue is with your code not the package. at `App\Models\User` line `48` you are using the `appends` to append the accessor `image` on each user but don't have it yet in the `user` model.

You either solve it with your needs or remove the `appends`.. it is up to you.

**Comment by munafio** [comment]
@Taos191 and please, next time make sure that the issue you open is related to the package itself not an issue with your app, so you have to check the errors and track them to lead you to the place that causing the error.

**Comment by Taos191** [comment]
sorry for being late

**Comment by Taos191** [comment]
> @Taos191 After a long search in your code and as I thought, the issue is with your code not the package. at `App\Models\User` line `48` you are using the `appends` to append the accessor `image` on each user but don't have it yet in the `user` model.
> 
> You either solve it with your needs or remove the `appends`.. it is up to you.

yesssssss
thank youuuuu
