### ISSUE TITLE
dont show  contacts cloumn left

### ISSUE THREAD

**Issue by Taos191** [munafio/chatify#186]
![image](https://user-images.githubusercontent.com/106091750/169889202-2387ec3e-ab09-4ae4-8f49-6127e0aee234.png)
![image](https://user-images.githubusercontent.com/106091750/169889251-41f92cec-f129-4257-9fdc-a7968acb90c9.png)

Hello!
Contact User dont show in Coloumn Left

And image dont show

http://localhost/storage/users-avatar/avatar.png

**Comment by Taos191** [comment]
i fixed user  in in column left

only image connot fixed

**Comment by munafio** [comment]
@Taos191 The issue is with your url, in your `.env` file, change `APP_URL` to your running url.
