### ISSUE TITLE
can't change the profil image or sent a one 

### ISSUE THREAD

**Issue by imanezerouali** [munafio/chatify#188]
since i installed chatify , i got two problems that i wasn't really able to fix it 
i can't change or send image profil( the links are ceated succefuly with the command php artisan storage :link ) , and i got an error with sending message ( i should refrech the page every time )

![image](https://user-images.githubusercontent.com/93742102/172012091-aba6b9c9-4a4a-460d-8596-84111c42003d.png)
![image](https://user-images.githubusercontent.com/93742102/172012287-fbeca7e1-a950-4ec7-8ee7-d0ed1d86c9b4.png)

**Comment by munafio** [comment]
@imanezerouali Please check the network tab to track the errors occurred

**Comment by imanezerouali** [comment]
![image](https://user-images.githubusercontent.com/93742102/172410264-655ca6d2-42a8-4d08-a29d-b471d0517b66.png)

**Comment by imanezerouali** [comment]
![image](https://user-images.githubusercontent.com/93742102/172410545-0a8935c9-a3a1-48d5-8938-29ad0d569714.png)

**Comment by imanezerouali** [comment]
![image](https://user-images.githubusercontent.com/93742102/172412284-48b65b3e-6a0b-49c8-a3fe-23c0f296ccfb.png)

**Comment by imanezerouali** [comment]
![image](https://user-images.githubusercontent.com/93742102/172415786-048ce8e2-f2c5-4165-9a43-e59abcfec1f2.png)

**Comment by imanezerouali** [comment]
![image](https://user-images.githubusercontent.com/93742102/172419249-f56c794f-77fd-4a03-93c2-6371b8dbe225.png)

**Comment by munafio** [comment]
@imanezerouali
in your image above, if you can see the request (sendMessage) with error 500 .. click on it and check out what's causing the error.

**Comment by munafio** [comment]
I have deleted the unnecessary images you sent in this issue to keep it clear for other developer who may face the same issue.

**Comment by imanezerouali** [comment]
![image](https://user-images.githubusercontent.com/93742102/172468486-b6c5320c-64b0-4605-ade9-11a0b1df165e.png)

**Comment by munafio** [comment]
@imanezerouali Not this one!! please follow my instructions .. go to `network` tab as in the first image above, then the red request `sendMessage` click on it, a panel on the right side will appear then select `response` tab. there you can find the error message sent by the server.

**Comment by imanezerouali** [comment]
![image](https://user-images.githubusercontent.com/93742102/172474486-9dcf9135-5e8e-4109-8dda-160efe789f52.png)

**Comment by munafio** [comment]
This issue is related to Pusher and your machine's timestamp. 
Follow [this link](https://support.pusher.com/hc/en-us/articles/4412509038097-What-Does-The-Timestamp-Expired-Response-From-The-Channels-Rest-API-Mean-When-Triggering-An-Event-) to solve the issue.
