### ISSUE TITLE
sending offline messages as emails

### ISSUE THREAD

**Issue by makerstorage** [munafio/chatify#19]
This is a required improvement for this great package. Do you have any idea how to implement it? If you have a solution I am here to develop it and start a pull request. I am sure most of the users want to have it

**Comment by munafio** [comment]
Can you provide more details about this functionality ?

**Comment by makerstorage** [comment]
We have an indicator of the User if he is online or offline.
If the user is offline people can message him. But he can not have info about having a message to him if he did not login to the web site. It can be great to have an email when you got an email while you are offline. So that you can click the link in the email and go to the chat web page. Twitter and others sends you an email saying that your friend sent you a direct message.
Can you add this functionality with the built-in notification support of Laravel?

**Comment by munafio** [comment]
I'll keep that in mind in the next releases .. thanks for your suggestion.

**Comment by chandlerwilcox88** [comment]
Would anyone point me to docs, source or how to implement offline message emails?

**Comment by munafio** [comment]
@chandlerwilcox88 you can do this by publishing the controller as mentioned in the docs https://chatify.munafio.com/customizations#controllers 

Then make some changes on the send method to allow sending an email (a normal Laravel email notification).

**Comment by chandlerwilcox88** [comment]
@munafio Thank you!!
