### ISSUE TITLE
Getting error: message	"Trying to get property 'id' of non-object"

### ISSUE THREAD

**Issue by samialtaher** [munafio/chatify#194]
Hi,
I installed this and initially things seemed OK. I have 2 issues:
1- On the left, i do not get a list of all users. I can only search for them and click to start a conversation.

2- Main issue: 
A- start a conversation with any user (or even the saved messages). Things work fine
B- Go to any other user and start a new conversation - OK
C- Go back to first conversation, i get the error, and the chat box to type is gone
D- also go back to second conversation , the same issue

When i do inspect element, this is the error:

server 500 - and in the response:

<html><body>
<span class="message-body-wrapper">

message | "Trying to get property 'id' of non-object"
-- | --
exception | "ErrorException"
file | "/usr/home/mysite.net/htdocs/vendor/munafio/chatify/src/ChatifyMessenger.php"
line | 120

</span>
</body>
</html>

This line 120 is: 

            'id' => $msg->id,

===

Do not understand why this is happening, and why only after changing the conversation. Before it works fine!

PS: I only changed the path to avatars and attachment in the file /usr/home/mysite.net/htdocs/vendor/munafio/chatify/src/ChatifyMessenger.php

Other than that nothing changed!

**Comment by munafio** [comment]
@samialtaher
My answer to your issues: 
1. this is how Chatify works, you have to search then start conversation to add it then to your contact list.
2. This seams to be an issue in Chatify that I'm going to solve soon.

Last, you don't have to make modifications directly on `ChatifyMessenger.php`, not a good idea to make changes in `vendor` files.

**Comment by samialtaher** [comment]
Thank for the response.

1- Understood. 
2- Looking forward to the fix. It has been driving me crazy

Where can i change the path to the avatar and attachments? Can this file ChatifyMessenger.php  be published?

**Comment by munafio** [comment]
@samialtaher you can take a look at `config/chatify.php` in your app.

Also, can you demonstrate your second issue? because after testing the issue in my side, seems OK!

**Comment by samialtaher** [comment]
I recorded a video here: https://www.loom.com/share/706d7548f4cd4fb29faf9629728844e2

**Comment by munafio** [comment]
@samialtaher  Thank you for your demonstration.
As I can see, there is an issue with the message you send to the database .. thats why it can not be loaded again because it fails.
I have tested it out on my own dev environment also on http://chatify-demo.munafio.com/ .. and there is no issue as yours! 
I'll test it out and search more about the problem, and keep you updated.

**Comment by samialtaher** [comment]
@munafio Thanks.

**Comment by munafio** [comment]
@samialtaher Chatiify v1.5.2 is now out 🚀
this issue been solved in this version, you can check it out.
