### ISSUE TITLE
Malformed UTF-8 characters, possibly incorrectly encoded

### ISSUE THREAD

**Issue by gtu-myowin** [munafio/chatify#195]
getContacts ajax was causing the error "Malformed UTF-8 characters, possibly incorrectly encoded" and I have to change the response from 

```php
return Response::json([
	'contacts' => $contacts,
	'total' => $users->total() ?? 0,
	'last_page' => $users->lastPage() ?? 1,
], 200);
```

to 

```php
return Response::json(
	mb_convert_encoding([
		'contacts' => $contacts,
		'total' => $users->total() ?? 0,
		'last_page' => $users->lastPage() ?? 1,
	], 'UTF-8', 'UTF-8'),
	200
);
```

as suggested here ([https://stackoverflow.com/a/49564258/2218290](https://stackoverflow.com/a/49564258/2218290))

Just reporting to fix in next minor release.

**Comment by munafio** [comment]
@gtu-myowin this solution depends on your own, you can change just change it like your suggestion.
