### ISSUE TITLE
Asset Files not working after php artisan vendor:publish --tag=chatify-config

### ISSUE THREAD

**Issue by JeffGepiga** [munafio/chatify#2]
Operating System: Windows 7 64bit
PHP Version : 7.3
Laravel Version: 6.10

**Comment by munafio** [comment]
can you explain how it is not working ??

**Comment by JeffGepiga** [comment]
After I followed the instruction and did the command php artisan vendor:publish, the asset file is not published in my css and js directory, so I was able to fixed it by manually moving the css and js file from vendor.

**Comment by munafio** [comment]
No, copying files from vendor will not overwrite the files and make changes ..
`vendor:publish` needs an asset tag as mentioned in the docs .. 
So, if you want to publish(config) do : 
```bash
 $ php artisan vendor:publish --tag=chatify-config 
```

or, if you want the public (assets) do:
```bash 
$ php artisan vendor:publish --tag=chatify-assets
```

that means, changing what after the `chatify-` with the asset needed.

and like so with the others mentioned in the docs .. take a look at it.
