### ISSUE TITLE
Modify pusher's response for API

### ISSUE THREAD

**Issue by gtu-myowin** [munafio/chatify#200]
Hi bro,

It's me again and thank you for the great package again.

The following code is from `app/Http/Controllers/vendor/Chatify/MessagesController.php` » `send()` method

```php
$messageData = Chatify::fetchMessage($messageID);

// send to web
Chatify::push('private-chatify', 'messaging', [
	'from_id' => Auth::user()->id,
	'to_id' => $request['id'],
	'message' => Chatify::messageCard($messageData, 'default')
]);

// send to mobile
Chatify::push('private-chatify-api', 'messaging', [
	'from_id' => Auth::user()->id,
	'to_id' => $request['id'],
	'message' => $messageData
]);
```
I am overriding the default `ChatifyMessenger.php` with `app/Chatify/CustomChatifyMessenger.php` file. In that file, I have modified `fetchMessage()` method like this 

```php
public static function fetchMessage($id, $index = null)
{
	$msg = Message::where('id', $id)->first();

	$data = [
		'index' => $index,
		'id' => (string) $msg->id,
		'status' => $msg->seen ? 'seen' : 'delivered',
		'text' => $msg->body,
		'createdAt' => $msg->created_at->timestamp,
	];

	$file_name = null;
	$msg_type = null;
	$attachment_title = null;

	if (isset($msg->attachment)) {
		$attachmentOBJ = json_decode($msg->attachment);
		$file_name = $attachmentOBJ->new_name;
		$attachment_title = htmlentities(trim($attachmentOBJ->old_name), ENT_QUOTES, 'UTF-8');

		$ext = pathinfo($file_name, PATHINFO_EXTENSION);
		$msg_type = in_array($ext, self::getAllowedImages()) ? 'image' : 'file';

		// add attachment related fields to data
		$data = array_merge($data, [
			'name' => $attachment_title,
			'uri' => env('APP_URL') . '/storage/' . config('chatify.attachments.folder') . '/' . $file_name,
			'size' => Storage::disk('public')->size('attachments/' . $file_name),
		]);
	} else {
		$msg_type = 'text';
	}

	// prepare message author
	$author = self::fetchAuthor($msg->from_id);

	// add more fields to data
	$data = array_merge($data, [
		'type' => $msg_type,
		'author' => $author,
	]);

	return $data;
}
```

The problem is, the normal response return as I formatted but the pusher response is always returning in following format. Please let me know how can I customize the response of ` Chatify::push` response. I am needing some more information in the mobile app such as attachment size.

```json
{
	"from_id": 310,
	"to_id": "305",
	"message": {
		"index": null,
		"id": 2630453454,
		"from_id": 310,
		"to_id": 305,
		"message": "",
		"attachment": [
			"70ec44e7-7d9b-4938-82b7-869c4ec0bc97.pdf",
			"my file.pdf",
			"file"
		],
		"time": "\u101c\u103d\u1014\u103a\u1001\u1032\u1037\u101e\u1031\u102c \u1005\u1000\u1039\u1000\u1014\u103a.\u1021\u1014\u100a\u103a\u1038\u1004\u101a\u103a \u1000",
		"fullTime": "2022-07-27T16:00:02.000000Z",
		"viewType": "sender",
		"seen": 0
	}
}
```

Thanks in advance!

**Comment by gtu-myowin** [comment]
Hello @munafio,

I want to add more information for you to spot the fix. I went ahead to find the root cause and found out my custom class's `fetchMessage()` method isn't overriding vendor's one.

I tried changing the response in `vendor/munafio/chatify/src/ChatifyMessenger.php` and it worked but afaik changing vendor's file is not recommend.

May I know how do you recommend to fix this?

**Comment by munafio** [comment]
@gtu-myowin When you want to override a method in `ChatifyMessenger.php` which is the main class of Chatify, then you have to follow the steps below:
- Create a class in your Laravel application (e.g. `CustomChatify.php`).
- inside your class, extend `Chatify/ChatifyMessenger` 
```php
// CustomChatify.php

<?php

//...
use Chatify\ChatifyMessenger

class CustomChatify extends ChatifyMessenger{

    //here, override the methods you want. For example:
    public function fetchMessage($id, $index = null)
    {
        //...
    }
}
```
- Use your custom class `CustomChatify` at `MessegesController.php` for both web and api controllers if needed, instead of `Chatify`:
```php
// MessagesController.php
<?php
namespace App\Http\Controllers\vendor\Chatify;

//...
use Chatify\Facades\ChatifyMessenger as Chatify; // instead of this (remove it)
use Path\To\CustomChatify as Chatify; // use this (yours), use the right path or namespace to your custom class.
//...

class MessagesController extends Controller
{
//...
}
```

**Comment by munafio** [comment]
> ```
> MessagesController
> ```

Added to the official documentation:
https://chatify.munafio.com/customizations#custom-chatify-class

**Comment by munafio** [comment]
> @gtu-myowin When you want to override a method in `ChatifyMessenger.php` which is the main class of Chatify, then you have to follow the steps below:
> 
> * Create a class in your Laravel application (e.g. `CustomChatify.php`).
> * inside your class, extend `Chatify/ChatifyMessenger`
> 
> ```
> // CustomChatify.php
> 
> <?php
> 
> //...
> use Chatify\ChatifyMessenger
> 
> class CustomChatify extends ChatifyMessenger{
> 
>     //here, override the methods you want. For example:
>     public function fetchMessage($id, $index = null)
>     {
>         //...
>     }
> }
> ```
> 
> * Use your custom class `CustomChatify` at `MessegesController.php` for both web and api controllers if needed, instead of `Chatify`:
> 
> ```
> // MessagesController.php
> <?php
> namespace App\Http\Controllers\vendor\Chatify;
> 
> //...
> use Chatify\Facades\ChatifyMessenger as Chatify; // instead of this (remove it)
> use Path\To\CustomChatify as Chatify; // use this (yours), use the right path or namespace to your custom class.
> //...
> 
> class MessagesController extends Controller
> {
> //...
> }
> ```

added to the official documentation: 
https://chatify.munafio.com/customizations#custom-chatify-class

**Comment by gtu-myowin** [comment]
Jeez! Thank you very much for your extended support and updating the doc accordingly. I was extending the `use Chatify\Facades\ChatifyMessenger` instead of `Chatify/ChatifyMessenger` and it was working fine until this. 

Now, it is all ok! Thank you bro.
