### ISSUE TITLE
Keyboard overlaping on input textfield issue on mobile

### ISSUE THREAD

**Issue by MiralGondaliya** [munafio/chatify#202]

**Comment by munafio** [comment]
@MiralGondaliya you should not open an issue without providing a details! please update you issue description with the details required to be solved.

**Comment by roqstarco** [comment]
@munafio 

We have this issue. When opening the Chat window on a mobile device the keybord of the mobile phone pops up and is covering the text input field of the chat. So the user can type but is not seeing the text input field and what he is typing.
We tried to fix it but it's not working. 

The chat is within a main <div ="row"> but that shouldn't be the issue. Content should move up somehow when keyboard is openend but doesn't.

![chatify-issue](https://user-images.githubusercontent.com/35807846/186829948-e0715b9d-580d-42eb-85f8-219ce20db16c.png)

Thanks.

**Comment by roqstarco** [comment]
@munafio Any idea what could be the issue?

**Comment by munafio** [comment]
> @munafio Any idea what could be the issue?

I'll fix this issue in the next releases, currently you can modify the css styling to fit your needs.

**Comment by roqstarco** [comment]
@munafio 
Ok, that would be amazing!
We tried everything CSS wise but it didn't work.

**Comment by munafio** [comment]
@roqstarco I have fixed this issue by changing the layout of the messaging area (header, messages area, input card) and added a js code listening on the `resize` event to make the messaging area fit the height of the viewport on change.

This fix will be included with the coming release `v1.5.6`.
