### ISSUE TITLE
image attachments and profile picture not appear

### ISSUE THREAD

**Issue by Amr-Elewa** [munafio/chatify#203]
image attachments and profile picture not appear
![002](https://user-images.githubusercontent.com/110920001/183686108-f8728c32-af18-4896-b375-4401db7cf983.png)
![001](https://user-images.githubusercontent.com/110920001/183686129-56d60313-c304-4013-8692-47e72d67586f.png)

**Comment by munafio** [comment]
@Amr-Elewa please, when you close an issue of your own don't forget to mention the solution for others who may face same issue..  or refer to a previous issue if helped.

**Comment by michaeldegraciacuento** [comment]
what is the solution for this? im getting same issue right now

**Comment by michaeldegraciacuento** [comment]
Done solving the issue, add/modify this in your code

@if($get == 'sharedPhoto')
    @php
        $images = str_replace('http://localhost/storage/', 'public/',$image);
        $fileContents = Storage::get($images);
        $base64 = base64_encode($fileContents);
        $dataImage = 'data:image/png;base64,' . $base64;
    @endphp
    <div class="shared-photo chat-image" style="background-image: url({{ $dataImage }})"></div>
@endif
<img width="1440" alt="Screenshot 2023-06-27 at 2 15 40 PM" src="https://github.com/munafio/chatify/assets/54446140/b633f470-1ac5-4374-baf5-96e309a9c874">

**Comment by sambhaskar** [comment]
Hello @michaeldegraciacuento Can you please tell me that where should i update below code:

@if($get == 'sharedPhoto')
https://github.com/php
$images = str_replace('http://localhost/storage/', 'public/',$image);
$fileContents = Storage::get($images);
$base64 = base64_encode($fileContents);
$dataImage = 'data:image/png;base64,' . $base64;
@endphp

@endif
