### ISSUE TITLE
Server Error in AWS Server

### ISSUE THREAD

**Issue by kirshi-sathish** [munafio/chatify#204]
I implemented this code in my project and its working well in local. even in aws server i'm able to send and receive messages. but while getting getcontacts in web, it shows 500 error without any explanation.

**Comment by munafio** [comment]
@kirshi-sathish it does throw errors without an explanation because the `debug mode` is false in production, you can set it `APP_DEBUG` to true to check the errors or check you logs to see what's happening there.

**Comment by DevCores** [comment]
Malformed UTF-8 characters, possibly incorrectly encoded
I get this error at 500 errors
