### ISSUE TITLE
Messages Are Disapear When Page Refresh and user cant receive messages when is offline 

### ISSUE THREAD

**Issue by AmirHosseinAminiDev** [munafio/chatify#205]
1- when two users are sending message to eachother and one of them refresh the page all messages and contacts lists that he sent message to them are disapear.

2- when a user is offline and other user send message to him , when user becomes online the received messages are not showing to user until user send him message again. 

i can record a video or send image if you want

**Comment by aliassad** [comment]
@munafio  I am facing this issue too, this is really critical, whenever user refresh the screen the chat users disappears which having new messages. The only way it came back if that user send a message again. 

Please guide are we missing any thing.

**Comment by shabnamashrafganjoie** [comment]
hi.

issue 1 :SQLSTATE[42000]: Syntax error or access violation: 1055 'laravel.users.name' isn't in GROUP BY.
solution:
short answer:
in config/database.php --> "mysql" array , set 'strict'=>false  to disable all.

or....

You can leave 'strict' => true and add modes to "mysql" option in:

```
'mysql' => [
       ...
       ....
       'strict' => true,
       'modes' => [
            //'ONLY_FULL_GROUP_BY', // Disable this to allow grouping by one column
            'STRICT_TRANS_TABLES',
            'NO_ZERO_IN_DATE',
            'NO_ZERO_DATE',
            'ERROR_FOR_DIVISION_BY_ZERO',
            'NO_AUTO_CREATE_USER',
            'NO_ENGINE_SUBSTITUTION'
        ],
 ]
```

issue2 : Malformed UTF-8 characters, possibly incorrectly encoded.

solution:
untill now you fixed just for english language messages . if you want to fix for persian language messages too, you should try this:

 1.first publish chatify controller (if you want to know how to publish it visit this site : [publish_controller](https://chatify.munafio.com/customizations ) ).

2.  go to : app/http/controllers/vendor/chatify/messagesController.php -->public function getContacts(){} .
3. add this ```$contacts= mb_convert_encoding($contacts, 'UTF-8', 'UTF-8'); ```  to messagesController.php file , like below:

```
 public function getContacts(Request $request)
    {
         ...
         ...

if (count($usersList) > 0) {
            $contacts = '';
            foreach ($usersList as $user) {
                $contacts .= Chatify::getContactItem($user);
            }
        } else {
            $contacts = '<p class="message-hint center-el"><span>Your contact list is empty</span></p>';
        }


            $contacts= mb_convert_encoding($contacts, 'UTF-8', 'UTF-8'); 


return Response::json([
            'contacts' => $contacts,
            'total' => $users->total() ?? 0,
            'last_page' => $users->lastPage() ?? 1,
        ], 200);
    }
```


good luck

@aliassad 
@AmirHosseinAminiDev

**Comment by munafio** [comment]
@AmirHosseinAminiDev Please provide more details with your issue, I can not help without a detailed issue .. any errors there? which Laravel and php version your are using? ...etc

+Thanks to @shabnamashrafganjoie for a detailed solutions that may help, @AmirHosseinAminiDev @aliassad you can check it out too.

**Comment by aliassad** [comment]
Awesome @shabnamashrafganjoie , The solution worked, thank you for sharing a detailed solution.

**Comment by Mohitsingh88** [comment]
what i do if my user name in UserProfile model
