### ISSUE TITLE
Chatify Messaging Customization

### ISSUE THREAD

**Issue by enanwangai** [munafio/chatify#211]
### Discussed in https://github.com/munafio/chatify/discussions/210

<div type='discussions-op-text'>

<sup>Originally posted by **enanwangai** August 28, 2022</sup>
Hi, thank you for this wonderful package that is simple and straightforward. 
I would need your help given that I am just familiarizing myself with Laravel. 
1. I wanted to know how to automatically show the contact list on loading of the chatify page with their last correspondence kind of like what we see in other chat platforms. Mine unfortunately does not show that and I haven't seen documentation for the same. 
2. How to turn the Chatify messages into events to be displayed as notifications via Pusher on the home page. 

Kindly assist me.
Regards.</div>

**Comment by munafio** [comment]
@enanwangai Keep it as a discussion since there are no issues to solve.
