### ISSUE TITLE
How to wrap the chat main screen in anouther page 

### ISSUE THREAD

**Issue by majedqatousa** [munafio/chatify#212]
Hello , 
i neet to wrap chat main screen with my header  and side  menu in my web site 
how i can  do it ? 
thank you  

laravel v : 9

**Comment by munafio** [comment]
@majedqatousa you can use `Iframe`, or use the views in you page.

**Comment by jayomayan** [comment]
@majedqatousa are you able to accomplish this? if yes, how?
