### ISSUE TITLE
[BUGS] After update version, from 1.5.0 to 1.5.2 it's break

### ISSUE THREAD

**Issue by illusi03** [munafio/chatify#213]
I have problem with pusher, after investigation i think it's route **chatify/chat/auth** has not called if i update version from 1.5.0 to 1.5.2.
In version 1.5.0 it's normally work, but upper version it's not working (Because it's not called route **chatify/chat/auth**).
Here some log all route when i go to http://localhost:[PORT]/chatify in version 1.5.2
![image](https://user-images.githubusercontent.com/52351532/188450126-163a2549-2c45-4e84-8b31-3dcbe41328d4.png)
And here is version 1.5.0,
![image](https://user-images.githubusercontent.com/52351532/188450187-714a585b-1554-4f13-83c6-10259b260d21.png)
I see the different changes in that version, maybe because update version guzzle package ? (Maybe), i don't know why it's not working in newer version.

Thankyou in advance

**Comment by munafio** [comment]
@illusi03 It is working on the newer/older version and did test it even on Laravel 9 and lower .. you can check the console logs or network tab to see if anything is going wrong there?

**Comment by illusi03** [comment]
I had already checked and it's error auth error (can't redirect of unauth user). 
Maybe i will check in newer version, thankyou verymuch for response mr munaf. Jazakallohu khoiron
