### ISSUE TITLE
failed to start converstation

### ISSUE THREAD

**Issue by zeehan805** [munafio/chatify#216]
I am trying to start new conversation with other user but when i clicked on his name no action or response. and get this error in console
code.js:952 Server error, check your response
error @ code.js:952
fire @ jquery.js?8262:3500
fireWith @ jquery.js?8262:3630
done @ jquery.js?8262:9798
eval @ jquery.js?8262:10057
load (async)
send @ jquery.js?8262:10076
ajax @ jquery.js?8262:9690
getSharedPhotos @ code.js:943
IDinfo @ code.js:364
(anonymous) @ code.js:1274
dispatch @ jquery.js?8262:5430
elemData.handle @ jquery.js?8262:5234
code.js:400 Error, check server response!

![image](https://user-images.githubusercontent.com/90240112/189290506-63654f79-5989-49b8-ac26-81a21f5faf92.png)

**Comment by munafio** [comment]
@zeehan805 check out `network` tab in your browser's web dev tools (next to/before `console` tab), there you can see the detailed issue occurred with the request you sent.

**Comment by zeehan805** [comment]
Thank you problem solved...

**Comment by rashadkhan359** [comment]
What was the problem that you found? Mine doesn't so anything in network. The chat does't get created when clicked on after searching a user. It stays on the same page.
