### ISSUE TITLE
Pusher not defined and so template with laravel voyager

### ISSUE THREAD

**Issue by MuhhalimR** [munafio/chatify#219]
I make a custom view chatify with laravel voyager, when use in local there's no error like when i already use with live server like Cpanel

This is the pict of what error i found
![chat error 5](https://user-images.githubusercontent.com/61299752/193786748-afa1a83b-9cc7-4a6f-a510-8e2f7530fb53.PNG)

i don't know what's wrong with my code

**Comment by munafio** [comment]
@MuhhalimR make sure of the imports (pusher, css stylings...etc).

**Comment by MuhhalimR** [comment]
> @MuhhalimR make sure of the imports (pusher, css stylings...etc).

i already imports (pusher.etc). i get this error when live deploy but in local is works

**Comment by munafio** [comment]
@MuhhalimR Probably you are missing something you did locally, I can't tell so you have to provide us more details about your issue and the customizations you did to help you.

**Comment by MuhhalimR** [comment]
```
@extends('voyager::master')

@section('page_title', 'Chat')

@section('content')
<div class="page-content read container-fluid">
    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-bordered" style="height: 90vh;">
                <iframe src="{{ url('chatify') }}" frameborder="0" style="overflow:hidden;overflow-x:hidden;overflow-y:hidden;height:100%;width:100%;position:absolute;top:0px;left:0px;right:0px;bottom:0px" height="100%" width="100%"></iframe>
            </div>
        </div>
    </div>
</div>
@stop

```

this is the customizations i did. chat.blade.php

**Comment by MuhhalimR** [comment]
![image](https://user-images.githubusercontent.com/61299752/195247602-391cd647-b90b-4b20-8de4-1f5ffe042634.png)
this is the last error that i get.
but i don't know why there's no style in chat

```
<!DOCTYPE html>
<title>{{ config('chatify.name') }}</title>

{{-- Meta tags --}}
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="id" content="{{ $id }}">
<meta name="type" content="{{ $type }}">
<meta name="messenger-color" content="{{ $messengerColor }}">
<meta name="csrf-token" content="{{ csrf_token() }}">
<meta name="url" content="{{ url('').'/'.config('chatify.routes.prefix') }}" data-user="{{ Auth::user()->id }}">

{{-- scripts --}}
<script
   href="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script type="text/js" href="{{ asset('js/chatify/font.awesome.min.js') }}"></script>
<script  type="text/js" href="{{ asset('js/chatify/autosize.js') }}"></script>
<script  type="text/js" href="{{ asset('js/app.js') }}"></script>
<script  type="text/js" src='https://unpkg.com/nprogress@0.2.0/nprogress.js'></script>

{{-- styles --}}
<link type="text/css"  rel="stylesheet" src='https://unpkg.com/nprogress@0.2.0/nprogress.css'/>
<link  type="text/css" href="{{ asset('css/chatify/style.css') }}" />
<link  type="text/css" href="{{ asset('css/chatify/'.$dark_mode.'.mode.css') }}"  />
<link  type="text/css" href="{{ asset('css/app.css') }}"  />

{{-- Messenger Color Style--}}
@include('Chatify::layouts.messengerColor')
```
this is my headlink.blade.php code

**Comment by munafio** [comment]
@MuhhalimR have you make a symlink for the storage? `php artisan storage:link`

**Comment by MuhhalimR** [comment]
> 

i already solve this, ty for your reply

**Comment by munafio** [comment]
@MuhhalimR If you solved this in your way, then please mention the solution for other developers who may face the same issue in the future. Thank you.

**Comment by munafio** [comment]
@MuhhalimR  If you solved this in your way, then please mention the solution for other developers who may face the same issue in the future. Thank you.
