### ISSUE TITLE
Numeric Value Out Of Range and Abnormal Contact List Display

### ISSUE THREAD

**Issue by FarizRafiqi** [munafio/chatify#223]
Laravel: v9.35.1
PHP: v8.1.10
Chatify: v1.5.2

When I start chatting on my hosted website, the message is not sent because the range is out of bound. Even though in the ch_messages table there are only a few messages, maybe this arises because of the limited big int range, randomly generating message ids, and the limitations of the web hosting I use. Maybe in the future the id column can be replaced with uuid or something so that this doesn't happen again.

![image](https://user-images.githubusercontent.com/45725951/199700805-769b1921-4402-4042-ad36-f5b31d8d8409.png)

And also when I send a message quickly I get a contact list display that is not normal like this, maybe in the future it can be fixed.

![image](https://user-images.githubusercontent.com/45725951/199701748-e27d0e71-2df7-468d-82d1-1f610c4f2166.png)

**Comment by munafio** [comment]
@FarizRafiqi Hi Fariz,
Thank you for informing me about this issue, it will be replaced with UUIDs in the next releases .. currently, you can make it on your own (Chatify is fully customizable).

Regards
