### ISSUE TITLE
Denormalized User Table

### ISSUE THREAD

**Issue by ronlinet** [munafio/chatify#225]
I saw the demo => Nice work! 

The only issue I see is the denormalized user table . 

It would make much more sense storing the user preferences in a package dedicated preferences table.

I know that a lot of other packages denormalize users tables but compartmentalization is the bread and butter of modular architecture and package development does have a lot to do with modularity.  There are nearly 240,000 packages available on Packagist imagine each of them would add few columns to user table?

Here is the  ER diagram as well as the create table code. 
Feel free to reuse. 

```
CREATE TABLE IF NOT EXISTS  user_has_chatify_preference` (
  `id`  NOT NULL,
  `users_id` INT(10) UNSIGNED NOT NULL,
  `preference_name` VARCHAR(150) NULL,
  `preference_value` MEDIUMTEXT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_user_has_chatify_preference_users_idx` (`users_id` ASC),
  CONSTRAINT `fk_user_has_chatify_preference_users`
    FOREIGN KEY (`users_id`)
    REFERENCES `users` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
```
![image](https://user-images.githubusercontent.com/2538315/202542701-d908f469-e7a1-4011-8826-354ef4b1fa19.png)

**Comment by sabrydawood** [comment]
This an only demo you can customize as you need 
An customized all database tables to be work with my website ✨

**Comment by munafio** [comment]
@ronlinet I will put this suggestion in my considerations, and I agree this is a better way of doing that but I wanted it first to be as simple as I can .. also, everything can be customized with Chatify so you can modify migrations, controllers...etc to meet your needs.
Thank you for your suggestion ❤️

**Comment by ronlinet** [comment]
@munafio  Please consider my post as a contribution, or as a constructive critic. 
I am not trying to discredit what you have done guys, personally I think that you have done an excellent job.  
Including into your project a bit of backend design will only make it better.  
Have a nice day !
