### ISSUE TITLE
Show previous chatlist without searching for the user

### ISSUE THREAD

**Issue by Alecckie** [munafio/chatify#226]
My chatify installation is okay and fine.
Only problem is that I have to search a previously contacted user to load their messages.

How can I show the previous chats on the left panel by default upon loading the chatify like other messenger apps?
Laravel version: 9.18 with vite

![Screenshot 2022-11-28 052508](https://user-images.githubusercontent.com/10174852/204179016-8233b0e2-a1f3-42f2-bb4f-c55d1aa4c4ab.jpg)
![Screenshot 2022-11-28 052347](https://user-images.githubusercontent.com/10174852/204179018-0223ceaa-2c1a-43dc-adb2-2cf0722b777f.jpg)

**Comment by munafio** [comment]
@Alecckie hey, It is already by default showing you people you have contacted each other.. there must be a problem with yours, check the network tab or any console logs .. if there are no issues there, then check [this issue.](https://github.com/munafio/chatify/issues/205#issuecomment-1219399270)

if not any of these, provide us with the details.

**Comment by Alecckie** [comment]
> @Alecckie hey, It is already by default showing you people you have contacted each other.. there must be a problem with yours, check the network tab or any console logs .. if there are no issues there, then check [this issue.](https://github.com/munafio/chatify/issues/205#issuecomment-1219399270)
> 
> if not any of these, provide us with the details.

Thank you sir,
Having followed the link to the issue, I have found the problem to be the strict mode on mysql.
It works fine now.

**Comment by AnkitTranktechies** [comment]
my error is this when i click on user name it will show chatify/idInfo 500 (Internal Server Error)  in my console and not open chat
