### ISSUE TITLE
chatify Error when change color or change photo

### ISSUE THREAD

**Issue by mohammadbassam55** [munafio/chatify#230]
Hello
1st proplem user-avatar not found , i've instaled php artisan storage:link
2 when i change color to dark mood , or any colors its loading without change any thing.
3 also when change the photo its loading without change any thing
help please.
![444444444444](https://user-images.githubusercontent.com/121625814/209971970-af31061e-5973-48bc-ae3b-4e428406081e.JPG)

**Comment by munafio** [comment]
@mohammadbassam55 open network tab using dev tools then check what's going on..

**Comment by mohammadbassam55** [comment]
@munafio 
![image](https://user-images.githubusercontent.com/121625814/210126190-bba871ee-2468-404d-88cb-af1b4639ef0d.png)

**Comment by mohammadbassam55** [comment]
![image](https://user-images.githubusercontent.com/121625814/210126277-f5e0c62a-b456-4473-8b59-0d632056ddc4.png)
![image](https://user-images.githubusercontent.com/121625814/210126289-06ad558f-ad7d-4349-8813-e9fcdd08d703.png)

**Comment by munafio** [comment]
@mohammadbassam55 please when you open the network tab, click on the request that causing the error to see its response!

**Comment by mohammadbassam55** [comment]
![image](https://user-images.githubusercontent.com/121625814/210172236-f19f19a7-31ad-4122-9800-0c03c411a038.png)
![image](https://user-images.githubusercontent.com/121625814/210172254-e9b868e6-3c5f-4779-9ed2-6d9b3c2371bb.png)
![image](https://user-images.githubusercontent.com/121625814/210172274-9408787a-5072-4127-8e74-b20acc84977a.png)
![image](https://user-images.githubusercontent.com/121625814/210172336-becbf4fc-ad0e-4f30-9a46-83f8fae29106.png)

**Comment by mohammadbassam55** [comment]
@munafio done this what you want?

**Comment by munafio** [comment]
@mohammadbassam55 in the response of this request says that `dark_mode` column in `users` table not found! I think that because you did not follow the installation steps very well .. you missing migration as I can see or you have different users table. 

Please follow the installation steps very well, and don't forget to migrate.
https://chatify.munafio.com/installation

**Comment by mohammadbassam55** [comment]
![image](https://user-images.githubusercontent.com/121625814/210174479-c8956eb4-56fb-4733-9c33-92da96e2837b.png)
@munafio  i've migrate all the migrations , its was working first day then i dont know whats wrong with that!
i dont change any data in the migrations

**Comment by munafio** [comment]
@mohammadbassam55 If it did work first day then you did something wrong letting this happen .. try to figure it out, check your database, re-install Chatify or republish migrations...etc
