### ISSUE TITLE
Support for PHP 7.4

### ISSUE THREAD

**Issue by sahilxjain** [munafio/chatify#24]
Getting this issue on PHP 7.4 due to pusher/pusher-php-server ^3.4@dev

Problem 1
    - Installation request for pusher/pusher-php-server v3.4.1 -> satisfiable by pusher/pusher-php-server[v3.4.1].
    - pusher/pusher-php-server v3.4.1 requires php >=5.4 <7.4 -> your PHP version (7.4.3) does not satisfy that requirement.
  Problem 2
    - pusher/pusher-php-server v3.4.1 requires php >=5.4 <7.4 -> your PHP version (7.4.3) does not satisfy that requirement.
    - munafio/chatify v1.0.0 requires pusher/pusher-php-server ^3.4@dev -> satisfiable by pusher/pusher-php-server[v3.4.1].
    - Installation request for munafio/chatify v1.0.0 -> satisfiable by munafio/chatify[v1.0.0].

**Comment by munafio** [comment]
It will be supported in the next release.

**Comment by HDVinnie** [comment]
Why are you closing this? It should NOT be closed until resolved.

**Comment by ayman-elmalah** [comment]
Please dont close this issue, it's important for users, you can support it for this release
