### ISSUE TITLE
\Chatify\MessagesController::index does not exist.

### ISSUE THREAD

**Issue by musadiq003** [munafio/chatify#242]
when publish the controller then (Method App\Http\Controllers\vendor\Chatify\MessagesController::index does not exist.)

**Comment by munafio** [comment]
@musadiq003 if you have removed this method from the controller of course it will throw this error. This method responsible showing up the app view of Chatify. Check out the repository and its code for more info.

**Comment by musadiq003** [comment]
I did not remove anything in controller i just publish the controllers from
chatify to app..

**Comment by jayomayan** [comment]
i got the same error. How was this resolved?

**Comment by jayomayan** [comment]
Got it.. the MessagesController.php in API does not have this.

  public function index( $id = null)
    {
        $messenger_color = Auth::user()->messenger_color;
        return view('Chatify::pages.app', [
            'id' => $id ?? 0,
            'messengerColor' => $messenger_color ? $messenger_color : Chatify::getFallbackColor(),
            'dark_mode' => Auth::user()->dark_mode < 1 ? 'light' : 'dark',
        ]);
    }
