### ISSUE TITLE
Dont use mt_rand(9, 99999999) for ids

### ISSUE THREAD

**Issue by Pfannkuchensack** [munafio/chatify#243]
Dont use something random for a id in a database.
better use uuids for this. (Or dont set a random number as id then it is good too)
https://www.educative.io/answers/how-to-use-uuids-in-laravel

Files with the random number:
https://github.com/munafio/chatify/blob/f5197f8e89d7d1315515d80ac2a867b5e88fabf0/src/Http/Controllers/MessagesController.php#L150
https://github.com/munafio/chatify/blob/b2c48e969501877fa4eb51b27f438fc9a1e38404/src/Http/Controllers/Api/MessagesController.php#L132
https://github.com/munafio/chatify/blob/f5197f8e89d7d1315515d80ac2a867b5e88fabf0/src/ChatifyMessenger.php#L308

**Comment by Pfannkuchensack** [comment]
Good Work

**Comment by munafio** [comment]
@Pfannkuchensack A new version now released v1.6, with a fix to your issue.
