### ISSUE TITLE
error if make other migration

### ISSUE THREAD

**Issue by fadiljaelani** [munafio/chatify#245]
![image](https://user-images.githubusercontent.com/66046419/215647213-4ee80a38-5c13-41fd-923f-159b6e59d0dd.png)

can you help me?

**Comment by munafio** [comment]
@fadiljaelani make sure you don't have 2 migrations at the same time with the same name

**Comment by fadiljaelani** [comment]
![image](https://user-images.githubusercontent.com/66046419/215918035-9b0e1118-5d67-4dbc-8e83-3726cecc0cda.png)

this is mymigration.

if i run command "php artisan make:migration 'create course table'"

error 
"PHP Fatal error:  Cannot declare class CreateMessagesTable, because the name is already in use in D:\App\kbm\d
atabase\migrations\2023_01_19_999999_create_messages_table.php on line 7"

**Comment by munafio** [comment]
@fadiljaelani as I can see, you have 2 migration file with the name `create_messages_table` and their class name are the same so it throws this error .. to solve this issue, you can change the class name in one of the two files and will be solved.
