### ISSUE TITLE
Eloquent MissingAttributeException

### ISSUE THREAD

**Issue by satis-apex** [munafio/chatify#248]
is there a way to publish the ChatifyMessenger facade and customize it?

I have to manually change the vendor source of  ChatifyMessenger in the pusherAuth method which is not a good coding habit.
$authData = json_encode([
      'user_id' => $authUser->id,
      'user_info' => [
          'name' => $authUser->name // user model doesnot have name attribute 
      ]
]);

**Comment by munafio** [comment]
@satis-apex of course you can, check out the official documentation https://chatify.munafio.com/customizations#custom-chatify-class
