### ISSUE TITLE
iOS message textarea does not slide up with iOS keyboard then hides messages

### ISSUE THREAD

**Issue by chandlerwilcox88** [munafio/chatify#249]
I recorded a video to show the issue. When coming into a new chat and clicking into the message textarea the keyboard slides over. Then after the first message is sent the textarea will now slide up but it's because the full page slides up and now hides the initial messages.

https://user-images.githubusercontent.com/7296169/216872355-b5e8864d-bb43-404c-b3b1-dd7077824c10.mp4

**Comment by munafio** [comment]
@chandlerwilcox88 Please update the package, this issue been solved few days ago with v1.5.6 #202

**Comment by m-popa** [comment]
Hello and thanks for the awesome package. 

The bug still persists on iOS (latest version)


![image](https://user-images.githubusercontent.com/23634938/223484904-155004a7-4600-4c78-9e9a-ed6fcd539369.png)

**Comment by IamNuru** [comment]
@m-popa please are you able to get around this issue with the latest iphone devices?

**Comment by JeffGepiga** [comment]
I tried commenting out this code in code.js

```
window.visualViewport.addEventListener("resize", (e) => {
  clearTimeout(resizeTimeout);
  resizeTimeout = setTimeout(function () {
    const h = e.target.height;
    if (h) {
      $(".messenger-messagingView").css({ height: h + "px" });
    }
  }, 100);
});
```

and now it works properly now in mobile devices.

**Comment by JoharOfficial1** [comment]
@munafio The issue is still there as I removed the code part mentioned by @JeffGepiga but when we click on textarea field it messages goes up and if screen becomes scrollable. So, when we scroll it shows gray area below textarea field. Video is below

https://github.com/user-attachments/assets/edb74566-50d9-4a0f-a898-154c7e586ae0
