### ISSUE TITLE
Pusher Alternative? 

### ISSUE THREAD

**Issue by HDVinnie** [munafio/chatify#25]
Will Socket.io or Laravel WebSockets be an option?

**Comment by munafio** [comment]
Now (v1.0), No!!
Later, Maybe! .. I'll keep it in mind in the next releases

**Comment by munafio** [comment]
@HDVinnie Now it is supported and you can use it with any other WS server, check out the [documentation](https://chatify.munafio.com/custom-websocket-server) .
