### ISSUE TITLE
ErrorException when use api Trying to get property 'id' of non-object i

### ISSUE THREAD

**Issue by salah11172** [munafio/chatify#251]
ErrorException: Trying to get property 'id' of non-object in file 
vendor/munafio/chatify/src/Http/Controllers/Api/MessagesController.php on line 216

**Comment by munafio** [comment]
@salah11172 your issue in [this](https://github.com/munafio/chatify/blob/f20fa3fedd4067a36adb0a0fd225d72e61aa9e91/src/Http/Controllers/Api/MessagesController.php#L213) `where` clause , getting the id from the auth user .. check your auth.

**Comment by salah11172** [comment]
Is there any source to explain dealing with api

**Comment by munafio** [comment]
@munafio if you mean with Chatify APIs, no need for that because it's as any Laravel API and for that there are many sources out there.

**Comment by munafio** [comment]
@salah11172  if you mean with Chatify APIs, no need for that because it's as any Laravel API and for that there are many sources out there.

**Comment by abdulqadeer1999** [comment]
hi there iam unable to get logged in user through post man when i send message everything is correct i also pass auth token in post man still iam not getting logged in user

**Comment by abdulqadeer1999** [comment]
@salah11172  Use sanctum auth in your chatify api routes 
Route::middleware(['auth:sanctum'])->group(function(){

)};
it worked for me
