### ISSUE TITLE
in chatifyMessenger.php files you use self::  and when want create CustomChatify Class extend this files 

### ISSUE THREAD

**Issue by YounesMokhtari** [munafio/chatify#256]
i get very errors

![image](https://user-images.githubusercontent.com/100948437/222136712-20b05b8d-4ea5-438c-859b-9a23e92c1e93.png)

how can overwite this?

how extends your files??

when overwire any function beacause you use self:: keyword chatify get any error for example see it

![image](https://user-images.githubusercontent.com/100948437/222137495-b5554e64-00c1-4687-beac-91f0f46bf2d2.png)

and you can see my custom files

![Screenshot from 2023-03-01 15-51-09](https://user-images.githubusercontent.com/100948437/222146173-1b5113dd-0222-4243-9931-55981f4dcf2c.png)

**Comment by munafio** [comment]
@YounesMokhtari instead of `self` use `parent` when extending ChatifyMessenger as your parent.

**Comment by YounesMokhtari** [comment]
When  extended parant and overwrite any method i got error
You can see error above.

**Comment by munafio** [comment]
@YounesMokhtari You have to check `network` tab in your browser to see the actual  error message, can't know with this console logs.

**Comment by YounesMokhtari** [comment]
How can customize geturlavatar() method??

**Comment by munafio** [comment]
> How can customize geturlavatar() method??

By extending the main class, and you already doing that just you have to know the errors occurring .. in your browser inspect > network tab > click failed request > select response tab
and you'll see error messages there
