### ISSUE TITLE
Can we use laravel-websockets instead of pusher?

### ISSUE THREAD

**Issue by lovecoding-git** [munafio/chatify#26]
Hi Thank you for such great package.
Can we use laravel-websockets instead of pusher?

**Comment by munafio** [comment]
For now, no!!
but later in the next release, may use it

**Comment by H4ck3r-x0** [comment]
Thanks for this amazing package, we really need this to work on laravel-websockets

**Comment by volserverRay** [comment]
hi @munafio is this supported now? I'm using v1.2.5, still can't figure out how to use laravel-websocket for now.

**Comment by munafio** [comment]
> hi @munafio is this supported now? I'm using v1.2.5, still can't figure out how to use laravel-websocket for now.

The new Chatify will support both pusher and Laravel websockets, at the same time, you can now implement it yourself to work with Laravel WebSockets.

**Comment by munafio** [comment]
@volserverRay @H4ck3r-x0 @lovecoding-git Now it is supported and you can use it with any other WS server, check out the [documentation](https://chatify.munafio.com/custom-websocket-server) .
