### ISSUE TITLE
issue with broadcasting 

### ISSUE THREAD

**Issue by AmarAwni** [munafio/chatify#263]
Hello, First of all, I would like to express my appreciation for providing such a wonderful chat system. I have successfully integrated it into my production project and am able to send messages to other users, which appear in the "all messages" section. but when I reload the page, all messages disappear from that section, indicating that other users are unable to view any messages in the "all messages" section. Additionally, I am curious to know whether push notifications are supposed to be sent when a user receives a message. I have already gone through all the necessary steps, including verifying the BROADCAST_DRIVER in the .env file and the pusher settings in the config/broadcasting.php file, and everything appears to be in order.

**Comment by munafio** [comment]
@AmarAwni Can you provide a demo for your issue? because it's not quite clear.
And about the notifications, the package handles only the sounds which should be only when user receive a message.
Lastly, This package does not use Laravel's native broadcasting, it uses Pusher SDK directly on the back/front end side.

Make sure to read the package source code to understand it well.

**Comment by Arooj097** [comment]
I integrated your Chat App with my project. I am stuck on this error and couldn't find any answer working .Cannot broadcast client event (connection not subscribed to channel private-chatify.40).

**Comment by munafio** [comment]
> I integrated your Chat App with my project. I am stuck on this error and couldn't find any answer working .Cannot broadcast client event (connection not subscribed to channel private-chatify.40). 

You didn't enable client events on pusher site dashboard. Please follow the official documentation

**Comment by munafio** [comment]
Closed due to inactivity and lack of information
