### ISSUE TITLE
Custom assets path?

### ISSUE THREAD

**Issue by gtu-myowin** [munafio/chatify#264]
I can see that assets are being published and load public folder (i.e; `/js/app.js` and `/css/app.css`) but I have configured to load them via `/assets/js/app.js` and `/assets/css/app.css`. How can I tell Chatify to load those assets from my desired location? Thank you!

**Comment by munafio** [comment]
@gtu-myowin Currently you can not do that, but I'll keep it in mind to add this ability in the configurations file in the next releases.
Thank you

**Comment by gtu-myowin** [comment]
Thank you for your support.
