### ISSUE TITLE
Am having difficulty installing chatify to my website currently.

### ISSUE THREAD

**Issue by edwinlongjohn** [munafio/chatify#270]
below is the response am getting.  

Failed to download munafio/chatify from dist: curl error 28 while downloading https://api.github.com/repos/munafio/chatify/zipball/7ae634e13bbf543f06b80a8d9d941e6101a830a4: Connection timed out after 10011 milliseconds
    Now trying to download from source
  - Syncing munafio/chatify (v1.6.1) into cache
Cloning failed using an ssh key for authentication, enter your GitHub credentials to access private repos
When working with _public_ GitHub repositories only, head to https://github.com/settings/tokens/new?scopes=&description=Composer+on+DESKTOP-SBK9AQQ+2023-03-30+0510 to retrieve a token.
This token will have read-only permission for public information only.
When you need to access _private_ GitHub repositories as well, go to https://github.com/settings/tokens/new?scopes=repo&description=Composer+on+DESKTOP-SBK9AQQ+2023-03-30+0510
Note that such tokens have broad read/write permissions on your behalf, even if not needed by Composer.
Tokens will be stored in plain text in "C:/Users/Exquisite Star/AppData/Roaming/Composer/auth.json" for future use by Composer.
For additional information, check https://getcomposer.org/doc/articles/authentication-for-private-packages.md#github-oauth
Token (hidden):

**Comment by munafio** [comment]
@edwinlongjohn its issue with your credentials as I can see, try to fix it first then try again.

**Comment by munafio** [comment]
@edwinlongjohn This could be due to various reasons such as slow internet connectivity, server issues, or network problems.
