### ISSUE TITLE
ServeCommand.php Undefined array key 1

### ISSUE THREAD

**Issue by vishal-sohani** [munafio/chatify#277]
Undefined array key 1

  at vendor\laravel\framework\src\Illuminate\Foundation\Console\ServeCommand.php:303
    299▕         $regex = env('PHP_CLI_SERVER_WORKERS', 1) > 1 ? '/^\[\d+]\s\[([a-zA-Z0-9: ]+)\]/' : '/^\[([^\]]+)\]/';
    300▕ 
    301▕         preg_match($regex, $line, $matches);
    302▕ 
  ➜ 303▕         return Carbon::createFromFormat('D M d H:i:s Y', $matches[1]);
    304▕     }
    305▕ 
    306▕     /**
    307▕      * Get the request port from the given PHP server output.

  1   vendor\laravel\framework\src\Illuminate\Foundation\Console\ServeCommand.php:303
      Illuminate\Foundation\Bootstrap\HandleExceptions::Illuminate\Foundation\Bootstrap\{closure}("Undefined array key 1", "C:\Users\CG-Vishal\Desktop\vishal main script\chatapp\chatify-demo\vendor\laravel\framework\src\Illuminate\Foundation\Console\ServeCommand.php")

  2   vendor\laravel\framework\src\Illuminate\Foundation\Console\ServeCommand.php:248
      Illuminate\Foundation\Console\ServeCommand::getDateFromLine("ay  5 12:39:40 2023] 127.0.0.1:61011 Accepted")

**Comment by munafio** [comment]
@vishal-sohani This is not related to Chatify!, please when open an issue make sure its related to this package and provide more details not only the error to reproduce the issue
