### ISSUE TITLE
work with flutter ?

### ISSUE THREAD

**Issue by salah11172** [munafio/chatify#278]
any one can work with this package with flutter ?

**Comment by jocypher** [comment]
I'm sorry, but I'm not sure which package you are referring to. Could you please provide me with more context or clarify your request?

**Comment by munafio** [comment]
@salah11172 There are APIs that can be integrated anywhere, you can find the apis at the official documentation .. also you have to make your client same as what is done with the js client of Chatify such as connections ...etc

**Comment by salah11172** [comment]
![WhatsApp Image 2023-05-12 at 17 08 25](https://github.com/munafio/chatify/assets/77698583/542f6028-1e0b-49da-b8a4-cfc68aec43a7)
  
  I need hostEndPoint and  hostAuthEndPoint

**Comment by salah11172** [comment]
> @salah11172 There are APIs that can be integrated anywhere, you can find the apis at the official documentation .. also you have to make your client same as what is done with the js client of Chatify such as connections ...etc

im read documentation well 
the only part mention in api part is collection link

**Comment by munafio** [comment]
@salah11172 yes, thats all you need .. otherwise, follow the client code implementation.
and about `hostEndPoint` is where your host is, and `hostAuthEndPoint` is the [endpoint](https://github.com/munafio/chatify/blob/7ae634e13bbf543f06b80a8d9d941e6101a830a4/src/routes/api.php#L8) to the Pusher's auth.

**Comment by salah11172** [comment]
hostAuthEndPoint require  channel_name and socket_id 
chennel_name is ok 
socket_id how can find it ?
![Screenshot from 2023-05-13 12-10-51](https://github.com/munafio/chatify/assets/77698583/94531a58-98c1-42b0-b247-4fd0935f3e88)

**Comment by munafio** [comment]
> hostAuthEndPoint require channel_name and socket_id chennel_name is ok socket_id how can find it ? ![Screenshot from 2023-05-13 12-10-51](https://user-images.githubusercontent.com/77698583/238125704-94531a58-98c1-42b0-b247-4fd0935f3e88.png)

This is handled by pusher sdk, you only give it the endpoint so it can handle the auth
