### ISSUE TITLE
Notifications in the header

### ISSUE THREAD

**Issue by zeus6999** [munafio/chatify#28]
@munafio  are you going to add notifications in the header to alert users that are unread messages?

in this way it seems to me that it is a complete chat

http://prntscr.com/u0sys1

Thank you

**Comment by munafio** [comment]
maybe it will be included in the next releases .. but for now, you can implement it yourself easily when receiving messages from a specific user..
Thanks for your suggestion.

**Comment by Manoah1988** [comment]
any solution for notification in header for other page on laravel app?
Thank you
