### ISSUE TITLE
An issue regarding the display of users

### ISSUE THREAD

**Issue by us2ahmad** [munafio/chatify#281]
After adding the chat package to my project, I cannot see the existing users so that I can message them, and the user data for the person who opened the chat is not appearing. Can you please help me solve this problem?

**Comment by solomiles** [comment]
Hi @us2ahmad are you using the default user model for your authenticated users?

**Comment by NEVELYNE** [comment]
Hello @solomiles , I have the same issue. When I click on a user, the user data doesn't load I instead get the "Your contact list is empty" message

**Comment by us2ahmad** [comment]
thanks for your care @solomiles  
No, some modifications have been made to it, such as deleting the name, adding a first name and a second name, and some other modifications
Also, the groups interface does not appear for me

**Comment by solomiles** [comment]
@us2ahmad if you're not using laravel's defualt User model, i think you should open up the controllers from the vendor folder and customise the Methods that are not working

**Comment by solomiles** [comment]
![chatify scrren](https://github.com/munafio/chatify/assets/23401399/3b554819-5bb9-4514-b1ce-6d1cb2476584)
@NEVELYNE chatify is using the Users model, you can override that by using your own custom model.. you should also customise the migrations to add columns to your own tables.

**Comment by NEVELYNE** [comment]
@solomiles , Good Morning, 
Thanks for the response, I still have the same issue. I can now only message myself. Other users don't show unless I search for them. When they appear, I still can't click on them to start messaging them.

**Comment by solomiles** [comment]
Hi, @NEVELYNE , here is my email osaighesolomon@gmail.com ..you can schedule a google meeting so we can debug the package together. thanks

**Comment by NEVELYNE** [comment]
I have sent you an email dear.
Thanks dear

**Comment by gurtner-it** [comment]
Well, what was the solution? I have the same issue!
