### ISSUE TITLE
Change routes prefix with subdomain

### ISSUE THREAD

**Issue by samuelsurbakti** [munafio/chatify#283]
Can I use this package with subdomain?
I mean, instead use prefix like "yourdomain.com/chat", I want tou use like "chat.yourdomain.com"?
Anyway, this package so cool

**Comment by munafio** [comment]
@samuelsurbakti yes you can from the configurations of the routes 
https://github.com/munafio/chatify/blob/7ae634e13bbf543f06b80a8d9d941e6101a830a4/src/config/chatify.php#L24
