### ISSUE TITLE
Total number of unseen messages

### ISSUE THREAD

**Issue by foxit07** [munafio/chatify#284]
```php
    /**
     * Count Unseen messages
     *
     * @param int $user_id
     * @return Collection
     */
    public function countUnseenMessages($user_id)
    {
        return Message::where('from_id', $user_id)->where('to_id', Auth::user()->id)->where('seen', 0)->count();
    }
```

This method shows the number of invisible messages from a particular user.

Do I understand correctly that there are no total unseen messages yet?

**Comment by munafio** [comment]
@munafio That's correct, it counts the number of unseen messages for a particular user not for the whole contact list of yours.
