### ISSUE TITLE
"message": "Attempt to read property \"id\" on null",

### ISSUE THREAD

**Issue by Kokil** [munafio/chatify#286]
I am using 1.4 and using laravel passport.
this is my config for api
![image](https://github.com/munafio/chatify/assets/481786/a6381bf6-a2eb-4e72-bb4b-ca39f620b046)

Authorization header
![image](https://github.com/munafio/chatify/assets/481786/1219f725-a90d-4a67-bfe4-bc9a5ecd1b44)

i get :
{
    "message": "Unauthenticated."
}

i any thing i did wrong

**Comment by munafio** [comment]
@Kokil this error happens with your application auth not on Chatify side, when your are not authenticated then it will throw this error, so you have to check your auth.
