### ISSUE TITLE
Pusher's messages quantity increasing a lot 

### ISSUE THREAD

**Issue by Kashorako** [munafio/chatify#287]
Hello friend, first of all thank you for your package, it's great!

I just started using your package a few days ago, but there is something weird happening.

The main problem is, when i send a single message, the Pusher's "messages sent quantity" increases A LOT!

For example i sent the next message "Hi friend" and the quantity went from 208 to 240, i'd like to understand what's happening, i did not do any change to your package (yet) but that problem is really weird.

The amount increased for message is not always the same, also, when i'm idle in the chat route (for example https://laravelproject/chatify) the amount increases as well but not that much.

I'm guessing the problem is related to your listeners which show the typing status or the new message received or something like that, can you help me please?

Thank you so much for your help and time!

- Yosue

**Comment by munafio** [comment]
@Kashorako That's correct, because we have many listeners including client events are counting .. that's why.
