### ISSUE TITLE
error app.js and pusher on new install

### ISSUE THREAD

**Issue by nachete1987** [munafio/chatify#288]
Hello,

On new install I'm getting errors to load resource: the server responded with a status of 404 (Not Found) on app.js that is located on headlinks.blade.php 
and caught ReferenceError: pusher is not defined on code.js. in the line var channel = pusher.subscribe(`${channelName}.${auth_id}`);

What could be happening?
Thanks a lot

**Comment by nachete1987** [comment]
I have resolve the error, It was a problem with N+1 spatie package but now I'm getting this error:
"production.ERROR: Call to undefined method Chatify\ChatifyMessenger::fetchMessage()"

**Comment by munafio** [comment]
@nachete1987 you probably  making changes to the controller namespace .. make sure all config are correct and follow the official docs.

**Comment by nachete1987** [comment]
I think it's a problem with upgrade instructions from a previous version.
Some classes are not overwritten and it causes the problem
