### ISSUE TITLE
Realtime Update Issue

### ISSUE THREAD

**Issue by Emad-2002** [munafio/chatify#294]
The problem I am facing is, Say I am Roger and I send a message to my friend Gold saying 'hi'. After pressing send, it shows the clock icon on the message and unless I refresh the page, the icon does not change to sent. The same for receiver's end too, unless the page is refreshed Gold cannot see the latest message either. Basically, the send message and all components are working fine, but I believe there is some sort of problem with the pusher which is not showing the messages in real time.

**Comment by rashadkhan359** [comment]
Share your browser console messages as well as the pusher debug console. Your events might be getting fired but now getting listened.

**Comment by Emad-2002** [comment]
![image](https://github.com/munafio/chatify/assets/108452008/8d13166c-ae93-4f55-abfd-63a8dd78a77c)

**Comment by Emad-2002** [comment]
> Share your browser console messages as well as the pusher debug console. Your events might be getting fired but now getting listened.

Yes I think that is the issue, but I am new to this which is why I am not sure exactly what went wrong.

**Comment by Emad-2002** [comment]
Wuhuuuu, I got to the solution, the issue was SSL certificate problem, which is a common problem if using localhost, to which I used the solution by following the link : https://www.scratchcode.io/curl-error-ssl-certificate-problem-unable-to-get-local-issuer-certificate/
