### ISSUE TITLE
After searching for a user, the conversation is not being created.

### ISSUE THREAD

**Issue by rashadkhan359** [munafio/chatify#295]
Whenever I search for a user and it shows their name, I'm unable to click on it and open a new chat. It just doesn't do anything except select a few texts on the chat list. There are no errors in the console, and no event is fired in the network tab. When I create a chat directly going to the database, that works absolutely fine.
Here is a video of the issue.
[https://ydray.com/get/t/16901302187346IaMAc03bd2c68217DX](url)

https://github.com/munafio/chatify/assets/20838779/442b1e0c-c219-4432-a532-0566bd93b4fa

**Comment by munafio** [comment]
@rashadkhan359 As I can see .. what you are doing is pressing down or holding the key of your mouse, this is not how it works .. you should only press the user then it will show up.
Tested on many users and never had this issue!

**Comment by yeonjih1** [comment]
same problem. how to fix this.?
