### ISSUE TITLE
Route [login] not defined.

### ISSUE THREAD

**Issue by JugalRupela** [munafio/chatify#30]
Hi,
I'm a newbie and a learner, I tried to follow the steps and install it in my local machine, everything installed smoothly but at the end of the installation when i try to access it keeps throwing this error:

"Symfony\Component\Routing\Exception\RouteNotFoundException
Route [login] not defined.
http://localhost/laravelprojects/chatApp/public/chatify"

I tried few times but i don't understand what am I doing wrong.

**Comment by munafio** [comment]
Please check your app url and make sure that all your credentials are correct .. or re-install it again but follow the steps carefully as mentioned..

**Comment by sinnbeck** [comment]
Did you remember to scaffold the auth stuff in laravel?

https://laravel.com/docs/7.x/authentication#authentication-quickstart

After that you should make sure that you have this in your web.php (routes folder)

```
Auth::routes();.

**Comment by munafio** [comment]
Thanks to @Sinnbeck to mention that .. I forgot to mention it because I thought you already scaffold the auth stuff in your Laravel application.

**Comment by munafio** [comment]
Thanks for you @Sinnbeck .
@JugalRupela , I thought you already scaffold the `auth` stuff in your Laravel application .. because a chat system like this won't work without authentication system!! right?

Follow the official documentation :
https://laravel.com/docs/7.x/authentication#authentication-quickstart

as @Sinnbeck mentioned above.

**Comment by JugalRupela** [comment]
@sinnbeck Thank you so much for the help, it worked.
@munafio my bad I didn't, still a newbie :)

Thank you so much for your help! U guys rock as always 👍

**Comment by ralphsunny22** [comment]
app.js:1 POST http://127.0.0.1:8000/chatify/idInfo 500 (Internal Server Error)
please help me resolve. Installation was perfect. this ajax request error

**Comment by sinnbeck** [comment]
@ralphsunny22 

1. This issue is closed
2. Your issue does not seem to be related
