### ISSUE TITLE
Still Image Is not showing in chat and if we are set the profile also it will not showing. I have also link the storage with public.

### ISSUE THREAD

**Issue by rutulsheladiya31** [munafio/chatify#305]
- You can see here when i am sending the image to other user it will not showing in the chat and.

![image](https://github.com/munafio/chatify/assets/125446691/77d3c9b2-3fe7-4689-9d32-5ffcf7efe824)

![image](https://github.com/munafio/chatify/assets/125446691/e08fda81-5678-4b73-bf6a-60209affd286)

- check here when i am setting the profile image it will also not showing 
![image](https://github.com/munafio/chatify/assets/125446691/13d78ce8-f703-49c4-9215-eea8249d7f09)

- see here From My account i have set the image but it will not showing
![image](https://github.com/munafio/chatify/assets/125446691/ac1d9e71-6ae2-47e0-a910-9e442e2ee19c)

**Comment by munafio** [comment]
@rutulsheladiya31 make sure of your `.env` file, you have to set the right APP_URL. If it is right, then check the elements using the `inspect` tool in your browser to check the url of the image to see whats wrong.

**Comment by rutulsheladiya31** [comment]
> @rutulsheladiya31 make sure of your `.env` file, you have to set the right APP_URL. If it is right, then check the elements using the `inspect` tool in your browser to check the url of the image to see whats wrong.

@munafio Sure I Will Check It. Thanks For Your Reply :)
