### ISSUE TITLE
The User class inside MessagesController breaks when you have a different location.

### ISSUE THREAD

**Issue by JeffGepiga** [munafio/chatify#308]
I have tried installing this package and encountered some issues because my User Class is in a different directory, and updating all the ```User::``` to ```Auth::user()``` would fix it inside MessagesController.php

I hope this will be considered.
Anyway, great package!
Thank you

**Comment by JeffGepiga** [comment]
added a PR https://github.com/munafio/chatify/pull/310 for this

**Comment by munafio** [comment]
@JeffGepiga  Basically, you can change the namespace to resolve this issue at MessagesController.php 
And you need to publish the controllers first, and this one explained in the docs.
