### ISSUE TITLE
Undefined $user variable

### ISSUE THREAD

**Issue by Zaaawn** [munafio/chatify#315]
I've tried everything to have user information with $user but I still have the same error. I would like some help about that. I dont how I can solve that issue.

**Comment by munafio** [comment]
@Zaaawn please provide more information to help.

**Comment by Zaaawn** [comment]
Here is the problem, I use Chatify to have a chat for my website but with a
vue info.blade.php which provide users informations but when I try to
implement with $user it says undefined variable. I'm wondering how can I
implemenent it because in the controller I dont find any function refering
to the info.blade.php nor a route in the web.php. So I would like to have
more informations about that. And how I can solve this issue

**Comment by munafio** [comment]
@Zaaawn Make sure you are passing the user variable to the blade file you are targeting or working on
