### ISSUE TITLE
How use chatify with mobile client?

### ISSUE THREAD

**Issue by FetFrumos** [munafio/chatify#316]
Hi @munafio, thank you for your work and your plugin.

I read your documentation and installed your plugin on my server. Now I have a question - how to use it with the client (mobile application)?
if Pusher is used as the server by default, then it is necessary to configure Pusher on the client as well? what address should i use for x on the client?
I did not find anything about this in the documentation. 
I would be grateful if you could explain this in more detail

**Comment by munafio** [comment]
@FetFrumos Thank you for your words, and about the implementation on other client apps, you only need to configure Pusher as they explained in their documentation and then use apis of Chatify to control data and send ...etc

It is the same way configured in 'code.js' client code of Chatify.
