### ISSUE TITLE
how to start a chat from another blade not in chatify routes blade

### ISSUE THREAD

**Issue by MdTanvirHasanAnik** [munafio/chatify#32]
Please tell me how to start a new chat by sender and reciveer id only from outside of catify routes blade

**Comment by munafio** [comment]
Can you please explain your issue ?

**Comment by MdTanvirHasanAnik** [comment]
Ok directly inserted to the database and solve it. Please brother can you complete the group chat soon, if it is possible when will get the update? You have done a great work indeed.

**Comment by munafio** [comment]
As soon as I can it will be there with Chatify v2
