### ISSUE TITLE
How to custom images design in chats?

### ISSUE THREAD

**Issue by httptools** [munafio/chatify#321]
Hello, this package is best package for chat applications. I love this and thanks for build this package.

How to custom images design in chats? Where style path?

**Comment by mduzair025** [comment]
You can find it at your project public directly. public_path()//css/chatify/ you will find the style files
<img width="315" alt="image" src="https://github.com/munafio/chatify/assets/47058770/13eeccd0-108c-492b-8e09-afd5d78c69ad">
