### ISSUE TITLE
The issue of channel-authorization, on console

### ISSUE THREAD

**Issue by mduzair025** [munafio/chatify#323]
<img width="1361" alt="image" src="https://github.com/munafio/chatify/assets/47058770/28216a5b-7bd0-427a-906b-5136a2aa9225">

That restricts me to fired even though I have tried so many times even if I have to change the structure. but it is working fine at Chatify-demo but working on my project can someone help me with this? @munafio @stoneshaq

**Comment by munafio** [comment]
@mduzair025 disable debugbar if you have it enabled, or just except `/chatify` route from debugbar config
