### ISSUE TITLE
How to filter the user records returned in search from the controller?

### ISSUE THREAD

**Issue by sabira-khan** [munafio/chatify#324]
I have a User model with different organization_ids. I want to limit the search results to display users within the same organization. 
I tried editing the following files, but it doesn't seem to have any effect, it still returns all users. Even if I add dd(); the search still works although this is written as the route, so I'm wondering, am I on the correct place to modify this behavior? 
Please let me know. Thanks.
![Screenshot (1013)](https://github.com/munafio/chatify/assets/113014892/eebdd7dc-d8af-4c06-97db-f3417182eec4)
![Screenshot (1012)](https://github.com/munafio/chatify/assets/113014892/c28cd7bf-1046-4033-9f5a-84cee8fbfeb8)

**Comment by munafio** [comment]
@sabira-khan modify the search method in the controller and the js code to meet your needs
