### ISSUE TITLE
Failed to load resource: the server responded with a status of 500 (Internal Server Error) Chatify

### ISSUE THREAD

**Issue by Rkhmadmaulana** [munafio/chatify#325]
I experienced problems using chatify, when I wanted to start a chat it couldn't
![Screenshot (178)](https://github.com/munafio/chatify/assets/111129854/b358a85c-ff9e-46db-af57-f3c301315af6)
Plis help me

**Comment by munafio** [comment]
@Rkhmadmaulana check out network tab and its failing requests to see what is the error happens

**Comment by munafio** [comment]
issue been closed due to inactivity
