### ISSUE TITLE
Update doc with Ably Configuration

### ISSUE THREAD

**Issue by sacOO7** [munafio/chatify#328]
Thanks for the wonderful chat sdk library!
I was wondering if you can add support for [ably-broadcaster](https://github.com/ably/laravel-broadcaster).
[Ably-broadcaster](https://github.com/ably/laravel-broadcaster) is officially recognized by laravel https://laravel.com/docs/10.x/broadcasting#ably and provides [advanced features](https://github.com/ably/laravel-broadcaster?tab=readme-ov-file#features) on top of existing pusher features.
There's also a plan to add more unique features as per https://github.com/ably/laravel-broadcaster/issues/37.

**Comment by sacOO7** [comment]
hi @munafio, any updates on above

**Comment by munafio** [comment]
@sacOO7 Hey 👋🏻,
I have not check it till now, but you can follow same instructions mentioned in the official docs of Chatify about custom WS .. it might help.. and I will look into it if needed later.

**Comment by sacOO7** [comment]
Sure, that would be helpful.
It would have been great if official docs had a repository where I can raise a PR to update config. for the same.
This would be helpful for a lot other people.

**Comment by sacOO7** [comment]
Hi @munafio is there any way to create a PR to modify website docs to include support for ably?

**Comment by munafio** [comment]
@sacOO7 Unfortunately, there is no repo for the docs, it is hosted on GitBook directly, but you can contribute using our discord server.
