### ISSUE TITLE
 500 (Internal Server Error)

### ISSUE THREAD

**Issue by iislamtaleb** [munafio/chatify#329]
When I'm sending messages, I encounter the following error in my browser console: POST http://localhost:8000/messages/sendMessage 500 (Internal Server Error). The PHP certificate is set properly, and yet, I still receive this error

![Capture d'écran 2023-12-25 143716](https://github.com/munafio/chatify/assets/148808316/40f17598-8df8-4d53-8fa3-fa371f39be5e)
![Capture d'écran 2023-12-25 143733](https://github.com/munafio/chatify/assets/148808316/2791d467-7f5f-4fb6-95f5-d5ce7b265a37)
![Capture d'écran 2023-12-25 143758](https://github.com/munafio/chatify/assets/148808316/f619d188-c063-4a7c-b335-23f3b5814759)

**Comment by iislamtaleb** [comment]
I have downloaded the wrong cert version! it's working now, thanks for the package :)

**Comment by iislamtaleb** [comment]
I have downloaded the wrong cert version! it's working now, thanks for the package :)

**Comment by hussain4real** [comment]
@iislamtaleb facing same issue, i'm using laravel valet

**Comment by 10ANT** [comment]
> I have downloaded the wrong cert version! it's working now, thanks for the package :)

what cert did you download?
