### ISSUE TITLE
Laravel 8 version

### ISSUE THREAD

**Issue by Haronur** [munafio/chatify#33]
I have integrated this package in laravel 8. But after following this instruction I had to do extra two things is below:
1) copy CSS & js folder from ```vendor\munafio\chatify\assets ``` and paste to the public folder in the root of my app and 
2) As per laravel 8, I had to change
 `use App\Models\User;` to `use App\Models\User;`
 in the `MessagesController.php` file in the folder of```vendor\munafio\chatify\src\Http\Controllers``` 
Now it is working like laravel 6 version.
You can clone this demo: https://github.com/Haronur/chat-app-with-Laravel

**Comment by munafio** [comment]
First, assets(css, js,...) can be published as mentioned [here](https://github.com/munafio/chatify#3-publishing-assets) in the installations steps.
Second, Currently you can not customize Model's used in this package from it's config .. but! in the next version it will support that.
