### ISSUE TITLE
Feature Request: Implement Chunk Upload for Large Files

### ISSUE THREAD

**Issue by manhtruongwang** [munafio/chatify#331]
As an avid user of the Chatify package, I have greatly appreciated its seamless integration and ease of use. However, I've encountered a significant limitation when it comes to file sharing within Cloudflare environments. Cloudflare imposes a 100MB upload limit, which restricts the uploading of large files through Chatify. This limitation affects user experience, as larger media files or documents cannot be shared directly through the chat interface.

**Proposed Solution**

To resolve this issue and enhance the file-sharing experience, I would like to propose the implementation of a chunk upload functionality. This feature would allow files to be split into smaller segments (chunks) and uploaded sequentially. This method of uploading would not only address Cloudflare's limitations but would also provide a more robust and reliable file transfer process.

**Why is this feature important?**

- **Compatibility with Cloudflare**: By implementing chunked uploads, Chatify would become more versatile and functional for users who deploy their applications behind Cloudflare.
- **Improved Reliability**: Chunking large files mitigates the risk of failed uploads due to network issues or size restrictions, as only the affected chunk would need to be resent.
- **Enhanced User Experience**: Users would benefit from a smoother upload process with progress indicators and the ability to pause and resume uploads.
- **Server Performance**: Chunked uploads can lead to more efficient use of server resources and bandwidth, resulting in better performance for the application.

I hope to see this feature considered for future releases. Thank you for your attention to this matter.

**Comment by munafio** [comment]
@manhtruongwang I will put that in mind, but currently not planned in our next releases
