### ISSUE TITLE
BUG: Cannot declare class Chatify\Http\Controllers\MessagesController, because the name is already in use

### ISSUE THREAD

**Issue by abbas-roholamin** [munafio/chatify#332]
I installed the Chatify laravel package to add "live-chat" functionality to my existing Laravel application. After I published the controller assets following this documentation: [https://chatify.munafio.com/customizations](https://chatify.munafio.com/customizations) I got the `error: Cannot declare class Chatify\Http\Controllers\MessagesController because the name is already in use.`

Here is my config/chatify.php:

```
 'routes' => [
        'prefix' => env('CHATIFY_ROUTES_PREFIX', 'chatify'),
        'middleware' => env('CHATIFY_ROUTES_MIDDLEWARE', ['admin']),
        'namespace' => env('CHATIFY_ROUTES_NAMESPACE', 'App\Http\Controllers\vendor\Chatify'),
    ],
    
    'api_routes' => [
        'prefix' => env('CHATIFY_API_ROUTES_PREFIX', 'chatify/api'),
        'middleware' => env('CHATIFY_API_ROUTES_MIDDLEWARE', ['api']),
        'namespace' => env('CHATIFY_API_ROUTES_NAMESPACE', 'App\Http\Controllers\vendor\Chatify\Api'),
    ],
```

When I published the controller assets, it created the following directories:

`app\Http\Controllers\Vendor\Chatify\Api\MessagesController.php`

and

`app\Http\Controllers\Vendor\Chatify\MessagesController.php`

**Comment by iislamtaleb** [comment]
same error here

**Comment by iislamtaleb** [comment]
> I installed the Chatify laravel package to add "live-chat" functionality to my existing Laravel application. After I published the controller assets following this documentation: https://chatify.munafio.com/customizations I got the `error: Cannot declare class Chatify\Http\Controllers\MessagesController because the name is already in use.`
> 
> Here is my config/chatify.php:
> 
> ```
>  'routes' => [
>         'prefix' => env('CHATIFY_ROUTES_PREFIX', 'chatify'),
>         'middleware' => env('CHATIFY_ROUTES_MIDDLEWARE', ['admin']),
>         'namespace' => env('CHATIFY_ROUTES_NAMESPACE', 'App\Http\Controllers\vendor\Chatify'),
>     ],
>     
>     'api_routes' => [
>         'prefix' => env('CHATIFY_API_ROUTES_PREFIX', 'chatify/api'),
>         'middleware' => env('CHATIFY_API_ROUTES_MIDDLEWARE', ['api']),
>         'namespace' => env('CHATIFY_API_ROUTES_NAMESPACE', 'App\Http\Controllers\vendor\Chatify\Api'),
>     ],
> ```
> 
> When I published the controller assets, it created the following directories:
> 
> `app\Http\Controllers\Vendor\Chatify\Api\MessagesController.php`
> 
> and
> 
> `app\Http\Controllers\Vendor\Chatify\MessagesController.php`

Change the namespace from "namespace Chatify\Http\Controllers;
" to " namespace App\Http\Controllers\vendor\Chatify;"

**Comment by munafio** [comment]
@abbas-roholamin same as @iislamtaleb has said, you have to change the namespace after publishing the controllers, please read the docs carefully before opening an issue.
