### ISSUE TITLE
The chat not update in real time 

### ISSUE THREAD

**Issue by hasanhadi** [munafio/chatify#335]
Hi
When send message to user the message not display in user in real time and work only if the user is reload the chat page
How can resolve this problem

**Comment by munafio** [comment]
@hasanhadi Make sure all your credentials are correct also check console & network tab in your browser's devtools to check for any errors there, if any.

**Comment by hasanhadi** [comment]
> @hasanhadi Make sure all your credentials are correct also check console & network tab in your browser's devtools to check for any errors there, if any.

Hi
please see the attached picture for error & log file for Laravel

how can make new event for refresh every 5 sec for example because is working if manual refresh
can be add function for sendMessage to resolve this problem
many thanks

![1](https://github.com/munafio/chatify/assets/15230351/965e63fb-af68-40b4-9b1e-ed7d4518c9c2)
[laravel.log](https://github.com/munafio/chatify/files/14717598/laravel.log)

**Comment by hussain4real** [comment]
facing same error, any updates

**Comment by husamsaleh** [comment]
same here, for some reason the bootstrap.js inside resources>js>bootstrap was commented :

import Echo from "laravel-echo";
import Pusher from "pusher-js";
window.Pusher = Pusher;

window.Echo = new Echo({
    broadcaster: "pusher",
    key: import.meta.env.VITE_PUSHER_APP_KEY,
    cluster: import.meta.env.VITE_PUSHER_APP_CLUSTER ?? "mt1",
    wsHost: import.meta.env.VITE_PUSHER_HOST
        ? import.meta.env.VITE_PUSHER_HOST
        : `ws-${import.meta.env.VITE_PUSHER_APP_CLUSTER}.pusher.com`,
    wsPort: import.meta.env.VITE_PUSHER_PORT ?? 80,
    wssPort: import.meta.env.VITE_PUSHER_PORT ?? 443,
    forceTLS: (import.meta.env.VITE_PUSHER_SCHEME ?? "https") === "https",
    enabledTransports: ["ws", "wss"],
});


.......
i don't know what else is configured wrong

**Comment by munafio** [comment]
@hasanhadi check `network` tab in your browser's devtools, there may be failed requests

**Comment by munafio** [comment]
closed due to inactivity

**Comment by Zain541** [comment]
Hi @munafio 
This is the network tab
![image](https://github.com/munafio/chatify/assets/18334780/0daa287a-0219-46e5-adbd-59172a80c59c)
