### ISSUE TITLE
Websocket not working

### ISSUE THREAD

**Issue by Isyraf98** [munafio/chatify#338]
Hi. I try using websocket instead of pusher. But it not working.
![Screen Shot 2024-04-05 at 11 23 52 AM](https://github.com/munafio/chatify/assets/138425138/b7108f2c-c532-427f-953a-49d0c5956f05)

Below are my .env
`PUSHER_APP_ID=blanditiis                              # Any random string
PUSHER_APP_KEY=illo                                   # Any random string
PUSHER_APP_SECRET=dolores                             # Any random string
PUSHER_HOST=127.0.0.1                                 # Server host
PUSHER_PORT=6001                                      # Server port
PUSHER_SCHEME=http                                    # For SSL use 'https', otherwise use 'http'.
PUSHER_APP_CLUSTER=mt1
LARAVEL_WEBSOCKETS_PORT="${PUSHER_PORT}"              # Laravel WS port

LARAVEL_WEBSOCKETS_SSL_LOCAL_PK=      # Optional for using SSL.
LARAVEL_WEBSOCKETS_SSL_LOCAL_CERT=    # Optional for using SSL.`

do i need existing pusher app key?

**Comment by munafio** [comment]
@Isyraf98 you should refer to Laravel Websockets configuration then set your creds here
