### ISSUE TITLE
Unable to publish route files

### ISSUE THREAD

**Issue by akhilkharva** [munafio/chatify#343]
Hello @munafio , 

I am trying to publish the route files using 

command :php artisan vendor:publish --tag=chatify-routes, 

but i am unable to publish it. 
![vendor-publish-chatify-routes](https://github.com/munafio/chatify/assets/51924462/96859788-aaba-481e-8344-6785fe3f48cc)

Even it is not visible in "vendor:publish" list
![vendor-publish-list](https://github.com/munafio/chatify/assets/51924462/76ed11c9-9b41-4509-87af-889863a331af)

Please look into this, it will be a great help to my current project where i am implementing some customizations on it.

Thanks in advance.

**Comment by munafio** [comment]
@akhilkharva what version you are using ?

**Comment by akhilkharva** [comment]
@munafio i have shared my versions here..

```
"laravel/framework": "^10.10",

"php": "^8.1",

"munafio/chatify": "^1.6",
```

**Comment by munafio** [comment]
@akhilkharva make sure you are using `v1.6.3` which is the latest for now, and follow up with the docs here
https://chatify.munafio.com/customizations#custom-routes

**Comment by akhilkharva** [comment]
Thanks @munafio the new version worked for me...
