### ISSUE TITLE
Can't authenticate my Customers user table

### ISSUE THREAD

**Issue by Xaliu** [munafio/chatify#346]
I've installed the chatify successful,
I tried to go to /chatify but it returns to /login.

It seems like the chatify is fetching users from my user table instead of customers table. 
How do I solve this problem?

**Comment by munafio** [comment]
@Xaliu By default, Chatify looks into your `users` table , if you need custom table to be used then you need to change users table from controllers and the main class .. 
https://chatify.munafio.com/customizations
