### ISSUE TITLE
The chat not update in real time

### ISSUE THREAD

**Issue by Ali3bdelhady** [munafio/chatify#353]
Hi @munafio I have submitted a Ticket before with diff. title so I guess if I change the title, maybe someone will give me the answer so am sorry for opening two tickets with the same issue 
This is the link for it [link for old ticket](https://github.com/munafio/chatify/issues/350)
I have Laravel with a debugger but I added chat to except and I have APP_DEBUG=false
like in the following 
![debugger](https://github.com/munafio/chatify/assets/105130773/4c9238f4-f04b-451c-9fbe-dc1761d343d5)
the system works so well on my local machine  
but when I upload it to my server 
I got an Internal Server Error as following 
![image](https://github.com/munafio/chatify/assets/105130773/633fe324-3325-4754-937f-2ddedfa5e84d)
![console 2](https://github.com/munafio/chatify/assets/105130773/983a2046-2b07-4969-b804-00856b16db18)
![console](https://github.com/munafio/chatify/assets/105130773/1f4b616a-a4cd-4526-bd99-ea7fc3612938)
![js](https://github.com/munafio/chatify/assets/105130773/57575550-d926-4f16-83d0-70a82c94d137)
![network](https://github.com/munafio/chatify/assets/105130773/764a95f0-e7eb-4c87-8aca-6d04da74841b)

**Comment by inmass** [comment]
if you can activate debugging for more details

**Comment by Ali3bdelhady** [comment]
> if you can activate debugging for more details
@inmass  when activate debugging to chatify not work at all with same issues

**Comment by Ali3bdelhady** [comment]
@inmass @vicenterusso @carloscapela @stoneshaq 
Could anyone help me, please?

**Comment by inmass** [comment]
@Ali3bdelhady could you activate debug and share the errors you get ?

**Comment by Ali3bdelhady** [comment]
@inmass 
I got these errors 
![console pusher error](https://github.com/munafio/chatify/assets/105130773/cc15c699-d0c9-4e8a-aa9a-5df2a8932c7d)
![network](https://github.com/munafio/chatify/assets/105130773/78d8f582-4130-401b-a2b4-7d1d052a0b89)
but my server time is set as my local machine

**Comment by Ali3bdelhady** [comment]
@inmass I got it my time was correct but I didn't check the date.
I appreciate your help.

**Comment by inmass** [comment]
@Ali3bdelhady  does this mean that your issue was fixed ? :D

**Comment by Ali3bdelhady** [comment]
> @Ali3bdelhady does this mean that your issue was fixed ? :D

Yes
