### ISSUE TITLE
License

### ISSUE THREAD

**Issue by wklau2006** [munafio/chatify#354]
Hi,

Thank you for creating such a good app. I noticed that recently license is added but it is a GPL. Would you consider using a more permissive license such as LGPL or MIT? The README does say Chatify is licensed under MIT.

Thanks.

**Comment by wklau2006** [comment]
You may want to update https://chatify.munafio.com/#license also.

**Comment by munafio** [comment]
> You may want to update https://chatify.munafio.com/#license also.

I will, thank you 🙏🏻

**Comment by MansourM** [comment]
Hey @munafio!

First off, awesome work on Chatify! It looks like a great solution for what I’m trying to build.

I’m working on adding live chat to the ticketing system in my project, and I found Chatify on GitHub. But I noticed a bit of a mix-up: the README, composer.json and docs say it’s MIT-licensed, but the license file mentions GPL-3.0.

Could you clarify which one is correct?

If it’s GPL-3.0,  I wouldn’t be able to use it in my project without having to open-source everything (thanks to the “viral” part of GPL). I’m hoping it’s MIT though, so I can go ahead and use it!

**Comment by munafio** [comment]
> Hey @munafio!
> 
> 
> 
> First off, awesome work on Chatify! It looks like a great solution for what I’m trying to build.
> 
> 
> 
> I’m working on adding live chat to the ticketing system in my project, and I found Chatify on GitHub. But I noticed a bit of a mix-up: the README, composer.json and docs say it’s MIT-licensed, but the license file mentions GPL-3.0.
> 
> 
> 
> Could you clarify which one is correct?
> 
> 
> 
> If it’s GPL-3.0,  I wouldn’t be able to use it in my project without having to open-source everything (thanks to the “viral” part of GPL). I’m hoping it’s MIT though, so I can go ahead and use it!

Its MIT, and there was a mistake that will be fixed soon.
