### ISSUE TITLE
When we open chat in mobile phone, then a white box appears below message box!

### ISSUE THREAD

**Issue by developmentveye** [munafio/chatify#370]
in android/mobile phone when we open chat, then a white box appears below message box is appearing and message box gets scrolled to the top.

![IMG-20241008-WA0123](https://github.com/user-attachments/assets/a4fedc10-59dd-4ad6-9f21-07ab770d3ff1)

**Comment by developmentveye** [comment]
this whole area (other than messages area) is scrollable.

**Comment by munafio** [comment]
@developmentveye duplicated #249
