### ISSUE TITLE
How Find Users

### ISSUE THREAD

**Issue by CChirino** [munafio/chatify#39]
When I try to search for a user in the chat, nothing is thrown at me,
I modify the value to search for another
MessagesController.php
![Captura de pantalla de 2020-09-23 13-30-07](https://user-images.githubusercontent.com/34484098/94048157-114c5a80-fda1-11ea-8731-092758b6fc56.png)
Client view
![Captura de pantalla de 2020-09-23 13-31-57](https://user-images.githubusercontent.com/34484098/94048248-3b058180-fda1-11ea-8f7e-8b2f0e7e8571.png)

**Comment by munafio** [comment]
@CChirino  That's because Chatify's `MessageController` not applies the changes you modified, see #10.

**Comment by munafio** [comment]
Duplicated
