### ISSUE TITLE
Route [home] not defined. (View: D:\laragon\www\chatmic\vendor\munafio\chatify\views\pages\app.blade.php)

### ISSUE THREAD

**Issue by dhruv1998** [munafio/chatify#41]
hi everyone today I have integrated chatify with my app I followed the process of chatify to install but when i am trying to access chatify to their default url i am getting this error and I integrated with laravel 7

**Comment by nguyenhuuphuchp** [comment]
I have the same problem, same question. After edit web.php then page without css and scripts

Route [home] not defined. (View: D:\LUAN VAN\bookshop\vendor\munafio\chatify\views\pages\app.blade.php).

**Comment by munafio** [comment]
@dhruv1998 @phuchuu26 
You need to publish the assets as mentioned [here](https://github.com/munafio/chatify#3-publishing-assets), and modify `app.blade.php` which will be inside your app (views/vendor/Chatify/pages) line 75 : 
```
<a href="{{ route('home') }}"><i class="fas fa-home"></i></a>
```
change `route('home')` to your home's route name.

if you don't have a name for your `home` route, set a name and refer that name to the link above as mentioned.

**Comment by nguyenhuuphuchp** [comment]
![image](https://user-images.githubusercontent.com/57587201/94359485-b896fd80-00d1-11eb-869b-9ccf11e7da09.png)
![Uploading Screenshot (537).png…]()

**Comment by munafio** [comment]
@phuchuu26 Looks like you did not published the assets .. please follow the installation guide step by step and it will work perfectly

**Comment by dhruv1998** [comment]
Thanks it worked for me

**Comment by dhruv1998** [comment]
One issue I can see in laravel 7 user model path is app/models/auth/user but you have used app/user which is making problem for me do you have any solution for that

**Comment by munafio** [comment]
@dhruv1998 This will be fixed with v2, you will be able to customize the package as your needs.

**Comment by dhruv1998** [comment]
Great thanks for your help

**Comment by dhruv1998** [comment]
hii @munafio  chats are not real-time every time I need to click on the user symbol to get the msg can you help me to get the msg real-time without clicking the user symbol

**Comment by munafio** [comment]
@dhruv1998 This is not related to this issue! 
Please if you see this is an issue, open a new one.. But before that:
Check out your pusher credentials and hope to follow the docs step by step to get it to work.

**Comment by dhruv1998** [comment]
Ok I'll check again @munafio
