### ISSUE TITLE
Every user can see all users, even the admin

### ISSUE THREAD

**Issue by cletuskingdom** [munafio/chatify#42]
Please how can i customize the app to only view specific users.

I don't want the authenticated user to view everyone, i want to be able to specify which users an authenticated user sees.

**Comment by munafio** [comment]
You can customize it by publishing the assets (controllers) and you need then to change the namespace of the package's controllers form the `config/chatify.php`

**Comment by munafio** [comment]
Check out #10 if you followed the instructions above and not worked.
