### ISSUE TITLE
chats are not real-time every time I need to click on the user symbol to get the msg can you help me to get the msg real-time without clicking the user symbol

### ISSUE THREAD

**Issue by dhruv1998** [munafio/chatify#45]
my pusher is working correctly I can see peak connection and the total message sent in pusher but it's not real-time

**Comment by munafio** [comment]
Provide me more details, open the  inspector and see if any errors occured or if pusher connection refused...

**Comment by dhruv1998** [comment]
Sorry for late reply I am busy a bit I'll chek and let you know @munafio

**Comment by dhruv1998** [comment]
@munafio I am getting this error in inspect for Pusher : Event recd : {"event":"pusher:error","data":{"code":null,"message":"Cannot broadcast client event (connection not subscribed to channel private-chatify)"}}

**Comment by munafio** [comment]
@dhruv1998 duplicated #17
you need to enable client-events in your Pusher account as mentioned in the documentaion.
