### ISSUE TITLE
Target class [MessagesController] does not exist.

### ISSUE THREAD

**Issue by dhruv1998** [munafio/chatify#46]
after updating the package I am getting this error. I updated the package in this version v1.0.0 to v1.0.1

**Comment by munafio** [comment]
Please can you provide me a details about this error? Where did happen?

**Comment by munafio** [comment]
@dhruv1998 Please can you provide me a details about this error? Where did happen?

**Comment by dhruv1998** [comment]
@munafio i got this error in when I try to visit default route.  /chatify

**Comment by munafio** [comment]
@dhruv1998 be clear with your question.. Where did it occure? Which file, line!?

**Comment by dhruv1998** [comment]
@munafio as per my understanding I am getting this error in routes web.php in line no 15 but I am not getting why it's coming that's why I am looking for a positive response from your side

**Comment by munafio** [comment]
Open `yourapp/config/chatify.php` and check out `namespace` property,

If you published controllers, so it should be :
`App/Http/Controllers/vendor/Chatify`
This to make routes' namespace depends on the published controllers not package's conrollers. 

or if not, it should be (as default) :
`Chatify/Http/Controllers`

**Comment by munafio** [comment]
@dhruv1998 Open `yourapp/config/chatify.php` and check out `namespace` property,

If you published controllers, so it should be :
`App/Http/Controllers/vendor/Chatify`
This to make routes' namespace depends on the published controllers not package's conrollers. 

or if not, it should be (as default) :
`Chatify/Http/Controllers`

**Comment by dhruv1998** [comment]
@munafio namespace property doesn't exist only in  config/chatify.php  this my whole chatify.php
   
   `return [

    /*
    |--------------------------------------------------------------------------
    | Messenger app name
    |--------------------------------------------------------------------------
    |
    | This value is the name of the app which is used in the views or elsewhere
    | in this app.
    |
    */

    'name' => env('CHATIFY_NAME', 'Chatify Messenger'),

    /*
    |--------------------------------------------------------------------------
    | Package path
    |--------------------------------------------------------------------------
    |
    | This value is the path of the package or in other meaning, it is the prefix
    | of all the registered routes in this package.
    |
    | e.g. : app.test/chatify
    */

    'path' => env('CHATIFY_PATH', 'chatify'),

    /*
    |--------------------------------------------------------------------------
    | Package's web routes middleware
    |--------------------------------------------------------------------------
    |
    | This value is the middleware of all routes registered in this package
    | which is by default : auth
    |
    */

    'middleware' => env('CHATIFY_MIDDLEWARE', 'auth'),

    /*
    |--------------------------------------------------------------------------
    | Pusher API credentials
    |--------------------------------------------------------------------------
    |
    | This array includes all the credentials that required to use pusher API
    | with Chatty package, which is used to broadcast events over websockets to
    | create a real-time features.
    |
    */
    'pusher' => [
        'key' => env('PUSHER_APP_KEY'),
        'secret' => env('PUSHER_APP_SECRET'),
        'app_id' => env('PUSHER_APP_ID'),
        'options' => [
            'cluster' => env('PUSHER_APP_CLUSTER'),
            'encrypted' => false,
        ],
    ],

    /*
    |--------------------------------------------------------------------------
    | User Avatar
    |--------------------------------------------------------------------------
    |
    | This is the user's avatar setting that includes :
    | [folder]  which is the default folder name to upload and get
    |           user's avatar from.
    | [default] which is the default avatar file name for users stored
    |           in database.
    |
    */
    'user_avatar' => [
        'folder' => 'users-avatar',
        'default' => 'avatar.png',
    ],

    /*
    |--------------------------------------------------------------------------
    | Attachments By Default
    |--------------------------------------------------------------------------
    |
    | This array contains the important default values that used in this package.
    |
    | The first value in this array is the default folder name in the storage
    | which is all the attachments will be stored in.
    | This is also going to be used in attachments urls in the views.
    |
    */
    'attachments' => [
        'folder' => 'attachments',
        // Below is the route name to download attachments.
        'route' => 'attachments.download',
    ],
];`

**Comment by munafio** [comment]
@dhruv1998 namespace available with v1.0.1
please re-install the package and follow the installation guide  step by step and it will work as it should 🙏🏻

**Comment by dhruv1998** [comment]
thanks @munafio it worked

**Comment by agnes2222** [comment]
![image](https://user-images.githubusercontent.com/79841623/115528611-df4d9900-a29a-11eb-9221-3131b545bc43.png)
aide moi sltpl
