### ISSUE TITLE
Is there any problem with Laravel 8.x

### ISSUE THREAD

**Issue by psycho3069** [munafio/chatify#48]
I am trying to use chatify with laravel 8.x and there shows a problem with home routing

**Comment by munafio** [comment]
@psycho3069 please provide more details about your issue

**Comment by psycho3069** [comment]
well I think I got the problem and also fixed it. To state it clearly, the latest version of Laravel (8.x) which uses Jetsteam has changed/renamed the 'home' route to 'dashboard'. So, without accessing localhost:8000/chatify the laravel works fine along with it's new components and named routes. But when tried to view chatify it shows the error: Route [home] not found as laravel 8 renamed it to 'dashboard'. To solve it, I copied the existing dashboard route and created another and renamed it to 'home' and the problem was solved.
![Capture](https://user-images.githubusercontent.com/33130889/95660682-426fad80-0b4b-11eb-95e0-12981effcb63.JPG)

**Comment by munafio** [comment]
@psycho3069 you don't need to do that with Laravel 8 routes.
All you need is to publish the assets (views) by this artisan command:
```
$ php artisan vendor:publish --tag=chatify-views
```
as mentioned [here](https://github.com/munafio/chatify#3-publishing-assets), this will make a copy of Chatify `views` into your app's views to be modified as your needs.


then you need to go and modify `app.blade.php` :
 ```
yourapp/resources/views/vendor/Chatify/pages/app.blade.php
```

line 75, change `route('home')` to your home route name, which in your case will be like `route('dashboard')`.
