### ISSUE TITLE
Upgrade to Chatify v2.0

### ISSUE THREAD

**Issue by zeus6999** [munafio/chatify#49]
Hi,

How soon do you upgrade to Chatify v2.0?

Regards

**Comment by munafio** [comment]
Welcome,
I can't say a specific time, but as soon as possible it will be released.
Regards

**Comment by zeus6999** [comment]
Chatify v2.0
1.Are you planning to add notification in the header?
2.Will it be possible to insert Chatify v2.0 in any existing laravel code?
Regards
