### ISSUE TITLE
Feature request for delete message feature+ small suggestion

### ISSUE THREAD

**Issue by gileneusz** [munafio/chatify#5]
Would be great to have an opportunity to delete the sent message. 

Also I had some stupid problems with instalation, because I run that on clean Laravel 6.x instalation. So I had to add the new authentication commands: 

```

composer require laravel/ui --dev
php artisan ui vue --auth
npm install && npm run dev

```

without those commands the package would not run, would be nice for others if you will add that in the documentation

**Comment by munafio** [comment]
I'll keep it in mind, thanks.

And about the user authentication system, I already added `Quick Note` about that [here](https://github.com/munafio/chatify#1-install-the-package-in-your-laravel-app).
