### ISSUE TITLE
getContacts error when fetching using MSSQL

### ISSUE THREAD

**Issue by nazirulfitrifauzi** [munafio/chatify#50]
I get this error 
"SQLSTATE[42000]: [Microsoft][ODBC Driver 13 for SQL Server][SQL Server]A column has been specified more than once in the order by list. Columns in the order by list must be unique. (SQL: select top 1 * from [messages] where [from_id] = 2 and [to_id] = 1 or [from_id] = 1 and [to_id] = 2 **order by [created_at] desc, [created_at] desc**)" 
when running using MSSQL db.

I fix it by comment out orderBy in the ChatifyMessenger.php
from : `public function getLastMessageQuery($user_id){
        return self::fetchMessagesQuery($user_id)->orderBy('created_at','DESC')->latest()->first();
    }`

to : `public function getLastMessageQuery($user_id){
        return self::fetchMessagesQuery($user_id)->latest()->first();
    }`

**Comment by munafio** [comment]
I think this issue related to MSSQL..
You can try removing DESC and run your query again.. OR! write a query instead of using QueryBuilder to match your needs.
