### ISSUE TITLE
Trying to get property 'dark_mode' of non-object

### ISSUE THREAD

**Issue by isaacongoma** [munafio/chatify#51]
Tring to get an error "Trying to get property 'dark_mode' of non-object" when I load the inbox page.

Here is the piece of my message controller
`        return view('Chatify::pages.app', [
            'id' => ($id == null) ? 0 : $route . '_' . $id,
            'route' => $route,
            'messengerColor' => isset(Auth::user()->messenger_color)?Auth::user()->messenger_color:' ',
            'dark_mode' => Auth::user()->dark_mode < 1 ? 'light' : 'dark',
        ]);
    }`

**Comment by munafio** [comment]
Try `['dark_mode'] ` instead of `->dark_mode`
