### ISSUE TITLE
 InvalidArgumentException Route [login] not defined.

### ISSUE THREAD

**Issue by AntonJanLindholm** [munafio/chatify#59]
I am getting this problem-
InvalidArgumentException
Route [login] not defined.
![problem](https://user-images.githubusercontent.com/66430940/100863322-b2881900-3494-11eb-9595-6796ecb28a66.PNG)
![problem 2](https://user-images.githubusercontent.com/66430940/100863323-b3b94600-3494-11eb-84ed-083796c98969.PNG)

**Comment by AntonJanLindholm** [comment]
I fixed it by:
php artisan make:auth

**Comment by munafio** [comment]
As mentioned in the docs, Laravel auth scaffolding is required.
