### ISSUE TITLE
Target class [App\Http\Controllers\vendor\Chatify\MessagesController] does not exist.

### ISSUE THREAD

**Issue by odion-cloud** [munafio/chatify#62]
Illuminate\Contracts\Container\BindingResolutionException
Target class [App\Http\Controllers\vendor\Chatify\MessagesController] does not exist.

this error come up after publish config

**Comment by munafio** [comment]
If you need to modify the MessagesController, you have to publish the assets as mentioned in the docs (on the configurations section).

Check out [this](https://github.com/munafio/chatify#controllers-namespace) **(Controller's Namespace)** for more information

**Comment by Expertweblancer** [comment]
`        'namespace' => env('CHATIFY_ROUTES_NAMESPACE', 'App\Http\Controllers\vendor\Chatify'),
`
I changed namespace and published controller assets. 
but I still get this error.

Illuminate\Contracts\Container\BindingResolutionException
Target class [App\Http\Controllers\vendor\Chatify\MessagesController] does not exist.

**Comment by Expertweblancer** [comment]
I fixed the issue.
I needed to change namespace on MessagesController as well.
like this
`// namespace Chatify\Http\Controllers;
namespace App\Http\Controllers\vendor\Chatify;`
