### ISSUE TITLE
the routing for chatify dose not work 

### ISSUE THREAD

**Issue by adimoz** [munafio/chatify#65]
i followed the steps and made sure i did it right, however when i visit /chatify route it gives me the interface but nothing more, it might be because i am using laravel 8, i tried to fix it by moving the controller and changing all routes at the web.php but still stuck, thank you.

**Comment by odion-cloud** [comment]
same here

**Comment by pallavbansal** [comment]
same. Any fix ??????

**Comment by munafio** [comment]
Make sure to follow the steps mentioned in the documentation.
* Currently,  Laravel 8+ not supported by Chatify v1 .. But v2 will support Laravel 8+, and will be released ASAP.
Thank you
