### ISSUE TITLE
when is this package going to support laravel 8x versions

### ISSUE THREAD

**Issue by odion-cloud** [munafio/chatify#66]

**Comment by munafio** [comment]
* Laravel 8+ will be supported with chatify v2.
**Chatify v2** release date may be delayed because of my job and time by general. 
But I promise that `(Chatify v2 will be amazing)`, so be patience ❤️

**Comment by lelu0** [comment]
Actually this package may work with L8 after few quite simple changes.
What have I done:
1. Install as in the tutorial
2. Fix route naming issue by publishing package views and changing route in Line:75 of  `resources\views\vendor\Chatify\pages\app.blade.php`
for
`<a href="/"><i class="fas fa-home"></i></a> `
3. If you have chatify page but can't interact and in the console is error about '$' being not defined you need to install jquery. 
So, do `npm i -D jquery`
then go to ` resources/js/bootstrap.js` and add `window.$ = require('jquery');`
then do `npm run dev`
4. Almost there. Probably you can interact, but can't search for users. Publish controller and do change in config as is in the documentation. Remember to cache config. Then go to controller. change namespace: 
`namespace App\Http\Controllers\vendor\Chatify;`
and change user model use to `use App\Models\User;`.
After that package is working for me.

**Comment by Mhmdabbasi** [comment]
Can I use this package with laravel8?
If not;  then can please tell us when **Chatify v2** going to be release?
