### ISSUE TITLE
jquery issue

### ISSUE THREAD

**Issue by mithauae** [munafio/chatify#69]
given the cdn link in headlinks.blade.php as

<script
  src="https://code.jquery.com/jquery-3.5.1.min.js"
  integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0="
  crossorigin="anonymous"></script>

and given publish command

php artisan vendor:publish --tag=chatify-views

still getting the error
Uncaught ReferenceError: $ is not defined

**Comment by munafio** [comment]
you need to publish the assets (css, js..) + the views and then add jQuery if it does not exist.

Or please provide error's details and where it occures.

**Comment by munafio** [comment]
Example:
headlinks.blade.php :
```
{{-- scripts --}}
<script
  src="https://code.jquery.com/jquery-3.5.1.min.js"
  integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0="
  crossorigin="anonymous"></script>
```

add jQuery after the `scripts` comment like the above example
