### ISSUE TITLE
Groups Messaging

### ISSUE THREAD

**Issue by karabayyazilim** [munafio/chatify#71]
When will group messaging arrive ?

**Comment by munafio** [comment]
Will available with Chatify v2

**Comment by dastiw1** [comment]
When v2 is realised?

**Comment by arshadinvoked** [comment]
Whats about the group messaging functionality is it updated or not ?

**Comment by munafio** [comment]
Checkout [this discussion](https://github.com/munafio/chatify/discussions/222)
