### ISSUE TITLE
Chats are not real-time

### ISSUE THREAD

**Issue by B3K4682** [munafio/chatify#73]
I have enabled client events, but chat still isn't real-time. why?

**Comment by Karma99** [comment]
I have enabled client events, but chat still isn't real-time. why?

**Comment by munafio** [comment]
@Karma99 @B3K4682 Please open up dev tools and check out pusher's messages if any errors occurred there? then provide me with the details so I can help you.

**Comment by B3K4682** [comment]
```
ERROR:
Cannot broadcast client event (connection not subscribed to channel private-chatify)
```

**Comment by munafio** [comment]
@B3K4682 Check out this issue #17

**Comment by B3K4682** [comment]
Thank you!
