### ISSUE TITLE
chatify/updateSettings(Console Log)

### ISSUE THREAD

**Issue by hattorihanzo86** [munafio/chatify#75]
Failed to load resource: the server responded with a status of 500 (Internal Server Error) 
the routes does not properly read even its on routelist, route:clear 

Laravel 5.8

**Comment by munafio** [comment]
@supacoderzpro Please can you provide more details about your issue ?

**Comment by munafio** [comment]
This issue will be closed, because of inactivity!

**Comment by hattorihanzo86** [comment]
Still the issue will never resolve even you close it brother some resources cannot be load with status of 500 :) (Internal Server Error)
