### ISSUE TITLE
No Option For Multi Guard Auth

### ISSUE THREAD

**Issue by rizwansaleem70** [munafio/chatify#76]
I have 3 types of users, each with different auth guard types. 

Admin
Influencer
Brand

In your code, you've only added Auth::user() there isn't any option or way to add guard() so we can use different auth guard types.

Regards,
Rizwan

**Comment by munafio** [comment]
@webribs Hi,
there is an option to modify/customize package's controller to meet your needs, so you can check it out.

**Comment by mh24409** [comment]
@webribs  how you do that ?
