### ISSUE TITLE
Pusher php version 7.4 error

### ISSUE THREAD

**Issue by hesammoosapour** [munafio/chatify#77]
Pusher php server only supports verisons of php below 7.3  , but I have a higher version of php .

Please upgrade chatify to support pusher php server of higher version.

**Comment by DevelopmentNightmare** [comment]
Yes, I also need 7.4!

**Comment by Argornst** [comment]
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - munafio/chatify[v1.0.0, ..., v1.0.1] require pusher/pusher-php-server ^3.4@dev -> found pusher/pusher-php-server[v3.4.0, v3.4.1] but it conflicts with your root composer.json require (^5.0).
    - Root composer.json requires munafio/chatify ^1.0 -> satisfiable by munafio/chatify[v1.0.0, v1.0.1].

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.

Installation failed, reverting ./composer.json and ./composer.lock to their original content.

**Comment by munafio** [comment]
It will be supported in the next release SOON!

**Comment by hesammoosapour** [comment]
> Your requirements could not be resolved to an installable set of packages.
> 
> Problem 1
> - munafio/chatify[v1.0.0, ..., v1.0.1] require pusher/pusher-php-server ^3.4@dev -> found pusher/pusher-php-server[v3.4.0, v3.4.1] but it conflicts with your root composer.json require (^5.0).
> - Root composer.json requires munafio/chatify ^1.0 -> satisfiable by munafio/chatify[v1.0.0, v1.0.1].
> 
> Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.
> 
> Installation failed, reverting ./composer.json and ./composer.lock to their original content.

@Argornst Even by using option --with-all-dependencies it still doesn't work even when I put it inside provide brackets.
