### ISSUE TITLE
Failed to load resource: the server responded with a status of 500 ()

### ISSUE THREAD

**Issue by DevelopmentNightmare** [munafio/chatify#78]
I get the following issue when clicking on a chat: 

Failed to load resource: the server responded with a status of 500 () - <localhost>/messenger/idInfo

Which would translate to the function **idFetchData** not being found? Also the contact don't seem to get fetched.

PHP7.3
Laravel 8 (I know it's supported in V2 but I thought I'd give it a try)

**Comment by munafio** [comment]
@Dynalogical Can you please provide me the exact error message by opening the dev-tools > Network > then the request that causing the error.

**Comment by DevelopmentNightmare** [comment]
I forgot to close this. Turned out a migration went wrong because of the Favorites table. Could that be renamed to chat_favorites in the future? Anyhow, I got it working on Laravel 8 without any hassle!

**Comment by munafio** [comment]
@Dynalogical Yes, of course it will be renamed to avoid issues like this in the future!
