### ISSUE TITLE
Laravel Chatify Install issue PHP version 7.4

### ISSUE THREAD

**Issue by blpraveen** [munafio/chatify#79]
Hi,
I am trying to run the composer update with PHP version 7.4 and I get this error. Is it possible to resolve.

![laravel-chatify](https://user-images.githubusercontent.com/3274289/110122691-f2d59b00-7de5-11eb-8fc1-429cb05891e8.png)

**Comment by munafio** [comment]
Your PHP version is not compatible with Pusher's requirement.
So, you need a php version that meets Pusher's requirements OR you have to wait the next release which will solve this issue.
