### ISSUE TITLE
Jquery missing issue.

### ISSUE THREAD

**Issue by SagarMaher2** [munafio/chatify#8]
i ran into js issues due to jquery was not loaded before loading other scripts.

<script src="{{ asset('front/js/jquery-3.2.1.min.js')}}"></script>

add this in "\vendor\munafio\chatify\views\layouts\footerLinks.blade.php" to solve the issue 
"Uncaught ReferenceError: $ is not defined at code.js:7"

**Comment by munafio** [comment]
jQuery is already included with Laravel .. or if it's not, add it to your header
