### ISSUE TITLE
How I can remove middleware on '/chatify' route(web.php of vendor chatity). Which redirect '/chatify' to '/login'(Laravel auth).

### ISSUE THREAD

**Issue by prashantsingh2408** [munafio/chatify#80]
Problem: 
* I implement chatify in my current project.When I route through through `'/chatify' ` it redirect me to `'/login'`**(Laravel auth)** url.
*  My project  had already different  **login** and **registration pages ** using other view and controller(not uses laravel auth)

web.php 
`
![Screenshot from 2021-03-07 13-33-42](https://user-images.githubusercontent.com/17498602/110233399-d3578300-7f49-11eb-8e1d-eecac4cc7a80.png)
![Screenshot from 2021-03-07 13-33-45](https://user-images.githubusercontent.com/17498602/110233403-d5214680-7f49-11eb-950a-0233e8fd541e.png)
![Screenshot from 2021-03-07 13-33-47](https://user-images.githubusercontent.com/17498602/110233404-d783a080-7f49-11eb-82b1-159aad594edb.png)
![Screenshot from 2021-03-07 13-33-49](https://user-images.githubusercontent.com/17498602/110233406-d8b4cd80-7f49-11eb-94ff-354b018e6fee.png)
![Screenshot from 2021-03-07 13-33-52](https://user-images.githubusercontent.com/17498602/110233408-da7e9100-7f49-11eb-954b-a3bd2a2fdb57.png)
![Screenshot from 2021-03-07 13-35-01](https://user-images.githubusercontent.com/17498602/110233434-f5e99c00-7f49-11eb-9eb3-c1cfb871b43f.png)

**Comment by munafio** [comment]
@prashantsingh2408 You don't have to modify it from the package itself! you have to configure your Laravel app to use your custom auth system.
 and also I have to mention that this package requires the auth scaffolding to be worked! thats why this issue appears to you.

**Comment by prashantsingh2408** [comment]
Yes,you are right.It can be configure to use custom auth.Thanks for ur help👍 @munafio .

**Comment by mh24409** [comment]
Do you change auth guard ?

**Comment by Xaliu** [comment]
> Yes,you are right.It can be configure to use custom auth.Thanks for ur help👍 @munafio .

Please how where you able to solve the problems. I have customers users table I want to use for the chat instead of the users table. I get redirected to login page eache time.
