### ISSUE TITLE
No internet connection

### ISSUE THREAD

**Issue by Rk-choudhary-ck** [munafio/chatify#84]
Hii Munafio
i have face a problem with chatify here is some messages are send to user and few messages are not send. and top of the screen
![Screenshot (1)](https://user-images.githubusercontent.com/71312337/114172238-06c76c00-9953-11eb-9580-9a680bf54e3c.png)
 show internet problem how i can overcome from this problem please give me any idea.

**Comment by munafio** [comment]
@Rk-choudhary-ck There is a problem with your connection OR with your pushers' account, so check your credentials too.
