### ISSUE TITLE
Actually this package may work with L8 after few quite simple changes.

### ISSUE THREAD

**Issue by jrcambonga** [munafio/chatify#85]
Actually this package may work with L8 after few quite simple changes.
What have I done:
1. Install as in the tutorial
2. Fix route naming issue by publishing package views and changing route in Line:75 of  `resources\views\vendor\Chatify\pages\app.blade.php`
for
`<a href="/"><i class="fas fa-home"></i></a> `
3. If you have chatify page but can't interact and in the console is error about '$' being not defined you need to install jquery. 
So, do `npm i -D jquery`
then go to ` resources/js/bootstrap.js` and add `window.$ = require('jquery');`
then do `npm run dev`
4. Almost there. Probably you can interact, but can't search for users. Publish controller and do change in config as is in the documentation. Remember to cache config. Then go to controller. change namespace: 
`namespace App\Http\Controllers\vendor\Chatify;`
and change user model use to `use App\Models\User;`.
After that package is working for me.

_Originally posted by @lelu0 in https://github.com/munafio/chatify/issues/66#issuecomment-756083954_

**Comment by jrcambonga** [comment]
Hello, I tried this, but there's '$' in my error logs. Cant interact with my Chatify Page. Please help.

**Comment by munafio** [comment]
@jrcambonga Follow as @lelu0 have mentioned .. if still the same! you need to publish the assets (views) then open `views/layouts/headLinks.blade.php` and add jQuery link/script there.

 + Thanks to @lelu0

**Comment by jrcambonga** [comment]
great, thank you!

**Comment by sglavach** [comment]
Any help on identifying where (what files?) I need to change the User Model to 'use App\Models\User' would be appreciated.
Thanks!

**Comment by munafio** [comment]
> Any help on identifying where (what files?) I need to change the User Model to 'use App\Models\User' would be appreciated.
> 
> Thanks!

`src/Http/Controllers/MessagesController.php` line **11**
