### ISSUE TITLE
Trying to get property 'attachment' of non-object

### ISSUE THREAD

**Issue by MilanUnjiya4149** [munafio/chatify#88]
There are the issue with fetch messages.
The attachment is display on right side bar shared sections but not able to load chat sections.
PFA image.

![Screenshot_2](https://user-images.githubusercontent.com/53517616/114687559-85485300-9d31-11eb-99b7-c86c813b743a.png)

**Comment by munafio** [comment]
This will be fixed in the next release V1.2.0 ASAP .. I'll Keep you in touch.

**Comment by MilanUnjiya4149** [comment]
> This will be fixed in the next release V1.2.0 ASAP .. I'll Keep you in touch.

OK, Thank You.

**Comment by munafio** [comment]
@MilanUnjiya4149 SOLVED .. update to v1.2
Check out [CHANGELOG.md](https://github.com/munafio/chatify/blob/master/CHANGELOG.md) for more information about the new release.
