### ISSUE TITLE
attachment is not delete from storage on delete conversations operations.

### ISSUE THREAD

**Issue by MilanUnjiya4149** [munafio/chatify#89]
Attachment should be delete from storage on delete conversation operations.

**Comment by vzool** [comment]
I think this should be the channel's option which may vary from channel to channel.

**Comment by MilanUnjiya4149** [comment]
> I think this should be the channel's option which may vary from channel to channel.

Attachment is not related to channel... Need to write logic for delete related attachments from storage.

**Comment by munafio** [comment]
@MilanUnjiya4149 There is already a method to delete a conversation from DB + Storage as you can see : https://github.com/munafio/chatify/blob/7a0a4f3ea91e6282f20133ec0dbb021692ca10a9/src/ChatifyMessenger.php#L311

But I think it's related to #88 issue, I'll check it out and fix it ASAP.

**Comment by MilanUnjiya4149** [comment]
OK, Thank You.
