### ISSUE TITLE
Failed to fetch messages! Laravel 7

### ISSUE THREAD

**Issue by abdelkadergelany** [munafio/chatify#9]
after a fresh installation, everything is working perfectly. However, when I create conversations with 2 users it is unable to fetch the messages for each conversation. 
Laravel version:7
How to reproduce the error:
-after installation on a fresh laravel 7 project
-create a conversation with one user
-then create another conversation with another user
-now we have 3 actives users
-send messages to the other 2 users
-logout and login again
-then click on any conversation to open:
the error will be display on the console:
"Failed to fetch messages! check your server response. @ code.js:434"
"Failed to load resource: the server responded with a status of 500 (Internal Server Error)"
"message: "Trying to get property 'attachment' of non-object"
exception: "ErrorException"
file: "D:\xamp\htdocs\chatify\chatify\vendor\munafio\chatify\src\ChatifyMessenger.php"
line: 115"

**Comment by munafio** [comment]
Hi,
This happens because the package tries to get (attachment) property of non-object!!
You can solve that by modify ChatifyMessenger.php by publishing the assets .. and all you need is to change :
`$msg->attachment`
to
`$msg['attachment']`

**Comment by Rifatalmamun** [comment]
D:\xamp\htdocs\chatify\chatify\vendor\munafio\chatify\src\ChatifyMessenger.php 
 i replace all $msg->attachment to $msg['attachment'] . 
but same error !

**Comment by munafio** [comment]
@Rifatalmamun @abdelkadergelany I'll look for that and fix it, stay tuned for any updates.

**Comment by abhilash14001** [comment]
Me also getting same error... ....
After troubleshooting I came to know while sending the message it is using the same id again and again I think problem in id random generation i.e. mt_rand in send function

**Comment by abhilash14001** [comment]
> 
> 
> Me also getting same error... ....
> After troubleshooting I came to know while sending the message it is using the same id again and again I think problem in id random generation i.e. mt_rand in send function

When that id is called by fetch message it is unable to load, bcz that id is not inserted in database at all plz check into it

**Comment by San-tiago** [comment]
is this solved? i have the same issue though i change  $msg->attachment to $msg['attachment'] .

**Comment by munafio** [comment]
@San-tiago If you got the same issue, it will be fixed in the next release ASAP .. So, stay tuned.

**Comment by San-tiago** [comment]
Oww okay, thank youuuu. i will wait for it.
