### ISSUE TITLE
Need API Routes

### ISSUE THREAD

**Issue by afrasiyabhaider** [munafio/chatify#92]
Hello
I'm glad to see such a nice and clean package for Chat. Your efforts are much appreciated by the community of Laravel. I wanted to ask is there any API routes available for this package?
I've a mobile app in react native and wanted to connect that App with my Laravel website.

If there is anything I can help you with please tell me I'll be happy to collaborate. 
ping.afrasiyab.haider@gmail.com

@munafio

**Comment by munafio** [comment]
@afrasiyabhaider Thanks for reaching out, currently (v1.0.1) doesn't provide api routes, but in the next version which is v1.2, there will be an api routes and docs about using them.

**Comment by afrasiyabhaider** [comment]
@munafio is there any release date available?

**Comment by munafio** [comment]
> @munafio is there any release date available?
Actually, no. I'll do my best to release it ASAP.

**Comment by munafio** [comment]
@afrasiyabhaider Actually, Chatify v1.2.0 will not have API routes, because the whole project is not written to use it with APIs .. 

Chatify v2 as I planning, will be re-designed completely and will come up with a better UI/UX  and code quality, APIs, security improvements, and mush more .. and the UI will be design with Vue.js .

after releasing v1.2.0 which will be released in the next few days, I'll announce about Chatify v2 and all details related to it and what features that will be there ... like so.

**Comment by afrasiyabhaider** [comment]
@munafio I wanted to tell you that I've managed to write API routes by using your web-based code... Tell me if you need a Postman doc from me. :)

**Comment by spartyboy** [comment]
Can't there be two options 1 for view and the order for jQuery.. so we just stick to the one we prefer for v2.. pls put that in consideration

**Comment by Adam-Oudaimah** [comment]
> @munafio I wanted to tell you that I've managed to write API routes by using your web-based code... Tell me if you need a Postman doc from me. :)

Please could you provide me the Postman doc?

**Comment by robertowzzz** [comment]
> @munafio I wanted to tell you that I've managed to write API routes by using your web-based code... Tell me if you need a Postman doc from me. :)

Could you also provide me the postman doc? Please :( Thank you!

**Comment by afrasiyabhaider** [comment]
> > @munafio I wanted to tell you that I've managed to write API routes by using your web-based code... Tell me if you need a Postman doc from me. :)
> 
> Could you also provide me the postman doc? Please :( Thank you!

Sent on your request

**Comment by afrasiyabhaider** [comment]
https://documenter.getpostman.com/view/8822545/UV5ZAw6F
