### ISSUE TITLE
Menu not popping up on Firefox

### ISSUE THREAD

**Issue by kaip-e** [munafio/chatify#95]
I'm having a issue where the chat menu does not show up by clicking the cog icon. However on all other plattforms it seems to work. A quick advice on how to resolve this issue would be great.

![image](https://user-images.githubusercontent.com/58008914/117456573-a5da8600-af48-11eb-9fb1-420251fac10e.png)

Thanks for the help! 

Edit: By changing the HTML so that the "settings" tab is showing ( changing the display property and adding the app-show-modal class ) and i can apply changes. The JS for hiding the container is working as expected.

P.S.: Really love this Package so far :)

**Comment by munafio** [comment]
@kaip-e you have the ability to change the js/css/html assets and customize it to meet your needs by publishing the assets as mentioned in the documentation

**Comment by sofhin** [comment]
@kaip-e could you please provide the details or the code that you have change?
Thanks in advance
