### ISSUE TITLE
Use with multiple guards

### ISSUE THREAD

**Issue by spartyboy** [munafio/chatify#98]
How do i configure chat to b between multiple guards assuming between users and admin?

**Comment by munafio** [comment]
@spartyboy Thanks for reaching out, 
currently, this package does not support multi-guard system by default, but you have the ability to change/modify package's assets (views, js, css, or controllers) as mentioned in the docs .. so you can implement it yourself.

**Comment by spartyboy** [comment]
I implemented it but haven't made it work generally as for now it only suit my usecase i should do that any time soon though and make a pull request

**Comment by alihastam** [comment]
add   `->where('id',2) ` in `App\Http\Controllers\vendor\Chatify\MessagesController` 
```
public function search(Request $request)
    {
        $getRecords = null;
        $input = trim(filter_var($request['input']));

        $records = User::where('id','!=',Auth::user()->id)
                     ->where('id',2)
                    ->where('name', 'LIKE', "%{$input}%")
                    ->paginate($request->per_page ?? $this->perPage);
        foreach ($records->items() as $record) {
            $getRecords .= view('Chatify::layouts.listItem', [
                'get' => 'search_item',
                'user' => Chatify::getUserWithAvatar($record),
            ])->render();
        }
        if($records->total() < 1){
            $getRecords = '<p class="message-hint center-el"><span>Nothing to show.</span></p>';
        }
        // send the response
        return Response::json([
            'records' => $getRecords,
            'total' => $records->total(),
            'last_page' => $records->lastPage()
        ], 200);
    }
```

**Comment by Emad-2002** [comment]
> add `->where('id',2) ` in `App\Http\Controllers\vendor\Chatify\MessagesController`
> 
> ```
> public function search(Request $request)
>     {
>         $getRecords = null;
>         $input = trim(filter_var($request['input']));
> 
>         $records = User::where('id','!=',Auth::user()->id)
>                      ->where('id',2)
>                     ->where('name', 'LIKE', "%{$input}%")
>                     ->paginate($request->per_page ?? $this->perPage);
>         foreach ($records->items() as $record) {
>             $getRecords .= view('Chatify::layouts.listItem', [
>                 'get' => 'search_item',
>                 'user' => Chatify::getUserWithAvatar($record),
>             ])->render();
>         }
>         if($records->total() < 1){
>             $getRecords = '<p class="message-hint center-el"><span>Nothing to show.</span></p>';
>         }
>         // send the response
>         return Response::json([
>             'records' => $getRecords,
>             'total' => $records->total(),
>             'last_page' => $records->lastPage()
>         ], 200);
>     }
> ```

I tried but nothing happened, for you what worked here?
