### ISSUE TITLE
It seems like that it doesn't support on Laravel 8

### ISSUE THREAD

**Issue by nikhil-lu210** [munafio/chatify#99]
I'm trying to implement this package into my Laravel 8 Project. But it's throwing errors. What should I do now...?

I just badly need to implement a real time chat on my project.

[[Note: I've used this package before twice in my Laravel 7 project. And it's worked fine as well.]]

**Comment by mprince2k18** [comment]
Same here.
I am facing a blank conversation blade where no click method is working.

**Comment by imajkumar** [comment]
update composer 
"pusher/pusher-php-server": "^7.0"
its works very nice in laravel 8 also 
Thanks @munafio

**Comment by munafio** [comment]
@nikhil-lu210 @mprince2k18 Please read Notes section mentioned in the Readme.md (Documentation).
